# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Execution tracer installation hook."""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

from pysymex._internal.logging.root import get_logger
from pysymex._internal.tracing.tracer.proxy.solver import TracingSolverProxy

logger = get_logger(__name__)

if TYPE_CHECKING:
    import dis
    from collections.abc import Callable

    from pysymex._internal.analysis.detectors.detector.types import Issue
    from pysymex._internal.config.tracing.settings import TracerConfig
    from pysymex._internal.core.state.record import VMState
    from pysymex._internal.execution.detectors.telemetry import DetectorQueryEvent
    from pysymex._internal.execution.executors.core import SymbolicExecutor
    from pysymex._internal.execution.fallback.types import FallbackEvent
    from pysymex._internal.execution.feasibility.telemetry import PathFeasibilityEvent
    from pysymex._internal.execution.scheduling.telemetry import SchedulerEvent
    from pysymex._internal.tracing.tracer.core import ExecutionTracer


class TracerInstallMixin:
    """Executor hook installation behavior for execution tracers."""

    if TYPE_CHECKING:
        config: TracerConfig
        _current_state: VMState | None
        _fallback_line_resolver: Callable[[int], int | None] | None

        def pre_step(self, executor: SymbolicExecutor, state: VMState) -> None:
            """Capture a lightweight snapshot of the state before an instruction dispatches.

            Args:
                executor: The symbolic executor running the code.
                state: The current virtual machine state before dispatch.

            """
            ...

        def post_step(
            self,
            executor: SymbolicExecutor,
            state: VMState,
            instr: dis.Instruction,
        ) -> None:
            """Emit a step delta event after an instruction has been dispatched.

            Args:
                executor: The symbolic executor running the code.
                state: The virtual machine state after the instruction has executed.
                instr: The bytecode instruction that was executed.

            """
            ...

        def on_fork(
            self,
            executor: SymbolicExecutor,
            parent_state: VMState,
            child_states: list[VMState],
        ) -> None:
            """Handle path forks during symbolic execution.

            Constructs and emits a keyframe event reflecting the state at the fork point
            and mapping parent-child relationships in the execution path tree.

            Args:
                executor: The symbolic executor running the code.
                parent_state: The virtual machine state from which the fork originates.
                child_states: The list of new child states generated by the fork.

            """
            ...

        def on_prune(self, executor: SymbolicExecutor, state: VMState, reason: str) -> None:
            """Handle state pruning during symbolic execution.

            Constructs and emits a keyframe event when a path is pruned from the worklist.

            Args:
                executor: The symbolic executor running the code.
                state: The virtual machine state that was pruned.
                reason: The reason for pruning the path (e.g., infeasible).

            """
            ...

        def on_issue(self, executor: SymbolicExecutor, state: VMState, issue: Issue) -> None:
            """Handle issue emission when a bug is detected during symbolic execution.

            Constructs and writes keyframes and issue telemetry events, serializing
            associated Z3 models, path constraints, and source locations.

            Args:
                executor: The symbolic executor running the code.
                state: The virtual machine state at the time of issue detection.
                issue: The detected issue details.

            """
            ...

        def on_fallback_event(self, event: FallbackEvent) -> None:
            """Handle fallback or degraded-execution event tracing.

            Args:
                event: The structured fallback event recorded by the execution session.

            """
            ...

        def on_detector_query_event(self, event: DetectorQueryEvent) -> None:
            """Handle detector feasibility-query event tracing.

            Args:
                event: The bounded detector-query telemetry record.

            """
            ...

        def on_path_feasibility_event(self, event: PathFeasibilityEvent) -> None:
            """Handle path-feasibility policy event tracing.

            Args:
                event: The bounded path-feasibility telemetry record.

            """
            ...

        def on_scheduler_event(self, event: SchedulerEvent) -> None:
            """Handle path-frontier scheduler event tracing.

            Args:
                event: The bounded scheduler telemetry record.

            """
            ...

    def install(self, executor: SymbolicExecutor) -> None:
        """Register all tracer hooks with *executor* and wrap its solver.

        This must be called **before** ``execute_function`` / ``execute_code``,
        but **after** ``start_session``.

        Args:
            executor: The :class:`~pysymex._internal.execution.executors.core.SymbolicExecutor`
                       whose execution will be traced.

        """
        if not self.config.enabled:
            logger.verbose("Skipping tracer installation because tracing is disabled")
            return

        executor.register_hook("pre_step", self.pre_step)
        executor.register_hook("post_step", self.post_step)
        executor.register_hook("on_fork", self.on_fork)
        executor.register_hook("on_prune", self.on_prune)
        executor.register_hook("on_issue", self.on_issue)
        executor.session.add_fallback_event_observer(self.on_fallback_event)
        executor.session.add_detector_query_event_observer(self.on_detector_query_event)
        executor.session.add_path_feasibility_event_observer(self.on_path_feasibility_event)
        executor.session.add_scheduler_event_observer(self.on_scheduler_event)
        self._fallback_line_resolver = executor.session.pc_to_line.get

        def state_getter() -> VMState | None:
            """Return the current VM state for telemetry context."""
            return self._current_state

        executor.solver = TracingSolverProxy(
            executor.solver,
            cast("ExecutionTracer", self),
            state_getter,
        )
        logger.info("Installed execution tracer hooks and solver proxy")
