from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import Generic, SupportsIndex, TypeAlias, TypeVar, overload

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)


class NDArray(Generic[_T_co]):
    shape: tuple[int, ...]
    ndim: int
    size: int
    dtype: object
    nbytes: int

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    @overload
    def __getitem__(self, index: SupportsIndex) -> _T_co: ...
    @overload
    def __getitem__(self, index: str) -> object: ...
    @overload
    def __getitem__(self, index: slice | tuple[object, ...]) -> NDArray[_T_co]: ...
    def __setitem__(self, index: SupportsIndex | slice | tuple[object, ...], value: object) -> None: ...
    def astype(self, dtype: object) -> NDArray[_T]: ...
    def copy(self) -> NDArray[_T_co]: ...
    def reshape(self, *shape: int | tuple[int, ...]) -> NDArray[_T_co]: ...
    def ravel(self) -> NDArray[_T_co]: ...
    def view(self, dtype: object = ...) -> NDArray[_T_co]: ...
    def __add__(self, other: object) -> NDArray[_T_co]: ...
    def __radd__(self, other: object) -> NDArray[_T_co]: ...
    def __sub__(self, other: object) -> NDArray[_T_co]: ...
    def __rsub__(self, other: object) -> NDArray[_T_co]: ...
    def __mul__(self, other: object) -> NDArray[_T_co]: ...
    def __rmul__(self, other: object) -> NDArray[_T_co]: ...
    def __truediv__(self, other: object) -> NDArray[_T_co]: ...
    def __rtruediv__(self, other: object) -> NDArray[_T_co]: ...
    def __and__(self, other: object) -> NDArray[_T_co]: ...
    def __rand__(self, other: object) -> NDArray[_T_co]: ...
    def sum(self) -> _T_co: ...


class NBitBase:
    ...


ArrayLike: TypeAlias = NDArray[object] | Sequence[object] | int | float | bool
