"""Type stubs for numba.cuda module."""

from __future__ import annotations

from collections.abc import Callable, Sequence
from types import TracebackType
from typing import Literal, TypeVar, overload

import numpy as np
import numpy.typing as npt

from numba import (
    CUDADispatcher,
    CUDAEvent,
    CUDAStream,
    DeviceNDArray,
    NumbaType,
    _CUDADevice,
    _DeferCleanup,
    _Dim3,
    _GPUList,
)

_F = TypeVar("_F", bound=Callable[..., object])
_T = TypeVar("_T")
_ScalarType = TypeVar("_ScalarType", bound=np.generic)
_ScalarType2 = TypeVar("_ScalarType2", bound=np.generic)

_ShapeLike = int | tuple[int, ...]
_DTypeLike = type[_ScalarType] | np.dtype[_ScalarType] | str
_Numeric = int | float | complex | np.generic
_ArrayLike = _Numeric | Sequence[_Numeric] | npt.NDArray[np.generic]
_Signature = str | tuple[type[np.generic] | str, ...] | list[str | tuple[type[np.generic] | str, ...]]

# Re-export
from numba import DeviceNDArray as DeviceNDArray

# ── Device array creation ──────────────────────────────────────────

@overload
def to_device(ary: npt.NDArray[_ScalarType], stream: int | CUDAStream = 0, copy: bool = True) -> DeviceNDArray[_ScalarType]: ...
@overload
def to_device(ary: np.ndarray[tuple[int, ...], _ScalarType], stream: int | CUDAStream = 0, copy: bool = True) -> DeviceNDArray[_ScalarType]: ...
@overload
def to_device(ary: Sequence[int], stream: int | CUDAStream = 0, copy: bool = True) -> DeviceNDArray[np.int64]: ...
@overload
def to_device(ary: Sequence[float], stream: int | CUDAStream = 0, copy: bool = True) -> DeviceNDArray[np.float64]: ...

@overload
def device_array(shape: _ShapeLike, dtype: type[np.float64] | Literal["float64"] = ..., strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C", stream: int | CUDAStream = 0) -> DeviceNDArray[np.float64]: ...
@overload
def device_array(shape: _ShapeLike, dtype: type[np.float32] | Literal["float32"], strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C", stream: int | CUDAStream = 0) -> DeviceNDArray[np.float32]: ...
@overload
def device_array(shape: _ShapeLike, dtype: type[np.int32] | Literal["int32"], strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C", stream: int | CUDAStream = 0) -> DeviceNDArray[np.int32]: ...
@overload
def device_array(shape: _ShapeLike, dtype: type[np.int64] | Literal["int64"], strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C", stream: int | CUDAStream = 0) -> DeviceNDArray[np.int64]: ...
@overload
def device_array(shape: _ShapeLike, dtype: np.dtype[_ScalarType], strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C", stream: int | CUDAStream = 0) -> DeviceNDArray[_ScalarType]: ...

def device_array_like(ary: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], stream: int | CUDAStream = 0) -> DeviceNDArray[_ScalarType]: ...

def pinned_array(shape: _ShapeLike, dtype: _DTypeLike[_ScalarType] = ..., strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C") -> npt.NDArray[_ScalarType]: ...

def pinned_array_like(ary: npt.NDArray[_ScalarType]) -> npt.NDArray[_ScalarType]: ...

def mapped_array(shape: _ShapeLike, dtype: _DTypeLike[_ScalarType] = ..., strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C") -> npt.NDArray[_ScalarType]: ...

def managed_array(shape: _ShapeLike, dtype: _DTypeLike[_ScalarType] = ..., strides: tuple[int, ...] | None = None, order: Literal["C", "F"] = "C") -> npt.NDArray[_ScalarType]: ...

# ── Kernel compilation ─────────────────────────────────────────────

@overload
def jit(func: _F) -> CUDADispatcher: ...
@overload
def jit(
    signature: _Signature = ...,
    *,
    device: Literal[True],
    inline: bool | Literal["always", "never"] = False,
    link: list[str] = ...,
    debug: bool = False,
    opt: bool = True,
    lineinfo: bool = False,
    cache: bool = False,
    fastmath: bool = False,
    max_registers: int | None = None,
) -> Callable[[_F], _F]: ...
@overload
def jit(
    signature: _Signature = ...,
    *,
    device: bool = False,
    inline: bool | Literal["always", "never"] = False,
    link: list[str] = ...,
    debug: bool = False,
    opt: bool = True,
    lineinfo: bool = False,
    cache: bool = False,
    fastmath: bool = False,
    max_registers: int | None = None,
) -> Callable[[_F], CUDADispatcher]: ...

# ── Thread/block intrinsics ────────────────────────────────────────

@overload
def grid(ndim: Literal[1]) -> int: ...
@overload
def grid(ndim: Literal[2]) -> tuple[int, int]: ...
@overload
def grid(ndim: Literal[3]) -> tuple[int, int, int]: ...
@overload
def grid(ndim: int) -> int | tuple[int, ...]: ...

@overload
def gridsize(ndim: Literal[1]) -> int: ...
@overload
def gridsize(ndim: Literal[2]) -> tuple[int, int]: ...
@overload
def gridsize(ndim: Literal[3]) -> tuple[int, int, int]: ...
@overload
def gridsize(ndim: int) -> int | tuple[int, ...]: ...

threadIdx: _Dim3
blockIdx: _Dim3
blockDim: _Dim3
gridDim: _Dim3

def warpsize() -> int: ...
def laneid() -> int: ...

# ── Synchronization ────────────────────────────────────────────────

def syncthreads() -> None: ...
def syncthreads_count(predicate: bool) -> int: ...
def syncthreads_and(predicate: bool) -> bool: ...
def syncthreads_or(predicate: bool) -> bool: ...
def syncwarp(mask: int = 0xFFFFFFFF) -> None: ...
def synchronize() -> None: ...

# ── Warp primitives ────────────────────────────────────────────────

def shfl_sync(mask: int, value: _Numeric, src_lane: int) -> _Numeric: ...
def shfl_up_sync(mask: int, value: _Numeric, delta: int) -> _Numeric: ...
def shfl_down_sync(mask: int, value: _Numeric, delta: int) -> _Numeric: ...
def shfl_xor_sync(mask: int, value: _Numeric, lane_mask: int) -> _Numeric: ...
def vote_sync(mask: int, predicate: bool) -> int: ...
def all_sync(mask: int, predicate: bool) -> bool: ...
def any_sync(mask: int, predicate: bool) -> bool: ...
def ballot_sync(mask: int, predicate: bool) -> int: ...
def match_any_sync(mask: int, value: int) -> int: ...
def match_all_sync(mask: int, value: int) -> tuple[int, bool]: ...
def activemask() -> int: ...
def lanemask_lt() -> int: ...

# ── Memory ─────────────────────────────────────────────────────────

class local:
    @staticmethod
    def array(shape: _ShapeLike, dtype: type[_ScalarType] | np.dtype[_ScalarType]) -> npt.NDArray[_ScalarType]: ...

class shared:
    @staticmethod
    def array(shape: _ShapeLike, dtype: type[_ScalarType] | np.dtype[_ScalarType]) -> npt.NDArray[_ScalarType]: ...

class const:
    @staticmethod
    def array_like(ary: npt.NDArray[_ScalarType]) -> npt.NDArray[_ScalarType]: ...

# ── Atomics ────────────────────────────────────────────────────────

class atomic:
    @staticmethod
    def add(array: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], index: int | tuple[int, ...], value: _Numeric) -> _Numeric: ...
    @staticmethod
    def sub(array: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], index: int | tuple[int, ...], value: _Numeric) -> _Numeric: ...
    @staticmethod
    def max(array: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], index: int | tuple[int, ...], value: _Numeric) -> _Numeric: ...
    @staticmethod
    def min(array: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], index: int | tuple[int, ...], value: _Numeric) -> _Numeric: ...
    @staticmethod
    def and_(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], value: int) -> int: ...
    @staticmethod
    def or_(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], value: int) -> int: ...
    @staticmethod
    def xor(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], value: int) -> int: ...
    @staticmethod
    def inc(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], value: int) -> int: ...
    @staticmethod
    def dec(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], value: int) -> int: ...
    @staticmethod
    def exch(array: npt.NDArray[_ScalarType] | DeviceNDArray[_ScalarType], index: int | tuple[int, ...], value: _Numeric) -> _Numeric: ...
    @staticmethod
    def compare_and_swap(array: npt.NDArray[np.integer[np.typing.NBitBase]] | DeviceNDArray[np.integer[np.typing.NBitBase]], index: int | tuple[int, ...], old: int, val: int) -> int: ...

# ── Streams and events ─────────────────────────────────────────────

def stream() -> CUDAStream: ...
def default_stream() -> CUDAStream: ...
def event(timing: bool = True) -> CUDAEvent: ...

# ── Device management ──────────────────────────────────────────────

def is_available() -> bool: ...
def detect() -> bool: ...
def select_device(device_id: int) -> None: ...
def get_current_device() -> _CUDADevice: ...
def list_devices() -> list[_CUDADevice]: ...
def gpus() -> _GPUList: ...
def close() -> None: ...
def defer_cleanup() -> _DeferCleanup: ...
def profile_start() -> None: ...
def profile_stop() -> None: ...

# ── Device math ────────────────────────────────────────────────────

def fma(a: float, b: float, c: float) -> float: ...
def cbrt(x: float) -> float: ...
def brev(x: int) -> int: ...
def clz(x: int) -> int: ...
def ffs(x: int) -> int: ...
def popc(x: int) -> int: ...
def selp(cond: bool, true_val: _T, false_val: _T) -> _T: ...
