# pysymex: Python Symbolic Execution & Formal Verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


"""Common utilities shared across opcode handlers."""

from __future__ import annotations

BUILTIN_TYPES: dict[str, str] = {
    "int": "int",
    "float": "float",
    "complex": "complex",
    "str": "str",
    "bool": "bool",
    "bytes": "bytes",
    "bytearray": "bytearray",
    "memoryview": "memoryview",
    "list": "list",
    "dict": "dict",
    "tuple": "tuple",
    "set": "set",
    "frozenset": "frozenset",
    "object": "object",
    "type": "type",
    "abs": "callable",
    "aiter": "callable",
    "all": "callable",
    "anext": "callable",
    "any": "callable",
    "ascii": "callable",
    "bin": "callable",
    "breakpoint": "callable",
    "callable": "callable",
    "chr": "callable",
    "compile": "callable",
    "delattr": "callable",
    "dir": "callable",
    "divmod": "callable",
    "eval": "callable",
    "exec": "callable",
    "format": "callable",
    "getattr": "callable",
    "globals": "callable",
    "hasattr": "callable",
    "hash": "callable",
    "help": "callable",
    "hex": "callable",
    "id": "callable",
    "input": "callable",
    "isinstance": "callable",
    "issubclass": "callable",
    "iter": "callable",
    "len": "callable",
    "locals": "callable",
    "max": "callable",
    "min": "callable",
    "next": "callable",
    "oct": "callable",
    "open": "callable",
    "ord": "callable",
    "pow": "callable",
    "print": "callable",
    "repr": "callable",
    "round": "callable",
    "setattr": "callable",
    "sorted": "callable",
    "sum": "callable",
    "vars": "callable",
    "__build_class__": "callable",
    "__import__": "callable",
    "classmethod": "callable",
    "enumerate": "callable",
    "filter": "callable",
    "map": "callable",
    "property": "callable",
    "range": "callable",
    "reversed": "callable",
    "slice": "callable",
    "staticmethod": "callable",
    "super": "callable",
    "zip": "callable",
    "True": "bool",
    "False": "bool",
    "None": "NoneType",
    "Ellipsis": "ellipsis",
    "NotImplemented": "NotImplementedType",
    "BaseException": "type",
    "BaseExceptionGroup": "type",
    "Exception": "type",
    "ArithmeticError": "type",
    "AssertionError": "type",
    "AttributeError": "type",
    "BufferError": "type",
    "EOFError": "type",
    "ExceptionGroup": "type",
    "ImportError": "type",
    "LookupError": "type",
    "MemoryError": "type",
    "NameError": "type",
    "OSError": "type",
    "ReferenceError": "type",
    "RuntimeError": "type",
    "StopAsyncIteration": "type",
    "StopIteration": "type",
    "SyntaxError": "type",
    "SystemError": "type",
    "TypeError": "type",
    "ValueError": "type",
    "Warning": "type",
    "BlockingIOError": "type",
    "ChildProcessError": "type",
    "ConnectionError": "type",
    "BrokenPipeError": "type",
    "ConnectionAbortedError": "type",
    "ConnectionRefusedError": "type",
    "ConnectionResetError": "type",
    "FileExistsError": "type",
    "FileNotFoundError": "type",
    "InterruptedError": "type",
    "IsADirectoryError": "type",
    "NotADirectoryError": "type",
    "PermissionError": "type",
    "ProcessLookupError": "type",
    "TimeoutError": "type",
    "IndexError": "type",
    "KeyError": "type",
    "ModuleNotFoundError": "type",
    "UnboundLocalError": "type",
    "IndentationError": "type",
    "TabError": "type",
    "NotImplementedError": "type",
    "RecursionError": "type",
    "UnicodeError": "type",
    "UnicodeDecodeError": "type",
    "UnicodeEncodeError": "type",
    "UnicodeTranslateError": "type",
    "KeyboardInterrupt": "type",
    "SystemExit": "type",
    "GeneratorExit": "type",
    "BytesWarning": "type",
    "DeprecationWarning": "type",
    "EncodingWarning": "type",
    "FutureWarning": "type",
    "ImportWarning": "type",
    "PendingDeprecationWarning": "type",
    "ResourceWarning": "type",
    "RuntimeWarning": "type",
    "SyntaxWarning": "type",
    "UnicodeWarning": "type",
    "UserWarning": "type",
}
