# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

BUILTIN_ALL = [
    "AbsModel",
    "AllModel",
    "AnyModel",
    "AsciiModel",
    "AssertionErrorModel",
    "AttributeErrorModel",
    "BinModel",
    "BoolModel",
    "BreakpointModel",
    "BuiltinBoolModel",
    "BuiltinBytearrayModel",
    "BuiltinBytesModel",
    "BuiltinDictModel",
    "BuiltinFloatModel",
    "BuiltinFrozensetModel",
    "BuiltinIntModel",
    "BuiltinListModel",
    "BuiltinObjectModel",
    "BuiltinSetModel",
    "BuiltinStrModel",
    "BuiltinTupleModel",
    "BuiltinTypeModel",
    "BytearrayModel",
    "BytesModel",
    "CallableModel",
    "ChrModel",
    "ClassmethodModel",
    "CompileModel",
    "CopyrightModel",
    "CreditsModel",
    "DictModel",
    "DirModel",
    "DivmodModel",
    "EnumerateModel",
    "EvalModel",
    "ExceptionTypeModel",
    "ExecModel",
    "ExitModel",
    "FilterModel",
    "FloatModel",
    "FormatModel",
    "FrozensetModel",
    "FunctionModel",
    "GeneratorExitModel",
    "GetattrModel",
    "GlobalsModel",
    "HasattrModel",
    "HashModel",
    "HelpModel",
    "HexModel",
    "IdModel",
    "IndexErrorModel",
    "InputModel",
    "IntModel",
    "IsinstanceModel",
    "IssubclassModel",
    "IterModel",
    "KeyErrorModel",
    "LenModel",
    "LicenseModel",
    "ListModel",
    "LocalsModel",
    "MapModel",
    "MaxModel",
    "MemoryviewModel",
    "MinModel",
    "ModelRegistry",
    "ModelResult",
    "NextModel",
    "NoneModel",
    "NoneTypeModel",
    "NotImplementedErrorModel",
    "ObjectModel",
    "OctModel",
    "OpenModel",
    "OrdModel",
    "PowModel",
    "PrintModel",
    "PropertyModel",
    "QuitModel",
    "RangeModel",
    "ReprModel",
    "ReversedModel",
    "RoundModel",
    "RuntimeErrorModel",
    "SetModel",
    "SetattrModel",
    "SortedModel",
    "StaticmethodModel",
    "StopIterationModel",
    "StrModel",
    "SumModel",
    "SuperModel",
    "TupleModel",
    "TypeErrorModel",
    "TypeModel",
    "TypeModelBase",
    "TypeModelResult",
    "TypeTypeModel",
    "ValueErrorModel",
    "VarsModel",
    "ZeroDivisionErrorModel",
    "ZipModel",
    "create_exception_models",
    "get_default_model_registry",
]
