"""Testing infrastructure for PySpectre.
Provides property-based testing (fuzzing) with Hypothesis,
conformance test generation, and stateful testing machines.
"""

from pyspectre.testing.fuzzing import (
    ConformanceGenerator,
    ConformanceTest,
    MockInstruction,
    PropertyTests,
    SymbolicStateMachine,
    TestSymbolicState,
    arithmetic_ops,
    comparison_ops,
    invariants,
    mock_instructions,
    postconditions,
    preconditions,
    symbolic_booleans,
    symbolic_dicts,
    symbolic_floats,
    symbolic_integers,
    symbolic_lists,
    symbolic_none,
    symbolic_sets,
    symbolic_strings,
    symbolic_tuples,
    symbolic_values,
    z3_arithmetic_exprs,
    z3_bool_exprs,
    z3_bool_vars,
    z3_int_constants,
    z3_int_vars,
)

__all__ = [
    "symbolic_integers",
    "symbolic_booleans",
    "symbolic_strings",
    "symbolic_floats",
    "symbolic_none",
    "symbolic_values",
    "symbolic_lists",
    "symbolic_dicts",
    "symbolic_sets",
    "symbolic_tuples",
    "z3_int_vars",
    "z3_bool_vars",
    "z3_int_constants",
    "z3_arithmetic_exprs",
    "z3_bool_exprs",
    "MockInstruction",
    "arithmetic_ops",
    "comparison_ops",
    "mock_instructions",
    "preconditions",
    "postconditions",
    "invariants",
    "SymbolicStateMachine",
    "TestSymbolicState",
    "PropertyTests",
    "ConformanceTest",
    "ConformanceGenerator",
]
