"""Arithmetic opcode validation case inventory for non-error operations."""

from __future__ import annotations

from tests.repro.arithmetic_validation_error_cases import ARITHMETIC_ERROR_CASES
from tests.repro.arithmetic_validation_types import OpcodeValidationCase, case


ARITHMETIC_CASES: tuple[OpcodeValidationCase, ...] = (
    case(
        "x = +a",
        "UNARY_POSITIVE Concrete",
        initial_values={"a": 5},
        expected_locals={"x": 5},
    ),
    case(
        "x = +a",
        "UNARY_POSITIVE Symbolic",
        symbolic_vars={"a": "int"},
        initial_values={"a": 5},
        expected_locals={"x": 5},
    ),
    case(
        "x = -a",
        "UNARY_NEGATIVE Concrete",
        initial_values={"a": 5},
        expected_locals={"x": -5},
    ),
    case(
        "x = -a",
        "UNARY_NEGATIVE Symbolic",
        symbolic_vars={"a": "int"},
        initial_values={"a": 5},
        expected_locals={"x": -5},
    ),
    case(
        "x = not a",
        "UNARY_NOT Concrete True",
        initial_values={"a": True},
        expected_locals={"x": False},
    ),
    case(
        "x = not a",
        "UNARY_NOT Concrete False",
        initial_values={"a": False},
        expected_locals={"x": True},
    ),
    case(
        "x = not a",
        "UNARY_NOT Symbolic True",
        symbolic_vars={"a": "bool"},
        initial_values={"a": True},
        expected_locals={"x": False},
    ),
    case(
        "x = ~a",
        "UNARY_INVERT Concrete",
        initial_values={"a": 5},
        expected_locals={"x": -6},
    ),
    case(
        "x = ~a",
        "UNARY_INVERT Symbolic",
        symbolic_vars={"a": "int"},
        initial_values={"a": 5},
        expected_locals={"x": -6},
    ),
    case(
        "x = a + b",
        "BINARY_ADD Concrete/Concrete",
        initial_values={"a": 10, "b": 20},
        expected_locals={"x": 30},
    ),
    case(
        "x = a + b",
        "BINARY_ADD Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 10, "b": 20},
        expected_locals={"x": 30},
    ),
    case(
        "x = a + b",
        "BINARY_ADD Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 10, "b": 20},
        expected_locals={"x": 30},
    ),
    case(
        "x = a - b",
        "BINARY_SUBTRACT Concrete/Concrete",
        initial_values={"a": 30, "b": 10},
        expected_locals={"x": 20},
    ),
    case(
        "x = a - b",
        "BINARY_SUBTRACT Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 30, "b": 10},
        expected_locals={"x": 20},
    ),
    case(
        "x = a - b",
        "BINARY_SUBTRACT Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 30, "b": 10},
        expected_locals={"x": 20},
    ),
    case(
        "x = a * b",
        "BINARY_MULTIPLY Concrete/Concrete",
        initial_values={"a": 5, "b": 6},
        expected_locals={"x": 30},
    ),
    case(
        "x = a * b",
        "BINARY_MULTIPLY Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 5, "b": 6},
        expected_locals={"x": 30},
    ),
    case(
        "x = a * b",
        "BINARY_MULTIPLY Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 5, "b": 6},
        expected_locals={"x": 30},
    ),
    case(
        "x = a // b",
        "BINARY_FLOOR_DIVIDE Concrete/Concrete",
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a // b",
        "BINARY_FLOOR_DIVIDE Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a // b",
        "BINARY_FLOOR_DIVIDE Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a % b",
        "BINARY_MODULO Concrete/Concrete",
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 1},
    ),
    case(
        "x = a % b",
        "BINARY_MODULO Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 1},
    ),
    case(
        "x = a % b",
        "BINARY_MODULO Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 10, "b": 3},
        expected_locals={"x": 1},
    ),
    case(
        "x = a ** b",
        "BINARY_POWER Concrete/Concrete",
        initial_values={"a": 2, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a ** b",
        "BINARY_POWER Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 2, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a ** b",
        "BINARY_POWER Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 2, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a << b",
        "BINARY_LSHIFT Concrete/Concrete",
        initial_values={"a": 1, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a << b",
        "BINARY_LSHIFT Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 1, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a << b",
        "BINARY_LSHIFT Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 1, "b": 3},
        expected_locals={"x": 8},
    ),
    case(
        "x = a >> b",
        "BINARY_RSHIFT Concrete/Concrete",
        initial_values={"a": 8, "b": 2},
        expected_locals={"x": 2},
    ),
    case(
        "x = a >> b",
        "BINARY_RSHIFT Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 8, "b": 2},
        expected_locals={"x": 2},
    ),
    case(
        "x = a >> b",
        "BINARY_RSHIFT Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 8, "b": 2},
        expected_locals={"x": 2},
    ),
    case(
        "x = a & b",
        "BINARY_AND Concrete/Concrete",
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a & b",
        "BINARY_AND Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a & b",
        "BINARY_AND Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 3},
    ),
    case(
        "x = a | b",
        "BINARY_OR Concrete/Concrete",
        initial_values={"a": 4, "b": 2},
        expected_locals={"x": 6},
    ),
    case(
        "x = a | b",
        "BINARY_OR Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 4, "b": 2},
        expected_locals={"x": 6},
    ),
    case(
        "x = a | b",
        "BINARY_OR Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 4, "b": 2},
        expected_locals={"x": 6},
    ),
    case(
        "x = a ^ b",
        "BINARY_XOR Concrete/Concrete",
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 4},
    ),
    case(
        "x = a ^ b",
        "BINARY_XOR Symbolic/Concrete",
        symbolic_vars={"a": "int"},
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 4},
    ),
    case(
        "x = a ^ b",
        "BINARY_XOR Concrete/Symbolic",
        symbolic_vars={"b": "int"},
        initial_values={"a": 7, "b": 3},
        expected_locals={"x": 4},
    ),
    *ARITHMETIC_ERROR_CASES,
)
