# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Generate the optional Linux x86_64 seccomp launcher phase.

This module decides whether strict-profile launcher generation is eligible for
the detected architecture and emits trusted source that installs a fixed
syscall filter before running the sandbox harness.
"""

from __future__ import annotations

import os
import platform
import textwrap
from typing import TYPE_CHECKING

from pysymex._internal.logging.root import get_logger

from .shared import SYSCALL_ALLOWLIST_X86_64

if TYPE_CHECKING:
    from pysymex._internal.config.sandbox.types import SandboxConfig

logger = get_logger(__name__)


class LinuxSeccompMixin:
    """Provide architecture-gated seccomp launcher generation for Linux.

    The mixin emits an x86_64-only BPF allowlist launcher on supported hosts.
    Namespace creation and execution are owned by the backend.
    """

    if TYPE_CHECKING:
        config: SandboxConfig

    def _should_enable_seccomp(self) -> bool:
        """Enable seccomp for strict/untrusted profile on supported hosts."""
        try:
            machine_value = platform.machine()
            uname = getattr(os, "uname", None)
            if callable(uname):
                uname_machine = getattr(uname(), "machine", "")
                if isinstance(uname_machine, str) and uname_machine:
                    machine_value = uname_machine
            machine = machine_value.lower()
        except Exception:
            logger.debug("Failed to inspect Linux machine architecture", exc_info=True)
            return False
        return machine in {"x86_64", "amd64"}

    @staticmethod
    def _generate_launcher_script() -> str:
        """Generate the trusted in-namespace launcher that installs seccomp."""
        allowlist = tuple(sorted(SYSCALL_ALLOWLIST_X86_64))
        return textwrap.dedent(
            f"""\
            # pysymex Linux sandbox launcher: trusted code generated by linux.py.
            from __future__ import annotations

            import ctypes
            import runpy
            import sys

            SYSCALL_ALLOWLIST_X86_64 = {allowlist!r}


            def _install_seccomp() -> None:
                _PR_SET_NO_NEW_PRIVS = 38
                _PR_SET_SECCOMP = 22
                _SECCOMP_MODE_FILTER = 2
                _SECCOMP_RET_KILL_PROCESS = 0x80000000
                _SECCOMP_RET_ALLOW = 0x7FFF0000
                _BPF_LD = 0x00
                _BPF_JMP = 0x05
                _BPF_RET = 0x06
                _BPF_W = 0x00
                _BPF_ABS = 0x20
                _BPF_JEQ = 0x10
                _BPF_K = 0x00
                _AUDIT_ARCH_X86_64 = 0xC000003E

                class _SockFilter(ctypes.Structure):
                    _fields_ = [
                        ("code", ctypes.c_ushort),
                        ("jt", ctypes.c_ubyte),
                        ("jf", ctypes.c_ubyte),
                        ("k", ctypes.c_uint),
                    ]

                class _SockFprog(ctypes.Structure):
                    _fields_ = [
                        ("len", ctypes.c_ushort),
                        ("filter", ctypes.POINTER(_SockFilter)),
                    ]

                def _stmt(_code: int, _k: int) -> tuple[int, int, int, int]:
                    return (_code, 0, 0, _k)

                def _jump(
                    _code: int,
                    _k: int,
                    _jt: int,
                    _jf: int,
                ) -> tuple[int, int, int, int]:
                    return (_code, _jt, _jf, _k)

                _ins: list[tuple[int, int, int, int]] = []
                _ins.append(_stmt(_BPF_LD | _BPF_W | _BPF_ABS, 4))
                # If the architecture is x86_64, skip the kill instruction.
                # Any other arch means this x86_64 syscall table is invalid.
                _ins.append(_jump(_BPF_JMP | _BPF_JEQ | _BPF_K, _AUDIT_ARCH_X86_64, 1, 0))
                _ins.append(_stmt(_BPF_RET | _BPF_K, _SECCOMP_RET_KILL_PROCESS))
                _ins.append(_stmt(_BPF_LD | _BPF_W | _BPF_ABS, 0))

                _remaining = len(SYSCALL_ALLOWLIST_X86_64)
                for _nr in SYSCALL_ALLOWLIST_X86_64:
                    _remaining -= 1
                    _ins.append(
                        _jump(
                            _BPF_JMP | _BPF_JEQ | _BPF_K,
                            int(_nr),
                            _remaining + 1,
                            0,
                        )
                    )

                _ins.append(_stmt(_BPF_RET | _BPF_K, _SECCOMP_RET_KILL_PROCESS))
                _ins.append(_stmt(_BPF_RET | _BPF_K, _SECCOMP_RET_ALLOW))

                _arr_t = _SockFilter * len(_ins)
                _arr = _arr_t(*(_SockFilter(_c, _jt, _jf, _k) for _c, _jt, _jf, _k in _ins))
                _prog = _SockFprog(len(_ins), _arr)
                _libc = ctypes.CDLL("libc.so.6", use_errno=True)

                _rc = _libc.prctl(_PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)
                if _rc != 0:
                    _err = ctypes.get_errno()
                    raise OSError(_err, "prctl(PR_SET_NO_NEW_PRIVS) failed in launcher")

                _rc = _libc.prctl(
                    _PR_SET_SECCOMP,
                    _SECCOMP_MODE_FILTER,
                    ctypes.byref(_prog),
                    0,
                    0,
                )
                if _rc != 0:
                    _err = ctypes.get_errno()
                    raise OSError(_err, "prctl(PR_SET_SECCOMP) failed in launcher")


            def _main() -> None:
                if len(sys.argv) < 3:
                    raise SystemExit("linux-launcher: expected harness and target filename")
                _harness = sys.argv[1]
                _target = sys.argv[2]
                sys.argv = [_harness, _target]
                _install_seccomp()
                runpy.run_path(_harness, run_name="__main__")


            if __name__ == "__main__":
                _main()
            """,
        )
