import marshal
import sys
from unittest.mock import patch

import pytest
from pysymex.sandbox.bridge import (
    BytecodeBlob,
    ConcreteResult,
    execute_concrete,
    extract_bytecode,
)

class TestConcreteResult:
    """Test suite for pysymex.sandbox.bridge.ConcreteResult."""

    @pytest.mark.timeout(30)
    def test_initialization(self) -> None:
        """Test basic initialization."""
        result = ConcreteResult(
            succeeded=True,
            return_value=7,
            exception_type=None,
            exception_message=None,
            traceback=None,
            stdout="ok",
            stderr="",
        )
        assert result.succeeded is True
        assert result.return_value == 7
        assert result.stdout == "ok"
        assert result.stderr == ""


class TestBytecodeBlob:
    """Test suite for pysymex.sandbox.bridge.BytecodeBlob."""

    @pytest.mark.timeout(30)
    def test_reconstruct(self) -> None:
        """Test reconstruct behavior."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        blob = BytecodeBlob(
            payload=marshal.dumps(code_obj),
            filename=filename,
            producer_python=(sys.version_info.major, sys.version_info.minor),
        )
        rebuilt = blob.reconstruct()
        assert rebuilt.co_filename == filename

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_filename_mismatch(self) -> None:
        """Rejects tampered payload metadata to prevent cross-file bytecode injection."""
        code_obj = compile("x = 1\n", "actual.py", "exec")
        blob = BytecodeBlob(payload=marshal.dumps(code_obj), filename="different.py")
        with pytest.raises(ValueError):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_version_mismatch(self) -> None:
        """Rejects payloads generated by a different Python minor version for safety."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        wrong_minor = max(0, sys.version_info.minor - 1)
        blob = BytecodeBlob(
            payload=marshal.dumps(code_obj),
            filename=filename,
            producer_python=(sys.version_info.major, wrong_minor),
        )
        if wrong_minor == sys.version_info.minor:
            pytest.skip("Cannot create mismatched Python version tuple in this runtime")
        with pytest.raises(ValueError):
            blob.reconstruct()


@pytest.mark.timeout(30)
def test_extract_bytecode() -> None:
    """Test extract_bytecode behavior."""
    code_obj = compile("value = 5\n", "demo.py", "exec")
    payload = b"__PYSYMEX_BYTECODE__" + marshal.dumps(code_obj)
    with patch("pysymex.sandbox.bridge._run_raw_worker", return_value=payload):
        blob = extract_bytecode(b"value = 5\n", "demo.py", sandbox_config={"allow_weak_backends": True})
    rebuilt = blob.reconstruct()
    assert rebuilt.co_filename == "demo.py"


@pytest.mark.timeout(30)
def test_execute_concrete() -> None:
    """Test execute_concrete behavior."""
    parsed = {"ok": True, "return_value": 9}
    with patch(
        "pysymex.sandbox.bridge._run_json_worker",
        return_value=(parsed, "printed\n", ""),
    ):
        result = execute_concrete(
            b"def f(x):\n    return x + 1\n",
            "f",
            {"x": 8},
            filename="demo.py",
            sandbox_config={"allow_weak_backends": True},
        )
    assert result.succeeded is True
    assert result.return_value == 9
    assert result.stdout == "printed\n"
