import sys
import ast
import base64
import json
import re
from types import CodeType
from typing import TypeGuard
from collections.abc import Mapping
from unittest.mock import patch

import pytest
from pysymex.sandbox.bridge import (
    BytecodeBlob,
    ConcreteResult,
    execute_concrete,
    extract_bytecode,
)
from pysymex.sandbox.types import ExecutionStatus, SandboxBackend, SandboxConfig, SandboxResult


def _is_object_tuple(value: object) -> TypeGuard[tuple[object, ...]]:
    return isinstance(value, tuple)


def _is_object_frozenset(value: object) -> TypeGuard[frozenset[object]]:
    return isinstance(value, frozenset)


def _is_object_mapping(value: object) -> TypeGuard[Mapping[str, object]]:
    return isinstance(value, Mapping)


def _serialize_code_for_bridge(code_obj: CodeType, filename: str) -> dict[str, object]:
    def _serialize_constant(constant: object) -> object:
        if isinstance(constant, CodeType):
            return _serialize_code_for_bridge(constant, filename)
        if _is_object_tuple(constant):
            return {"_type": "tuple", "value": [_serialize_constant(item) for item in constant]}
        if _is_object_frozenset(constant):
            return {
                "_type": "frozenset",
                "value": [_serialize_constant(item) for item in constant],
            }
        if isinstance(constant, bytes):
            return {"_type": "bytes", "value": base64.b64encode(constant).decode("ascii")}
        if isinstance(constant, (int, float, str, type(None), bool)):
            return constant
        return None

    serialized: dict[str, object] = {
        "co_argcount": code_obj.co_argcount,
        "co_posonlyargcount": code_obj.co_posonlyargcount,
        "co_kwonlyargcount": code_obj.co_kwonlyargcount,
        "co_nlocals": code_obj.co_nlocals,
        "co_stacksize": code_obj.co_stacksize,
        "co_flags": code_obj.co_flags,
        "co_code": base64.b64encode(code_obj.co_code).decode("ascii"),
        "co_names": list(code_obj.co_names),
        "co_varnames": list(code_obj.co_varnames),
        "co_freevars": list(code_obj.co_freevars),
        "co_cellvars": list(code_obj.co_cellvars),
        "co_filename": filename,
        "co_name": code_obj.co_name,
        "co_firstlineno": code_obj.co_firstlineno,
        "_type": "CodeType",
        "co_qualname": code_obj.co_qualname,
        "co_linetable": base64.b64encode(code_obj.co_linetable).decode("ascii"),
        "co_exceptiontable": base64.b64encode(code_obj.co_exceptiontable).decode("ascii"),
    }
    serialized["co_consts"] = [_serialize_constant(constant) for constant in code_obj.co_consts]
    return serialized


def _create_bridge_payload(code_obj: CodeType, filename: str) -> bytes:
    return json.dumps(_serialize_code_for_bridge(code_obj, filename)).encode("utf-8")


class TestConcreteResult:
    """Test suite for pysymex.sandbox.bridge.ConcreteResult."""

    @pytest.mark.timeout(30)
    def test_initialization(self) -> None:
        """Test basic initialization."""
        result = ConcreteResult(
            succeeded=True,
            return_value=7,
            exception_type=None,
            exception_message=None,
            traceback=None,
            stdout="ok",
            stderr="",
        )
        assert result.succeeded is True
        assert result.return_value == 7
        assert result.stdout == "ok"
        assert result.stderr == ""


class TestBytecodeBlob:
    """Test suite for pysymex.sandbox.bridge.BytecodeBlob."""

    def _create_mock_json_payload(self, code_obj: CodeType, filename: str = "target.py") -> bytes:
        return _create_bridge_payload(code_obj, filename)

    @pytest.mark.timeout(30)
    def test_reconstruct(self) -> None:
        """Test reconstruct behavior."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, sys.version_info.minor),
        )
        rebuilt = blob.reconstruct()
        assert rebuilt.co_filename == filename

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_filename_mismatch(self) -> None:
        """Rejects tampered payload metadata to prevent cross-file bytecode injection."""
        code_obj = compile("x = 1\n", "actual.py", "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, "actual.py"), filename="different.py"
        )
        with pytest.raises(ValueError):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_version_mismatch(self) -> None:
        """Rejects payloads generated by a different Python minor version for safety."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        wrong_minor = max(0, sys.version_info.minor - 1)
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, wrong_minor),
        )
        if wrong_minor == sys.version_info.minor:
            pytest.skip("Cannot create mismatched Python version tuple in this runtime")
        with pytest.raises(ValueError):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_preserves_bytes_constants(self) -> None:
        """Bytes literals in code constants survive sandbox bytecode serialization."""
        filename = "target.py"
        code_obj = compile("payload = b'abc'\n", filename, "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, sys.version_info.minor),
        )

        rebuilt = blob.reconstruct()

        assert b"abc" in rebuilt.co_consts


@pytest.mark.timeout(30)
def test_extract_bytecode() -> None:
    """Test extract_bytecode behavior."""
    code_obj = compile("value = 5\n", "demo.py", "exec")

    def mock_run_raw_worker(worker_script: str, **kwargs: object) -> bytes:
        match = re.search(r"sys\.stdout\.buffer\.write\((b'.*?') \+ _payload\)", worker_script)
        assert match is not None
        sandbox_cfg = kwargs.get("sandbox_config")
        assert _is_object_mapping(sandbox_cfg)
        assert sandbox_cfg.get("allow_compat_fallback") is False
        assert sandbox_cfg.get("harness_install_audit_hook") is False
        marker_obj: object = ast.literal_eval(match.group(1))
        assert isinstance(marker_obj, bytes)
        marker = marker_obj
        payload = _create_bridge_payload(code_obj, "demo.py")
        return marker + payload

    with patch("pysymex.sandbox.bridge._run_raw_worker", side_effect=mock_run_raw_worker):
        blob = extract_bytecode(
            b"value = 5\n", "demo.py", sandbox_config={"allow_weak_backends": True}
        )
    rebuilt = blob.reconstruct()
    assert rebuilt.co_filename == "demo.py"


@pytest.mark.timeout(30)
def test_extract_bytecode_compat_fallback_handles_unshare_exec_failure() -> None:
    """Scanner bytecode extraction falls back when Linux unshare cannot exec the venv Python."""
    code_obj = compile("value = 5\n", "demo.py", "exec")
    payload = _create_bridge_payload(code_obj, "demo.py")
    configs: list[SandboxConfig] = []

    class FakeSandbox:
        def __init__(self, config: SandboxConfig) -> None:
            configs.append(config)
            self._config = config

        def __enter__(self) -> "FakeSandbox":
            return self

        def __exit__(
            self,
            exc_type: type[BaseException] | None,
            exc_val: BaseException | None,
            exc_tb: object,
        ) -> None:
            return None

        def execute_code(
            self,
            code: str | bytes,
            *,
            filename: str = "sandbox_code.py",
            input_data: bytes | None = None,
            extra_files: dict[str, bytes] | None = None,
        ) -> SandboxResult:
            _ = filename
            _ = input_data
            _ = extra_files
            if self._config.backend is not SandboxBackend.SUBPROCESS:
                return SandboxResult(
                    status=ExecutionStatus.FAILED,
                    exit_code=1,
                    stderr=(
                        b"unshare: failed to execute /opt/venv/bin/python: "
                        b"No such file or directory\n"
                    ),
                )

            assert isinstance(code, str)
            match = re.search(r"sys\.stdout\.buffer\.write\((b'.*?') \+ _payload\)", code)
            assert match is not None
            marker_obj: object = ast.literal_eval(match.group(1))
            assert isinstance(marker_obj, bytes)
            return SandboxResult(
                status=ExecutionStatus.SUCCESS,
                exit_code=0,
                stdout=marker_obj + payload,
            )

    with patch("pysymex.sandbox.SecureSandbox", FakeSandbox):
        blob = extract_bytecode(
            b"value = 5\n",
            "demo.py",
            sandbox_config={"allow_compat_fallback": True},
        )

    assert blob.reconstruct().co_filename == "demo.py"
    assert len(configs) == 2
    assert configs[1].backend is SandboxBackend.SUBPROCESS
    assert configs[1].allow_weak_backends is True


@pytest.mark.timeout(30)
def test_execute_concrete() -> None:
    """Test execute_concrete behavior."""
    parsed = {"ok": True, "return_value": 9}
    with patch(
        "pysymex.sandbox.bridge._run_json_worker",
        return_value=(parsed, "printed\n", ""),
    ):
        result = execute_concrete(
            b"def f(x):\n    return x + 1\n",
            "f",
            {"x": 8},
            filename="demo.py",
            sandbox_config={"allow_weak_backends": True},
        )
    assert result.succeeded is True
    assert result.return_value == 9
    assert result.stdout == "printed\n"
