import json
import sys
from types import CodeType

import pytest

from pysymex._internal.sandbox.bridge.blobs import BytecodeBlob, ConcreteResult
from pysymex._internal.sandbox.bridge.serialization import create_bytecode_payload
from tests.unit.sandbox.bridge_test_helpers import create_bridge_payload, is_object_mapping


class TestConcreteResult:
    """Test suite for pysymex._internal.sandbox.bridge.ConcreteResult."""

    @pytest.mark.timeout(30)
    def test_initialization(self) -> None:
        """Test basic initialization."""
        result = ConcreteResult(
            succeeded=True,
            return_value=7,
            exception_type=None,
            exception_message=None,
            traceback=None,
            stdout="ok",
            stderr="",
        )
        assert result.succeeded is True
        assert result.return_value == 7
        assert result.stdout == "ok"
        assert result.stderr == ""


class TestBytecodeBlob:
    """Test suite for pysymex._internal.sandbox.bridge.BytecodeBlob."""

    def _create_mock_json_payload(self, code_obj: CodeType, filename: str = "target.py") -> bytes:
        return create_bridge_payload(code_obj, filename)

    @pytest.mark.timeout(30)
    def test_reconstruct(self) -> None:
        """Test reconstruct behavior."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, sys.version_info.minor),
        )
        rebuilt = blob.reconstruct()
        assert rebuilt.co_filename == filename

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_filename_mismatch(self) -> None:
        """Rejects tampered payload metadata to prevent cross-file bytecode injection."""
        code_obj = compile("x = 1\n", "actual.py", "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, "actual.py"), filename="different.py"
        )
        with pytest.raises(ValueError):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_version_mismatch(self) -> None:
        """Rejects payloads generated by a different Python minor version for safety."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        wrong_minor = max(0, sys.version_info.minor - 1)
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, wrong_minor),
        )
        if wrong_minor == sys.version_info.minor:
            pytest.skip("Cannot create mismatched Python version tuple in this runtime")
        with pytest.raises(ValueError):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_unexpected_schema_fields(self) -> None:
        """Strict schema validation rejects sandbox output shape changes."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        payload = json.loads(create_bytecode_payload(code_obj).decode("utf-8"))
        assert is_object_mapping(payload)
        payload["surprise"] = True
        blob = BytecodeBlob(payload=json.dumps(payload).encode("utf-8"), filename=filename)

        with pytest.raises(ValueError, match="unexpected"):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_rejects_malformed_base64(self) -> None:
        """Bytecode bytes are decoded with strict base64 validation."""
        filename = "target.py"
        code_obj = compile("x = 1\n", filename, "exec")
        payload = json.loads(create_bytecode_payload(code_obj).decode("utf-8"))
        assert is_object_mapping(payload)
        module = payload["module"]
        assert is_object_mapping(module)
        module["code"] = "not valid base64!"
        blob = BytecodeBlob(payload=json.dumps(payload).encode("utf-8"), filename=filename)

        with pytest.raises(ValueError, match="base64"):
            blob.reconstruct()

    @pytest.mark.timeout(30)
    def test_reconstruct_preserves_bytes_constants(self) -> None:
        """Bytes literals in code constants survive sandbox bytecode serialization."""
        filename = "target.py"
        code_obj = compile("payload = b'abc'\n", filename, "exec")
        blob = BytecodeBlob(
            payload=self._create_mock_json_payload(code_obj, filename),
            filename=filename,
            producer_python=(sys.version_info.major, sys.version_info.minor),
        )

        rebuilt = blob.reconstruct()

        assert b"abc" in rebuilt.co_consts
