"""Type stubs for wasmtime — WebAssembly runtime.

This provides minimal stubs for import availability checking.
The actual wasmtime API is extensive but pysymex only checks for availability.
"""

from __future__ import annotations

from collections.abc import Sequence

# Basic types for wasmtime runtime
class Config:
    def __init__(self) -> None: ...
    def cache_config_load_default(self) -> None: ...
    def consume_fuel(self, enabled: bool) -> None: ...


class Engine:
    def __init__(self, config: Config | None = None) -> None: ...


class Store:
    def __init__(self, engine: Engine | None = None, data: object = None) -> None: ...
    def set_fuel(self, fuel: int) -> None: ...
    def consume_fuel(self, fuel: int) -> int: ...


class Module:
    @staticmethod
    def from_file(engine: Engine, path: str) -> Module: ...
    @staticmethod
    def from_binary(engine: Engine, binary: bytes) -> Module: ...


class Instance:
    def __init__(self, store: Store, module: Module, imports: Sequence[object]) -> None: ...
    def exports(self, store: Store) -> Exports: ...


class Exports:
    def __getitem__(self, name: str) -> Func | Memory | Global | Table: ...
    def __iter__(self) -> object: ...


class Func:
    def __call__(self, store: Store, *args: object) -> object: ...


class Memory:
    def data_ptr(self, store: Store) -> int: ...
    def data_len(self, store: Store) -> int: ...
    def grow(self, store: Store, delta: int) -> int: ...


class Global:
    def value(self, store: Store) -> object: ...
    def set_value(self, store: Store, val: object) -> None: ...


class Table:
    def size(self, store: Store) -> int: ...
    def grow(self, store: Store, delta: int, init: object) -> int: ...


class Linker:
    def __init__(self, engine: Engine) -> None: ...
    def define(self, module: str, name: str, item: object) -> None: ...
    def define_wasi(self) -> None: ...
    def instantiate(self, store: Store, module: Module) -> Instance: ...


class WasiConfig:
    def __init__(self) -> None: ...
    def inherit_stdin(self) -> None: ...
    def inherit_stdout(self) -> None: ...
    def inherit_stderr(self) -> None: ...
    def inherit_env(self) -> None: ...
    def inherit_args(self) -> None: ...
    def preopen_dir(self, path: str, guest_path: str) -> None: ...


# Trap for runtime errors
class Trap(Exception):
    def message(self) -> str: ...


# Type definitions
class ValType:
    @staticmethod
    def i32() -> ValType: ...
    @staticmethod
    def i64() -> ValType: ...
    @staticmethod
    def f32() -> ValType: ...
    @staticmethod
    def f64() -> ValType: ...


class FuncType:
    def __init__(self, params: Sequence[ValType], results: Sequence[ValType]) -> None: ...
