"""Type stubs for CuPy — GPU array library with NumPy-compatible API.

CuPy provides GPU-accelerated array operations using CUDA. These stubs
cover all cupy usage in pysymex and common operations.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator, Sequence
from types import TracebackType
from typing import Generic, Literal, Protocol, SupportsIndex, TypeVar, overload

import numpy as np
import numpy.typing as npt

# ── Type Variables ─────────────────────────────────────────────────

_ScalarType = TypeVar("_ScalarType", bound=np.generic)
_ScalarType_co = TypeVar("_ScalarType_co", bound=np.generic, covariant=True)
_ScalarType2 = TypeVar("_ScalarType2", bound=np.generic)
_IntType = TypeVar("_IntType", bound=np.integer[np.typing.NBitBase])
_FloatType = TypeVar("_FloatType", bound=np.floating[np.typing.NBitBase])

# ── Type Aliases ───────────────────────────────────────────────────

_ShapeLike = int | tuple[int, ...]
_DTypeLike = type[_ScalarType] | np.dtype[_ScalarType] | str
_OrderKACF = Literal["K", "A", "C", "F"]
_OrderCF = Literal["C", "F"]
_OrderACF = Literal["A", "C", "F"]
_CastingKind = Literal["no", "equiv", "safe", "same_kind", "unsafe"]
_SortKind = Literal["quicksort", "mergesort", "heapsort", "stable"]
_ModeKind = Literal["raise", "wrap", "clip"]

# Numeric types that can be used in array operations
_Numeric = int | float | complex | np.generic | ndarray[np.generic]
_ArrayLikeInt = int | np.integer[np.typing.NBitBase] | Sequence[int] | npt.NDArray[np.integer[np.typing.NBitBase]]
_ArrayLikeFloat = float | np.floating[np.typing.NBitBase] | Sequence[float] | npt.NDArray[np.floating[np.typing.NBitBase]]
_ArrayLikeBool = bool | np.bool_ | Sequence[bool] | npt.NDArray[np.bool_]
_ArrayLike = _Numeric | Sequence[_Numeric] | npt.NDArray[np.generic] | ndarray[np.generic]

# ── ndarray — Core GPU array class ────────────────────────────────

class ndarray(Generic[_ScalarType_co]):
    """GPU array with NumPy-compatible interface."""

    # ── Properties ─────────────────────────────────────────────────

    @property
    def data(self) -> memoryview:
        """Raw memory view of the array buffer."""
        ...

    @property
    def ptr(self) -> int:
        """GPU memory pointer as integer."""
        ...

    @property
    def dtype(self) -> np.dtype[_ScalarType_co]:
        """Data type of array elements."""
        ...

    @property
    def shape(self) -> tuple[int, ...]:
        """Array dimensions."""
        ...

    @property
    def strides(self) -> tuple[int, ...]:
        """Byte steps for each dimension."""
        ...

    @property
    def ndim(self) -> int:
        """Number of dimensions."""
        ...

    @property
    def size(self) -> int:
        """Total number of elements."""
        ...

    @property
    def itemsize(self) -> int:
        """Size of one element in bytes."""
        ...

    @property
    def nbytes(self) -> int:
        """Total bytes consumed by elements."""
        ...

    @property
    def T(self) -> ndarray[_ScalarType_co]:
        """Transposed view of the array."""
        ...

    @property
    def flat(self) -> Iterator[_ScalarType_co]:
        """Flat iterator over elements."""
        ...

    @property
    def real(self) -> ndarray[np.floating[np.typing.NBitBase]]:
        """Real part of complex array."""
        ...

    @property
    def imag(self) -> ndarray[np.floating[np.typing.NBitBase]]:
        """Imaginary part of complex array."""
        ...

    @property
    def device(self) -> Device:
        """Device where the array resides."""
        ...

    # ── Core methods ───────────────────────────────────────────────

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __index__(self) -> int: ...

    # ── Transfer methods ───────────────────────────────────────────

    def get(
        self,
        stream: Stream | None = None,
        order: _OrderKACF = "C",
        out: npt.NDArray[_ScalarType_co] | None = None,
    ) -> npt.NDArray[_ScalarType_co]:
        """Copy array to host memory."""
        ...

    def set(
        self,
        arr: npt.NDArray[_ScalarType_co],
        stream: Stream | None = None,
    ) -> None:
        """Copy data from host array to GPU."""
        ...

    # ── View and reshape methods ───────────────────────────────────

    @overload
    def view(self, dtype: type[_ScalarType2]) -> ndarray[_ScalarType2]: ...
    @overload
    def view(self, dtype: np.dtype[_ScalarType2]) -> ndarray[_ScalarType2]: ...

    def reshape(
        self,
        *shape: int | tuple[int, ...],
        order: _OrderACF = "C",
    ) -> ndarray[_ScalarType_co]: ...

    def ravel(self, order: _OrderKACF = "C") -> ndarray[_ScalarType_co]: ...

    def flatten(self, order: _OrderKACF = "C") -> ndarray[_ScalarType_co]: ...

    def squeeze(self, axis: int | tuple[int, ...] | None = None) -> ndarray[_ScalarType_co]: ...

    def transpose(self, *axes: int) -> ndarray[_ScalarType_co]: ...

    def swapaxes(self, axis1: int, axis2: int) -> ndarray[_ScalarType_co]: ...

    # ── Indexing and slicing ───────────────────────────────────────

    @overload
    def __getitem__(self, key: SupportsIndex) -> _ScalarType_co: ...
    @overload
    def __getitem__(self, key: slice) -> ndarray[_ScalarType_co]: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex | slice | None | ndarray[np.bool_] | ndarray[np.intp], ...]) -> ndarray[_ScalarType_co]: ...
    @overload
    def __getitem__(self, key: ndarray[np.bool_]) -> ndarray[_ScalarType_co]: ...
    @overload
    def __getitem__(self, key: ndarray[np.intp]) -> ndarray[_ScalarType_co]: ...
    @overload
    def __getitem__(self, key: npt.NDArray[np.bool_]) -> ndarray[_ScalarType_co]: ...
    @overload
    def __getitem__(self, key: npt.NDArray[np.intp]) -> ndarray[_ScalarType_co]: ...

    def __setitem__(self, key: SupportsIndex | slice | tuple[SupportsIndex | slice | None, ...] | ndarray[np.bool_] | ndarray[np.intp], value: _Numeric) -> None: ...

    # ── Arithmetic operators ───────────────────────────────────────

    def __add__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __radd__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __iadd__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __sub__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __rsub__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __isub__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __mul__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __rmul__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __imul__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __truediv__(self, other: _Numeric) -> ndarray[np.floating[np.typing.NBitBase]]: ...
    def __rtruediv__(self, other: _Numeric) -> ndarray[np.floating[np.typing.NBitBase]]: ...
    def __itruediv__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __floordiv__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __rfloordiv__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __ifloordiv__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __mod__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __rmod__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __imod__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __pow__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __rpow__(self, other: _Numeric) -> ndarray[np.generic]: ...
    def __ipow__(self, other: _Numeric) -> ndarray[_ScalarType_co]: ...
    def __neg__(self) -> ndarray[_ScalarType_co]: ...
    def __pos__(self) -> ndarray[_ScalarType_co]: ...
    def __abs__(self) -> ndarray[_ScalarType_co]: ...
    def __matmul__(self, other: ndarray[np.generic] | npt.NDArray[np.generic]) -> ndarray[np.generic]: ...
    def __rmatmul__(self, other: ndarray[np.generic] | npt.NDArray[np.generic]) -> ndarray[np.generic]: ...

    # ── Bitwise operators ──────────────────────────────────────────

    def __and__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __rand__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __iand__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[_ScalarType_co]: ...
    def __or__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __ror__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __ior__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[_ScalarType_co]: ...
    def __xor__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __rxor__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __ixor__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[_ScalarType_co]: ...
    def __invert__(self) -> ndarray[_ScalarType_co]: ...
    def __lshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __rlshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __ilshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[_ScalarType_co]: ...
    def __rshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __rrshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[np.integer[np.typing.NBitBase]]: ...
    def __irshift__(self, other: int | np.integer[np.typing.NBitBase] | ndarray[np.integer[np.typing.NBitBase]]) -> ndarray[_ScalarType_co]: ...

    # ── Comparison operators ───────────────────────────────────────

    def __eq__(self, other: object) -> ndarray[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: object) -> ndarray[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: _Numeric) -> ndarray[np.bool_]: ...
    def __le__(self, other: _Numeric) -> ndarray[np.bool_]: ...
    def __gt__(self, other: _Numeric) -> ndarray[np.bool_]: ...
    def __ge__(self, other: _Numeric) -> ndarray[np.bool_]: ...

    # ── Reduction methods ──────────────────────────────────────────

    @overload
    def sum(
        self,
        axis: None = None,
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
        keepdims: Literal[False] = False,
    ) -> _ScalarType_co: ...
    @overload
    def sum(
        self,
        axis: int | tuple[int, ...],
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
        keepdims: bool = False,
    ) -> ndarray[_ScalarType_co]: ...

    @overload
    def prod(
        self,
        axis: None = None,
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
        keepdims: Literal[False] = False,
    ) -> _ScalarType_co: ...
    @overload
    def prod(
        self,
        axis: int | tuple[int, ...],
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
        keepdims: bool = False,
    ) -> ndarray[_ScalarType_co]: ...

    @overload
    def mean(
        self,
        axis: None = None,
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        keepdims: Literal[False] = False,
    ) -> np.floating[np.typing.NBitBase]: ...
    @overload
    def mean(
        self,
        axis: int | tuple[int, ...],
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        keepdims: bool = False,
    ) -> ndarray[np.floating[np.typing.NBitBase]]: ...

    @overload
    def var(
        self,
        axis: None = None,
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        ddof: int = 0,
        keepdims: Literal[False] = False,
    ) -> np.floating[np.typing.NBitBase]: ...
    @overload
    def var(
        self,
        axis: int | tuple[int, ...],
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        ddof: int = 0,
        keepdims: bool = False,
    ) -> ndarray[np.floating[np.typing.NBitBase]]: ...

    @overload
    def std(
        self,
        axis: None = None,
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        ddof: int = 0,
        keepdims: Literal[False] = False,
    ) -> np.floating[np.typing.NBitBase]: ...
    @overload
    def std(
        self,
        axis: int | tuple[int, ...],
        dtype: _DTypeLike[_FloatType] | None = None,
        out: ndarray[_FloatType] | None = None,
        ddof: int = 0,
        keepdims: bool = False,
    ) -> ndarray[np.floating[np.typing.NBitBase]]: ...

    @overload
    def min(self, axis: None = None, out: ndarray[_ScalarType_co] | None = None, keepdims: Literal[False] = False) -> _ScalarType_co: ...
    @overload
    def min(self, axis: int | tuple[int, ...], out: ndarray[_ScalarType_co] | None = None, keepdims: bool = False) -> ndarray[_ScalarType_co]: ...

    @overload
    def max(self, axis: None = None, out: ndarray[_ScalarType_co] | None = None, keepdims: Literal[False] = False) -> _ScalarType_co: ...
    @overload
    def max(self, axis: int | tuple[int, ...], out: ndarray[_ScalarType_co] | None = None, keepdims: bool = False) -> ndarray[_ScalarType_co]: ...

    @overload
    def argmin(self, axis: None = None, out: ndarray[np.intp] | None = None) -> np.intp: ...
    @overload
    def argmin(self, axis: int, out: ndarray[np.intp] | None = None) -> ndarray[np.intp]: ...

    @overload
    def argmax(self, axis: None = None, out: ndarray[np.intp] | None = None) -> np.intp: ...
    @overload
    def argmax(self, axis: int, out: ndarray[np.intp] | None = None) -> ndarray[np.intp]: ...

    @overload
    def all(self, axis: None = None, out: ndarray[np.bool_] | None = None, keepdims: Literal[False] = False) -> np.bool_: ...
    @overload
    def all(self, axis: int | tuple[int, ...], out: ndarray[np.bool_] | None = None, keepdims: bool = False) -> ndarray[np.bool_]: ...

    @overload
    def any(self, axis: None = None, out: ndarray[np.bool_] | None = None, keepdims: Literal[False] = False) -> np.bool_: ...
    @overload
    def any(self, axis: int | tuple[int, ...], out: ndarray[np.bool_] | None = None, keepdims: bool = False) -> ndarray[np.bool_]: ...

    def cumsum(
        self,
        axis: int | None = None,
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
    ) -> ndarray[_ScalarType_co]: ...

    def cumprod(
        self,
        axis: int | None = None,
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
    ) -> ndarray[_ScalarType_co]: ...

    # ── Utility methods ────────────────────────────────────────────

    def copy(self, order: _OrderKACF = "C") -> ndarray[_ScalarType_co]: ...

    def fill(self, value: _ScalarType_co | int | float | complex) -> None: ...

    def astype(
        self,
        dtype: _DTypeLike[_ScalarType2],
        order: _OrderKACF = "K",
        casting: _CastingKind = "unsafe",
        subok: bool = True,
        copy: bool = True,
    ) -> ndarray[_ScalarType2]: ...

    def clip(
        self,
        a_min: _Numeric | None,
        a_max: _Numeric | None,
        out: ndarray[_ScalarType_co] | None = None,
    ) -> ndarray[_ScalarType_co]: ...

    def repeat(self, repeats: int | Sequence[int], axis: int | None = None) -> ndarray[_ScalarType_co]: ...

    def nonzero(self) -> tuple[ndarray[np.intp], ...]: ...

    def take(
        self,
        indices: _ArrayLikeInt,
        axis: int | None = None,
        out: ndarray[_ScalarType_co] | None = None,
    ) -> ndarray[_ScalarType_co]: ...

    def put(self, indices: _ArrayLikeInt, values: _ArrayLike) -> None: ...

    def diagonal(self, offset: int = 0, axis1: int = 0, axis2: int = 1) -> ndarray[_ScalarType_co]: ...

    def trace(
        self,
        offset: int = 0,
        axis1: int = 0,
        axis2: int = 1,
        dtype: _DTypeLike[_ScalarType2] | None = None,
        out: ndarray[_ScalarType2] | None = None,
    ) -> ndarray[_ScalarType_co]: ...

    def dot(self, b: ndarray[np.generic] | npt.NDArray[np.generic], out: ndarray[np.generic] | None = None) -> ndarray[np.generic]: ...

    def conj(self) -> ndarray[_ScalarType_co]: ...
    def conjugate(self) -> ndarray[_ScalarType_co]: ...

    def sort(
        self,
        axis: int = -1,
        kind: _SortKind | None = None,
        order: str | Sequence[str] | None = None,
    ) -> None: ...

    def argsort(
        self,
        axis: int = -1,
        kind: _SortKind | None = None,
        order: str | Sequence[str] | None = None,
    ) -> ndarray[np.intp]: ...

    def searchsorted(
        self,
        v: _ArrayLike,
        side: Literal["left", "right"] = "left",
        sorter: _ArrayLikeInt | None = None,
    ) -> ndarray[np.intp]: ...

    def tolist(self) -> list[_ScalarType_co | list[_ScalarType_co]]: ...

    def tobytes(self, order: _OrderACF = "C") -> bytes: ...

    # ── NumPy compatibility ────────────────────────────────────────

    def __array__(self, dtype: np.dtype[_ScalarType2] | None = None) -> npt.NDArray[_ScalarType2]: ...

    def __array_ufunc__(
        self,
        ufunc: np.ufunc,
        method: str,
        *inputs: _ArrayLike,
        **kwargs: _Numeric | ndarray[np.generic] | None,
    ) -> ndarray[np.generic] | tuple[ndarray[np.generic], ...]: ...


# ── CUDA Runtime Classes ───────────────────────────────────────────

class Device:
    """CUDA device handle."""

    id: int

    def __init__(self, device: int = 0) -> None: ...

    @property
    def compute_capability(self) -> str: ...

    @property
    def mem_info(self) -> tuple[int, int]: ...

    @property
    def name(self) -> str: ...

    @property
    def pci_bus_id(self) -> str: ...

    @property
    def attributes(self) -> dict[str, int | str | bool]: ...

    @property
    def cublas_handle(self) -> int: ...

    @property
    def cusolver_handle(self) -> int: ...

    @property
    def cusolver_sp_handle(self) -> int: ...

    @property
    def cusparse_handle(self) -> int: ...

    def synchronize(self) -> None: ...
    def use(self) -> None: ...

    def __enter__(self) -> Device: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...


class Stream:
    """CUDA stream for asynchronous operations."""

    ptr: int

    def __init__(
        self,
        null: bool = False,
        non_blocking: bool = False,
        ptds: bool = False,
    ) -> None: ...

    def synchronize(self) -> None: ...

    def add_callback(self, callback: Callable[[Stream, int, object], None], arg: object = None) -> None: ...

    def record(self, event: Event | None = None) -> Event: ...

    def wait_event(self, event: Event) -> None: ...

    @property
    def done(self) -> bool: ...

    def __enter__(self) -> Stream: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...


class Event:
    """CUDA event for timing and synchronization."""

    ptr: int

    def __init__(
        self,
        block: bool = False,
        disable_timing: bool = False,
        interprocess: bool = False,
    ) -> None: ...

    def synchronize(self) -> None: ...
    def record(self, stream: Stream | None = None) -> None: ...

    @property
    def done(self) -> bool: ...


class MemoryPointer:
    """GPU memory pointer wrapper."""

    ptr: int
    device_id: int

    def __init__(self, mem: object, offset: int) -> None: ...

    @property
    def device(self) -> Device: ...

    def copy_from(self, src: MemoryPointer, size: int) -> None: ...
    def copy_from_host(self, src: bytes | memoryview | npt.NDArray[np.generic], size: int) -> None: ...
    def copy_from_host_async(self, src: bytes | memoryview | npt.NDArray[np.generic], size: int, stream: Stream | None = None) -> None: ...
    def copy_to_host(self, dst: memoryview | npt.NDArray[np.generic], size: int) -> None: ...
    def copy_to_host_async(self, dst: memoryview | npt.NDArray[np.generic], size: int, stream: Stream | None = None) -> None: ...
    def memset(self, value: int, size: int) -> None: ...
    def memset_async(self, value: int, size: int, stream: Stream | None = None) -> None: ...


class _Runtime:
    """CUDA runtime API wrapper."""

    @staticmethod
    def getDeviceCount() -> int: ...

    @staticmethod
    def getDeviceProperties(device_id: int) -> dict[str, int | str | bytes]: ...

    @staticmethod
    def deviceCanAccessPeer(device_id: int, peer_device_id: int) -> bool: ...

    @staticmethod
    def setDevice(device_id: int) -> None: ...

    @staticmethod
    def getDevice() -> int: ...

    @staticmethod
    def deviceSynchronize() -> None: ...

    @staticmethod
    def memGetInfo() -> tuple[int, int]: ...


# ── cuda module namespace ──────────────────────────────────────────

class cuda:
    """CUDA functionality namespace."""

    Device = Device
    Stream = Stream
    Event = Event
    MemoryPointer = MemoryPointer
    runtime: _Runtime

    @staticmethod
    def synchronize() -> None: ...

    @staticmethod
    def get_device_id() -> int: ...

    @staticmethod
    def get_current_stream() -> Stream: ...


# ── RawModule / RawKernel — JIT compilation ────────────────────────

class RawKernel:
    """Compiled CUDA kernel."""

    kernel: int
    name: str
    max_threads_per_block: int

    def __call__(
        self,
        grid: tuple[int, ...],
        block: tuple[int, ...],
        args: tuple[ndarray[np.generic] | npt.NDArray[np.generic] | int | float, ...],
        *,
        stream: Stream | None = None,
        shared_mem: int = 0,
    ) -> None: ...

    @property
    def attributes(self) -> dict[str, int]: ...

    def max_dynamic_shared_size_bytes(self) -> int: ...


class RawModule:
    """CUDA module containing kernels."""

    def __init__(
        self,
        code: str = ...,
        *,
        path: str | None = None,
        options: tuple[str, ...] = (),
        backend: Literal["nvrtc", "nvcc"] = "nvrtc",
        translate_cucomplex: bool = False,
        enable_cooperative_groups: bool = False,
        name_expressions: Sequence[str] | None = None,
        jitify: bool = False,
    ) -> None: ...

    def get_function(self, name: str) -> RawKernel: ...

    def get_global(self, name: str) -> tuple[MemoryPointer, int]: ...


# ── Array creation functions ───────────────────────────────────────

@overload
def zeros(shape: _ShapeLike, dtype: type[np.float64] | Literal["float64"] = ...) -> ndarray[np.float64]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.float32] | Literal["float32"]) -> ndarray[np.float32]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.int32] | Literal["int32"]) -> ndarray[np.int32]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.int64] | Literal["int64"]) -> ndarray[np.int64]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.uint8] | Literal["uint8"]) -> ndarray[np.uint8]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.uint16] | Literal["uint16"]) -> ndarray[np.uint16]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.uint32] | Literal["uint32"]) -> ndarray[np.uint32]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.uint64] | Literal["uint64"]) -> ndarray[np.uint64]: ...
@overload
def zeros(shape: _ShapeLike, dtype: type[np.bool_] | Literal["bool"]) -> ndarray[np.bool_]: ...
@overload
def zeros(shape: _ShapeLike, dtype: np.dtype[_ScalarType]) -> ndarray[_ScalarType]: ...

@overload
def empty(shape: _ShapeLike, dtype: type[np.float64] | Literal["float64"] = ...) -> ndarray[np.float64]: ...
@overload
def empty(shape: _ShapeLike, dtype: type[np.float32] | Literal["float32"]) -> ndarray[np.float32]: ...
@overload
def empty(shape: _ShapeLike, dtype: type[np.int32] | Literal["int32"]) -> ndarray[np.int32]: ...
@overload
def empty(shape: _ShapeLike, dtype: type[np.int64] | Literal["int64"]) -> ndarray[np.int64]: ...
@overload
def empty(shape: _ShapeLike, dtype: type[np.uint8] | Literal["uint8"]) -> ndarray[np.uint8]: ...
@overload
def empty(shape: _ShapeLike, dtype: type[np.uint32] | Literal["uint32"]) -> ndarray[np.uint32]: ...
@overload
def empty(shape: _ShapeLike, dtype: np.dtype[_ScalarType]) -> ndarray[_ScalarType]: ...

@overload
def ones(shape: _ShapeLike, dtype: type[np.float64] | Literal["float64"] = ...) -> ndarray[np.float64]: ...
@overload
def ones(shape: _ShapeLike, dtype: type[np.float32] | Literal["float32"]) -> ndarray[np.float32]: ...
@overload
def ones(shape: _ShapeLike, dtype: type[np.int32] | Literal["int32"]) -> ndarray[np.int32]: ...
@overload
def ones(shape: _ShapeLike, dtype: np.dtype[_ScalarType]) -> ndarray[_ScalarType]: ...

@overload
def full(shape: _ShapeLike, fill_value: int, dtype: None = None) -> ndarray[np.int64]: ...
@overload
def full(shape: _ShapeLike, fill_value: float, dtype: None = None) -> ndarray[np.float64]: ...
@overload
def full(shape: _ShapeLike, fill_value: _Numeric, dtype: _DTypeLike[_ScalarType]) -> ndarray[_ScalarType]: ...

def zeros_like(
    a: ndarray[_ScalarType] | npt.NDArray[_ScalarType],
    dtype: _DTypeLike[_ScalarType2] | None = None,
    order: _OrderKACF = "K",
    subok: bool = True,
    shape: _ShapeLike | None = None,
) -> ndarray[_ScalarType] | ndarray[_ScalarType2]: ...

def empty_like(
    a: ndarray[_ScalarType] | npt.NDArray[_ScalarType],
    dtype: _DTypeLike[_ScalarType2] | None = None,
    order: _OrderKACF = "K",
    subok: bool = True,
    shape: _ShapeLike | None = None,
) -> ndarray[_ScalarType] | ndarray[_ScalarType2]: ...

def ones_like(
    a: ndarray[_ScalarType] | npt.NDArray[_ScalarType],
    dtype: _DTypeLike[_ScalarType2] | None = None,
    order: _OrderKACF = "K",
    subok: bool = True,
    shape: _ShapeLike | None = None,
) -> ndarray[_ScalarType] | ndarray[_ScalarType2]: ...

def full_like(
    a: ndarray[_ScalarType] | npt.NDArray[_ScalarType],
    fill_value: _Numeric,
    dtype: _DTypeLike[_ScalarType2] | None = None,
    order: _OrderKACF = "K",
    subok: bool = True,
    shape: _ShapeLike | None = None,
) -> ndarray[_ScalarType] | ndarray[_ScalarType2]: ...

def eye(
    N: int,
    M: int | None = None,
    k: int = 0,
    dtype: _DTypeLike[_ScalarType] = ...,
) -> ndarray[_ScalarType]: ...

def identity(n: int, dtype: _DTypeLike[_ScalarType] = ...) -> ndarray[_ScalarType]: ...

@overload
def arange(stop: int, dtype: type[np.intp] | None = None) -> ndarray[np.intp]: ...
@overload
def arange(start: int, stop: int, step: int = 1, dtype: type[np.intp] | None = None) -> ndarray[np.intp]: ...
@overload
def arange(start: float, stop: float | None = None, step: float = 1.0, dtype: _DTypeLike[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...

@overload
def linspace(
    start: float,
    stop: float,
    num: int = 50,
    endpoint: bool = True,
    retstep: Literal[False] = False,
    dtype: _DTypeLike[_ScalarType] | None = None,
    axis: int = 0,
) -> ndarray[_ScalarType]: ...
@overload
def linspace(
    start: float,
    stop: float,
    num: int = 50,
    endpoint: bool = True,
    retstep: Literal[True] = ...,
    dtype: _DTypeLike[_ScalarType] | None = None,
    axis: int = 0,
) -> tuple[ndarray[_ScalarType], float]: ...

def logspace(
    start: float,
    stop: float,
    num: int = 50,
    endpoint: bool = True,
    base: float = 10.0,
    dtype: _DTypeLike[_ScalarType] | None = None,
    axis: int = 0,
) -> ndarray[_ScalarType]: ...


# ── Array conversion functions ─────────────────────────────────────

def asnumpy(
    a: ndarray[_ScalarType],
    stream: Stream | None = None,
    order: _OrderACF = "C",
    out: npt.NDArray[_ScalarType] | None = None,
) -> npt.NDArray[_ScalarType]: ...

@overload
def asarray(a: npt.NDArray[_ScalarType], dtype: None = None) -> ndarray[_ScalarType]: ...
@overload
def asarray(a: Sequence[int], dtype: None = None) -> ndarray[np.int64]: ...
@overload
def asarray(a: Sequence[float], dtype: None = None) -> ndarray[np.float64]: ...
@overload
def asarray(a: _ArrayLike, dtype: _DTypeLike[_ScalarType]) -> ndarray[_ScalarType]: ...

def ascontiguousarray(a: _ArrayLike, dtype: _DTypeLike[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...

def asfortranarray(a: _ArrayLike, dtype: _DTypeLike[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...

def array(
    obj: _ArrayLike,
    dtype: _DTypeLike[_ScalarType] | None = None,
    copy: bool = True,
    order: Literal["C", "F", "A", "K"] | None = None,
    subok: bool = False,
    ndmin: int = 0,
) -> ndarray[_ScalarType]: ...

def copy(a: ndarray[_ScalarType], order: _OrderKACF = "K") -> ndarray[_ScalarType]: ...


# ── Mathematical functions ─────────────────────────────────────────

def abs(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def absolute(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def sqrt(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def cbrt(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def square(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def exp(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def exp2(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def expm1(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def log(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def log2(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def log10(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def log1p(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def power(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.generic] | None = None) -> ndarray[np.generic]: ...

# Trigonometric
def sin(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def cos(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def tan(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arcsin(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arccos(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arctan(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arctan2(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def sinh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def cosh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def tanh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arcsinh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arccosh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def arctanh(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...

# Rounding
def floor(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def ceil(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def trunc(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def rint(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def around(a: _ArrayLike, decimals: int = 0, out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def round(a: _ArrayLike, decimals: int = 0, out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def fix(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...

# Signs and special
def sign(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def negative(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def positive(x: ndarray[_ScalarType], out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def reciprocal(x: ndarray[np.generic], out: ndarray[np.floating[np.typing.NBitBase]] | None = None) -> ndarray[np.floating[np.typing.NBitBase]]: ...
def clip(a: ndarray[_ScalarType], a_min: _Numeric | None, a_max: _Numeric | None, out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...

# Bitwise
def bitwise_and(x1: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, x2: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def bitwise_or(x1: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, x2: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def bitwise_xor(x1: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, x2: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def bitwise_not(x: ndarray[np.integer[np.typing.NBitBase]], out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def invert(x: ndarray[np.integer[np.typing.NBitBase]], out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def left_shift(x1: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, x2: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...
def right_shift(x1: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, x2: ndarray[np.integer[np.typing.NBitBase]] | _ArrayLikeInt, out: ndarray[np.integer[np.typing.NBitBase]] | None = None) -> ndarray[np.integer[np.typing.NBitBase]]: ...


# ── Reduction functions ────────────────────────────────────────────

@overload
def sum(a: _ArrayLike, axis: None = None, dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None, keepdims: Literal[False] = False) -> np.generic: ...
@overload
def sum(a: _ArrayLike, axis: int | tuple[int, ...], dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None, keepdims: bool = False) -> ndarray[np.generic]: ...

@overload
def prod(a: _ArrayLike, axis: None = None, dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None, keepdims: Literal[False] = False) -> np.generic: ...
@overload
def prod(a: _ArrayLike, axis: int | tuple[int, ...], dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None, keepdims: bool = False) -> ndarray[np.generic]: ...

@overload
def mean(a: _ArrayLike, axis: None = None, dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, keepdims: Literal[False] = False) -> np.floating[np.typing.NBitBase]: ...
@overload
def mean(a: _ArrayLike, axis: int | tuple[int, ...], dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, keepdims: bool = False) -> ndarray[np.floating[np.typing.NBitBase]]: ...

@overload
def var(a: _ArrayLike, axis: None = None, dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, ddof: int = 0, keepdims: Literal[False] = False) -> np.floating[np.typing.NBitBase]: ...
@overload
def var(a: _ArrayLike, axis: int | tuple[int, ...], dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, ddof: int = 0, keepdims: bool = False) -> ndarray[np.floating[np.typing.NBitBase]]: ...

@overload
def std(a: _ArrayLike, axis: None = None, dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, ddof: int = 0, keepdims: Literal[False] = False) -> np.floating[np.typing.NBitBase]: ...
@overload
def std(a: _ArrayLike, axis: int | tuple[int, ...], dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, ddof: int = 0, keepdims: bool = False) -> ndarray[np.floating[np.typing.NBitBase]]: ...

@overload
def min(a: _ArrayLike, axis: None = None, out: ndarray[np.generic] | None = None, keepdims: Literal[False] = False) -> np.generic: ...
@overload
def min(a: _ArrayLike, axis: int | tuple[int, ...], out: ndarray[np.generic] | None = None, keepdims: bool = False) -> ndarray[np.generic]: ...

@overload
def max(a: _ArrayLike, axis: None = None, out: ndarray[np.generic] | None = None, keepdims: Literal[False] = False) -> np.generic: ...
@overload
def max(a: _ArrayLike, axis: int | tuple[int, ...], out: ndarray[np.generic] | None = None, keepdims: bool = False) -> ndarray[np.generic]: ...

@overload
def argmin(a: _ArrayLike, axis: None = None, out: ndarray[np.intp] | None = None) -> np.intp: ...
@overload
def argmin(a: _ArrayLike, axis: int, out: ndarray[np.intp] | None = None) -> ndarray[np.intp]: ...

@overload
def argmax(a: _ArrayLike, axis: None = None, out: ndarray[np.intp] | None = None) -> np.intp: ...
@overload
def argmax(a: _ArrayLike, axis: int, out: ndarray[np.intp] | None = None) -> ndarray[np.intp]: ...

@overload
def all(a: _ArrayLike, axis: None = None, out: ndarray[np.bool_] | None = None, keepdims: Literal[False] = False) -> np.bool_: ...
@overload
def all(a: _ArrayLike, axis: int | tuple[int, ...], out: ndarray[np.bool_] | None = None, keepdims: bool = False) -> ndarray[np.bool_]: ...

@overload
def any(a: _ArrayLike, axis: None = None, out: ndarray[np.bool_] | None = None, keepdims: Literal[False] = False) -> np.bool_: ...
@overload
def any(a: _ArrayLike, axis: int | tuple[int, ...], out: ndarray[np.bool_] | None = None, keepdims: bool = False) -> ndarray[np.bool_]: ...

def cumsum(a: _ArrayLike, axis: int | None = None, dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None) -> ndarray[np.generic]: ...

def cumprod(a: _ArrayLike, axis: int | None = None, dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None) -> ndarray[np.generic]: ...

def nansum(a: _ArrayLike, axis: int | tuple[int, ...] | None = None, dtype: _DTypeLike[_ScalarType] | None = None, out: ndarray[_ScalarType] | None = None, keepdims: bool = False) -> ndarray[np.generic] | np.generic: ...

def nanmean(a: _ArrayLike, axis: int | tuple[int, ...] | None = None, dtype: _DTypeLike[_FloatType] | None = None, out: ndarray[_FloatType] | None = None, keepdims: bool = False) -> ndarray[np.floating[np.typing.NBitBase]] | np.floating[np.typing.NBitBase]: ...


# ── Comparison functions ───────────────────────────────────────────

def equal(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def not_equal(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def less(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def less_equal(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def greater(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def greater_equal(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def isnan(x: ndarray[np.generic], out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def isinf(x: ndarray[np.generic], out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...
def isfinite(x: ndarray[np.generic], out: ndarray[np.bool_] | None = None) -> ndarray[np.bool_]: ...


# ── Array manipulation ─────────────────────────────────────────────

def reshape(a: ndarray[_ScalarType], newshape: _ShapeLike, order: _OrderACF = "C") -> ndarray[_ScalarType]: ...
def ravel(a: ndarray[_ScalarType], order: _OrderKACF = "C") -> ndarray[_ScalarType]: ...
def flatten(a: ndarray[_ScalarType], order: _OrderKACF = "C") -> ndarray[_ScalarType]: ...
def transpose(a: ndarray[_ScalarType], axes: tuple[int, ...] | None = None) -> ndarray[_ScalarType]: ...
def swapaxes(a: ndarray[_ScalarType], axis1: int, axis2: int) -> ndarray[_ScalarType]: ...
def moveaxis(a: ndarray[_ScalarType], source: int | Sequence[int], destination: int | Sequence[int]) -> ndarray[_ScalarType]: ...
def squeeze(a: ndarray[_ScalarType], axis: int | tuple[int, ...] | None = None) -> ndarray[_ScalarType]: ...
def expand_dims(a: ndarray[_ScalarType], axis: int | tuple[int, ...]) -> ndarray[_ScalarType]: ...
def concatenate(arrays: Sequence[ndarray[_ScalarType]], axis: int = 0, out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def stack(arrays: Sequence[ndarray[_ScalarType]], axis: int = 0, out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def vstack(tup: Sequence[ndarray[_ScalarType]]) -> ndarray[_ScalarType]: ...
def hstack(tup: Sequence[ndarray[_ScalarType]]) -> ndarray[_ScalarType]: ...
def dstack(tup: Sequence[ndarray[_ScalarType]]) -> ndarray[_ScalarType]: ...
def column_stack(tup: Sequence[ndarray[_ScalarType]]) -> ndarray[_ScalarType]: ...
def row_stack(tup: Sequence[ndarray[_ScalarType]]) -> ndarray[_ScalarType]: ...
def split(ary: ndarray[_ScalarType], indices_or_sections: int | Sequence[int], axis: int = 0) -> list[ndarray[_ScalarType]]: ...
def vsplit(ary: ndarray[_ScalarType], indices_or_sections: int | Sequence[int]) -> list[ndarray[_ScalarType]]: ...
def hsplit(ary: ndarray[_ScalarType], indices_or_sections: int | Sequence[int]) -> list[ndarray[_ScalarType]]: ...
def dsplit(ary: ndarray[_ScalarType], indices_or_sections: int | Sequence[int]) -> list[ndarray[_ScalarType]]: ...
def tile(A: ndarray[_ScalarType], reps: int | Sequence[int]) -> ndarray[_ScalarType]: ...
def repeat(a: ndarray[_ScalarType], repeats: int | Sequence[int], axis: int | None = None) -> ndarray[_ScalarType]: ...
def flip(m: ndarray[_ScalarType], axis: int | tuple[int, ...] | None = None) -> ndarray[_ScalarType]: ...
def fliplr(m: ndarray[_ScalarType]) -> ndarray[_ScalarType]: ...
def flipud(m: ndarray[_ScalarType]) -> ndarray[_ScalarType]: ...
def rot90(m: ndarray[_ScalarType], k: int = 1, axes: tuple[int, int] = (0, 1)) -> ndarray[_ScalarType]: ...
def roll(a: ndarray[_ScalarType], shift: int | tuple[int, ...], axis: int | tuple[int, ...] | None = None) -> ndarray[_ScalarType]: ...


# ── Indexing functions ─────────────────────────────────────────────

@overload
def where(condition: ndarray[np.bool_] | npt.NDArray[np.bool_]) -> tuple[ndarray[np.intp], ...]: ...
@overload
def where(condition: ndarray[np.bool_] | npt.NDArray[np.bool_], x: ndarray[_ScalarType], y: ndarray[_ScalarType]) -> ndarray[_ScalarType]: ...
@overload
def where(condition: ndarray[np.bool_] | npt.NDArray[np.bool_], x: _Numeric, y: _Numeric) -> ndarray[np.generic]: ...

def nonzero(a: ndarray[np.generic]) -> tuple[ndarray[np.intp], ...]: ...
def argwhere(a: ndarray[np.generic]) -> ndarray[np.intp]: ...
def flatnonzero(a: ndarray[np.generic]) -> ndarray[np.intp]: ...
def take(a: ndarray[_ScalarType], indices: _ArrayLikeInt, axis: int | None = None, out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def take_along_axis(arr: ndarray[_ScalarType], indices: ndarray[np.intp], axis: int | None) -> ndarray[_ScalarType]: ...
def put(a: ndarray[_ScalarType], ind: _ArrayLikeInt, v: _ArrayLike, mode: _ModeKind = "raise") -> None: ...
def put_along_axis(arr: ndarray[_ScalarType], indices: ndarray[np.intp], values: _ArrayLike, axis: int) -> None: ...
def choose(a: ndarray[np.intp], choices: Sequence[ndarray[_ScalarType]], out: ndarray[_ScalarType] | None = None, mode: _ModeKind = "raise") -> ndarray[_ScalarType]: ...
def select(condlist: Sequence[ndarray[np.bool_]], choicelist: Sequence[ndarray[_ScalarType]], default: _Numeric = 0) -> ndarray[_ScalarType]: ...
def compress(condition: ndarray[np.bool_], a: ndarray[_ScalarType], axis: int | None = None, out: ndarray[_ScalarType] | None = None) -> ndarray[_ScalarType]: ...
def diag(v: ndarray[_ScalarType], k: int = 0) -> ndarray[_ScalarType]: ...
def diagonal(a: ndarray[_ScalarType], offset: int = 0, axis1: int = 0, axis2: int = 1) -> ndarray[_ScalarType]: ...
def triu(m: ndarray[_ScalarType], k: int = 0) -> ndarray[_ScalarType]: ...
def tril(m: ndarray[_ScalarType], k: int = 0) -> ndarray[_ScalarType]: ...

@overload
def indices(dimensions: tuple[int, ...], dtype: _DTypeLike[_IntType] = ..., sparse: Literal[False] = False) -> ndarray[_IntType]: ...
@overload
def indices(dimensions: tuple[int, ...], dtype: _DTypeLike[_IntType] = ..., sparse: Literal[True] = ...) -> tuple[ndarray[_IntType], ...]: ...


# ── Sorting functions ──────────────────────────────────────────────

def sort(
    a: ndarray[_ScalarType],
    axis: int = -1,
    kind: _SortKind | None = None,
    order: str | Sequence[str] | None = None,
) -> ndarray[_ScalarType]: ...

def argsort(
    a: ndarray[np.generic],
    axis: int = -1,
    kind: _SortKind | None = None,
    order: str | Sequence[str] | None = None,
) -> ndarray[np.intp]: ...

def lexsort(keys: Sequence[ndarray[np.generic]], axis: int = -1) -> ndarray[np.intp]: ...

def partition(
    a: ndarray[_ScalarType],
    kth: int | Sequence[int],
    axis: int = -1,
    kind: str = "introselect",
    order: str | Sequence[str] | None = None,
) -> ndarray[_ScalarType]: ...

def argpartition(
    a: ndarray[np.generic],
    kth: int | Sequence[int],
    axis: int = -1,
    kind: str = "introselect",
    order: str | Sequence[str] | None = None,
) -> ndarray[np.intp]: ...

def searchsorted(
    a: ndarray[_ScalarType],
    v: _ArrayLike,
    side: Literal["left", "right"] = "left",
    sorter: _ArrayLikeInt | None = None,
) -> ndarray[np.intp]: ...

@overload
def unique(ar: ndarray[_ScalarType], return_index: Literal[False] = False, return_inverse: Literal[False] = False, return_counts: Literal[False] = False, axis: int | None = None) -> ndarray[_ScalarType]: ...
@overload
def unique(ar: ndarray[_ScalarType], return_index: Literal[True], return_inverse: Literal[False] = False, return_counts: Literal[False] = False, axis: int | None = None) -> tuple[ndarray[_ScalarType], ndarray[np.intp]]: ...
@overload
def unique(ar: ndarray[_ScalarType], return_index: Literal[False], return_inverse: Literal[True], return_counts: Literal[False] = False, axis: int | None = None) -> tuple[ndarray[_ScalarType], ndarray[np.intp]]: ...
@overload
def unique(ar: ndarray[_ScalarType], return_index: Literal[False], return_inverse: Literal[False], return_counts: Literal[True], axis: int | None = None) -> tuple[ndarray[_ScalarType], ndarray[np.intp]]: ...
@overload
def unique(ar: ndarray[_ScalarType], return_index: bool, return_inverse: bool, return_counts: bool, axis: int | None = None) -> tuple[ndarray[_ScalarType], ...]: ...


# ── Linear algebra ─────────────────────────────────────────────────

def dot(a: _ArrayLike, b: _ArrayLike, out: ndarray[np.generic] | None = None) -> ndarray[np.generic]: ...
def vdot(a: _ArrayLike, b: _ArrayLike) -> np.generic: ...
def inner(a: _ArrayLike, b: _ArrayLike) -> ndarray[np.generic]: ...
def outer(a: _ArrayLike, b: _ArrayLike, out: ndarray[np.generic] | None = None) -> ndarray[np.generic]: ...
def matmul(x1: _ArrayLike, x2: _ArrayLike, out: ndarray[np.generic] | None = None) -> ndarray[np.generic]: ...
def tensordot(a: _ArrayLike, b: _ArrayLike, axes: int | tuple[Sequence[int], Sequence[int]] = 2) -> ndarray[np.generic]: ...
def einsum(subscripts: str, *operands: _ArrayLike, out: ndarray[np.generic] | None = None, optimize: bool | str = False) -> ndarray[np.generic]: ...
def trace(a: ndarray[_ScalarType], offset: int = 0, axis1: int = 0, axis2: int = 1, dtype: _DTypeLike[_ScalarType2] | None = None, out: ndarray[_ScalarType2] | None = None) -> ndarray[_ScalarType] | _ScalarType: ...


# ── Memory management ──────────────────────────────────────────────

class MemoryPool:
    """GPU memory pool for allocation reuse."""

    def malloc(self, size: int) -> MemoryPointer: ...
    def free(self, ptr: MemoryPointer, size: int) -> None: ...
    def free_all_blocks(self) -> None: ...
    def free_all_free(self) -> None: ...
    def n_free_blocks(self) -> int: ...
    def used_bytes(self) -> int: ...
    def free_bytes(self) -> int: ...
    def total_bytes(self) -> int: ...


class PinnedMemoryPool:
    """Host pinned memory pool."""

    def malloc(self, size: int) -> memoryview: ...
    def free(self, ptr: memoryview, size: int) -> None: ...
    def free_all_blocks(self) -> None: ...
    def n_free_blocks(self) -> int: ...


def get_default_memory_pool() -> MemoryPool: ...
def get_default_pinned_memory_pool() -> PinnedMemoryPool: ...


# ── Miscellaneous ──────────────────────────────────────────────────

class _ArrayModule(Protocol):
    """Protocol for array module (cupy or numpy)."""
    ndarray: type[ndarray[np.generic] | npt.NDArray[np.generic]]

def get_array_module(*args: ndarray[np.generic] | npt.NDArray[np.generic]) -> _ArrayModule: ...

def is_available() -> bool: ...

__version__: str
