"""Tests for pysymex.tracing.analyzer — _touches_var and _any_constraint."""

from __future__ import annotations

import argparse

from pysymex.tracing.analyzer import build_pipeline


class TestTouchesVar:
    """Test the _touches_var inner filter function."""

    def test_touches_var_in_stack(self) -> None:
        """_touches_var finds needle in stack list."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var="my_var",
            constraint_contains=None,
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {"stack": ["my_var_value", "other"]}
        assert pipeline.matches(event)

    def test_touches_var_in_local_vars(self) -> None:
        """_touches_var finds needle in local_vars mapping."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var="target",
            constraint_contains=None,
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {"local_vars": {"target": "42"}}
        assert pipeline.matches(event)

    def test_touches_var_not_found(self) -> None:
        """_touches_var returns False when needle is absent."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var="absent_var",
            constraint_contains=None,
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {"stack": ["x", "y"], "local_vars": {"a": "1"}}
        assert not pipeline.matches(event)


class TestAnyConstraint:
    """Test the _any_constraint inner filter function."""

    def test_any_constraint_in_constraint_added(self) -> None:
        """_any_constraint finds needle in constraint_added.smtlib."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var=None,
            constraint_contains="bvadd",
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {"constraint_added": {"smtlib": "(bvadd x y)", "causality": ""}}
        assert pipeline.matches(event)

    def test_any_constraint_in_path_constraints(self) -> None:
        """_any_constraint finds needle in path_constraints[*].smtlib."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var=None,
            constraint_contains="needle_expr",
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {
            "path_constraints": [
                {"smtlib": "(= x needle_expr)", "causality": ""},
            ]
        }
        assert pipeline.matches(event)

    def test_any_constraint_not_found(self) -> None:
        """_any_constraint returns False when needle is absent everywhere."""
        args = argparse.Namespace(
            event_type=None,
            seq=None,
            seq_range=None,
            path_id=None,
            path_id_list=None,
            pc=None,
            pc_range=None,
            opcode=None,
            source_line=None,
            has_stack_push=False,
            has_stack_pop=False,
            has_var_modified=False,
            var_modified_name=None,
            has_var_added=False,
            var_added_name=None,
            has_var_removed=False,
            var_removed_name=None,
            has_mem_write=False,
            has_constraint_added=False,
            constraint_causality_contains=None,
            trigger=None,
            depth=None,
            depth_min=None,
            depth_max=None,
            parent_path_id=None,
            has_child_fork=False,
            prune_reason=None,
            stack_contains=None,
            local_var_name=None,
            global_var_name=None,
            constraint_smtlib_contains=None,
            num_path_constraints_min=None,
            num_path_constraints_max=None,
            solve_result=None,
            cache_hit=False,
            cache_miss=False,
            solver_latency_min=None,
            solver_latency_max=None,
            num_constraints_min=None,
            num_constraints_max=None,
            has_model_excerpt=False,
            model_var_name=None,
            severity=None,
            detector=None,
            issue_kind=None,
            message_contains=None,
            has_z3_model=False,
            z3_model_var=None,
            issue_source_line=None,
            confidence=None,
            constraint_at_issue_contains=None,
            function_name=None,
            source_file=None,
            pysymex_version=None,
            z3_version=None,
            touches_var=None,
            constraint_contains="ABSENT",
            any_field_contains=None,
        )
        pipeline = build_pipeline(args)
        event = {"constraint_added": {"smtlib": "(= x 1)", "causality": ""}}
        assert not pipeline.matches(event)
