# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Usage guidelines and architecture notes for the trace analyzer manual.

Exposes the usage section of the manual detailing strategies for feeding trace
output to an LLM, state reconstruction, path trees, and tracer options.
"""

from __future__ import annotations

"""LLM usage and architecture notes for the trace analyzer manual."""

AI_MANUAL_USAGE = """
## 4. Feeding Output to an LLM

Gigabyte trace files cannot be fed directly to any LLM. Use these strategies:

### Strategy A: Summary Preamble
```bash
# Get counts by event type first — tiny, always fits in context
pysymex-trace-analyze trace.jsonl --format summary
```

Include the summary table in your LLM prompt as context before asking
diagnostic questions. The summary includes event counts, solver/step latency
aggregates, solver outcomes/cache hit rate, detector-query outcomes, path
feasibility outcomes, fallback labels, uncertain detector sites, slowest paths,
and the slowest step opcodes by total dispatch time when those fields are present.

### Strategy B: Head + Tail Sampling
```bash
# First 50 events (analysis startup context)
pysymex-trace-analyze trace.jsonl --head 50 --format pretty

# Last 50 events (analysis ending context — often where bugs appear)
pysymex-trace-analyze trace.jsonl --tail 50 --format pretty
```

### Strategy C: Targeted Filter Chains
Compose 2-4 filters to isolate precisely the events relevant to your question:
```bash
# "Which SAT results mentioned variable 'idx' on slow queries?"
pysymex-trace-analyze trace.jsonl \
    --event-type solve \
    --solve-result sat \
    --solver-latency-min 200 \
    --any-field-contains idx \
    --format pretty | head -30
```

### Strategy D: Count First, Then Retrieve
Always count before rendering pretty-printing:
```bash
pysymex-trace-analyze trace.jsonl --event-type issue --count
# → 847
# Now retrieve only first 10 for inspection:
pysymex-trace-analyze trace.jsonl --event-type issue --head 10 --format pretty
```

### Strategy E: Issue-Specific Context
- **Isolate a bug**: `pysymex-trace-analyze trace.jsonl --event-type issue --fields seq,path_id,message,source_text,confidence`
- **Reconstruct logic around a bug**: Find sequence N for an `issue`. Then run `pysymex-trace-analyze trace.jsonl --seq-range (N-20):N --format pretty` to see the instructions that led to it.

---

## 5. Architecture Notes for LLM Reasoning

**seq monotonicity:** `seq` is a global, monotonically increasing integer
incremented under a lock. You can sort any mixed-type subset of events by
`seq` to recover chronological order.

**Keyframe + Delta composition:**
To reconstruct full symbolic state at any `step` event:
1. Find the most recent `keyframe` event with `seq < target_step.seq` and the
   same `path_id`.
2. Replay all `step` events from `keyframe.seq + 1` to `target_step.seq` where
   `path_id` matches, applying each `stack_diff`, `var_diff`, and `mem_diff`.

**Path tree reconstruction:**
Each `keyframe` with `trigger=fork` contains `parent_path_id` and
`child_path_ids`. Collecting all fork keyframes reconstructs the complete
execution tree topology.

**Thread safety note:**
The tracer uses a single `threading.Lock` for all writes. The JSONL file is
always consistent — a line is either fully written or not present. You will
never see a partial line.

**QUIET verbosity:**
When `TracerConfig.verbosity=QUIET`, `step` events are suppressed entirely.
Diagnostic events such as `keyframe`, `solve`, `detector_query`,
`path_feasibility`, `scheduler`, `fallback`, and `issue` are still emitted. Use
repeated `--event-type` flags to focus on those event families when analyzing a
QUIET-mode trace.

**Zero-overhead guarantee:**
When `TracerConfig.enabled=False` (the default), the tracer performs zero
work. No Z3 serialization, no Pydantic validation, no file I/O. Every hook
method short-circuits immediately on the `enabled` check. Set
`PY_SYMEX_TRACE=1` in the environment (or pass `TracerConfig(enabled=True)`)
to activate tracing.

---

*End of AI Manual. Generated by `pysymex-trace-analyze --ai-manual`.*
""".strip()

__all__ = ["AI_MANUAL_USAGE"]
