"""Type stubs for numba.cuda.cudadrv.driver module."""

from __future__ import annotations

from types import TracebackType

class Stream:
    """CUDA stream for asynchronous operations."""

    @property
    def handle(self) -> int: ...

    def synchronize(self) -> None: ...

    def auto_synchronize(self) -> _AutoSync: ...

    def add_callback(self, callback: object, data: object = None) -> None: ...

    def __enter__(self) -> Stream: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...


class _AutoSync:
    """Context manager for auto synchronization."""
    def __enter__(self) -> _AutoSync: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...


class Event:
    """CUDA event for timing and synchronization."""

    @property
    def handle(self) -> int: ...

    def record(self, stream: Stream | None = None) -> None: ...
    def wait(self, stream: Stream | None = None) -> None: ...
    def synchronize(self) -> None: ...
    def elapsed_time(self, end: Event) -> float: ...
    def query(self) -> bool: ...


class Device:
    """CUDA device object."""

    id: int
    name: str
    compute_capability: tuple[int, int]

    @property
    def TOTAL_MEMORY(self) -> int: ...
    @property
    def FREE_MEMORY(self) -> int: ...
    @property
    def MAX_THREADS_PER_BLOCK(self) -> int: ...
    @property
    def MAX_BLOCK_DIM_X(self) -> int: ...
    @property
    def MAX_BLOCK_DIM_Y(self) -> int: ...
    @property
    def MAX_BLOCK_DIM_Z(self) -> int: ...
    @property
    def MAX_GRID_DIM_X(self) -> int: ...
    @property
    def MAX_GRID_DIM_Y(self) -> int: ...
    @property
    def MAX_GRID_DIM_Z(self) -> int: ...
    @property
    def MAX_SHARED_MEMORY_PER_BLOCK(self) -> int: ...
    @property
    def ASYNC_ENGINE_COUNT(self) -> int: ...
    @property
    def CAN_MAP_HOST_MEMORY(self) -> bool: ...
    @property
    def MULTIPROCESSOR_COUNT(self) -> int: ...
    @property
    def WARP_SIZE(self) -> int: ...
    @property
    def UNIFIED_ADDRESSING(self) -> bool: ...
    @property
    def PCI_BUS_ID(self) -> int: ...
    @property
    def PCI_DEVICE_ID(self) -> int: ...

    def __enter__(self) -> Device: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

    def reset(self) -> None: ...
    def get_primary_context(self) -> Context: ...


class Context:
    """CUDA context."""

    @property
    def device(self) -> Device: ...

    def __enter__(self) -> Context: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

    def synchronize(self) -> None: ...
    def push(self) -> None: ...
    def pop(self) -> Context: ...
    def reset(self) -> None: ...


class MemoryPointer:
    """GPU memory pointer."""

    @property
    def owner(self) -> object: ...
    @property
    def device_pointer(self) -> int: ...
    @property
    def device_ctypes_pointer(self) -> int: ...

    def view(self, start: int, stop: int | None = None) -> MemoryPointer: ...
    def memset(self, value: int, count: int, stream: Stream | None = None) -> None: ...


def get_context(devnum: int = 0) -> Context: ...
def get_device(devnum: int = 0) -> Device: ...
def get_current_device() -> Device: ...
def list_devices() -> list[Device]: ...
def create_stream() -> Stream: ...
def create_event(timing: bool = True) -> Event: ...
def mem_alloc(size: int) -> MemoryPointer: ...
def device_memory_size() -> tuple[int, int]: ...
