"""Local typing boundary for the ``immutables`` package used by COW state."""

from __future__ import annotations

from collections.abc import ItemsView, Iterable, Iterator, KeysView, Mapping, ValuesView
from types import TracebackType
from typing import Generic, Self, TypeVar, overload

K = TypeVar("K")
V = TypeVar("V")
T = TypeVar("T")

class Map(Mapping[K, V], Generic[K, V]):
    def __init__(self, col: Mapping[K, V] | Iterable[tuple[K, V]] | None = None) -> None: ...
    def __getitem__(self, key: K, /) -> V: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object, /) -> bool: ...
    @overload
    def get(self, key: K, /) -> V | None: ...
    @overload
    def get(self, key: K, default: T, /) -> V | T: ...
    def get(self, key: K, default: T | None = None, /) -> V | T | None: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def items(self) -> ItemsView[K, V]: ...
    def set(self, key: K, val: V, /) -> Map[K, V]: ...
    def delete(self, key: K, /) -> Map[K, V]: ...
    def mutate(self) -> MapMutation[K, V]: ...

class MapMutation(Generic[K, V]):
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...
    def set(self, key: K, val: V, /) -> None: ...
    def delete(self, key: K, /) -> None: ...
    def finish(self) -> Map[K, V]: ...
