"""Type stubs for z3-solver – precise typing for pysymex.

This stub eliminates Any types through careful use of TypeVars, overloads,
and union types. The goal is pyright strict mode with zero errors.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from fractions import Fraction
from typing import TypeGuard, TypeVar, overload

# ══════════════════════════════════════════════════════════════════════
# Type Variables
# ══════════════════════════════════════════════════════════════════════

_E = TypeVar("_E", bound="ExprRef")
_Sort = TypeVar("_Sort", bound="SortRef")

# ══════════════════════════════════════════════════════════════════════
# Context
# ══════════════════════════════════════════════════════════════════════


class Context:
    def __init__(self, *args: int | str, **kwargs: int | str | bool) -> None: ...


def main_ctx() -> Context: ...
def set_param(*args: str | int, **kwargs: str | int | bool) -> None: ...
def get_param(name: str) -> str: ...
def reset_params() -> None: ...


# ══════════════════════════════════════════════════════════════════════
# Exceptions
# ══════════════════════════════════════════════════════════════════════


class Z3Exception(Exception): ...


# ══════════════════════════════════════════════════════════════════════
# Sort Hierarchy
# ══════════════════════════════════════════════════════════════════════


class SortRef:
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def kind(self) -> int: ...
    def get_id(self) -> int: ...
    def ctx(self) -> Context: ...
    def ctx_ref(self) -> int: ...


class BoolSortRef(SortRef): ...


class ArithSortRef(SortRef):
    def is_int(self) -> bool: ...
    def is_real(self) -> bool: ...


class BitVecSortRef(SortRef):
    def size(self) -> int: ...


class FPSortRef(SortRef):
    def ebits(self) -> int: ...
    def sbits(self) -> int: ...


class SeqSortRef(SortRef):
    def basis(self) -> SortRef: ...


class ReSortRef(SortRef): ...
class ArraySortRef(SortRef): ...
class DatatypeSortRef(SortRef): ...
class FiniteDomainSortRef(SortRef): ...
class CharSortRef(SortRef): ...
class TypeVarRef(SortRef): ...


# ══════════════════════════════════════════════════════════════════════
# AST Base
# ══════════════════════════════════════════════════════════════════════


class AstRef:
    def sexpr(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def hash(self) -> int: ...
    def ctx_ref(self) -> int: ...
    def get_id(self) -> int: ...
    def ctx(self) -> Context: ...


class AstVector:
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, i: int) -> AstRef: ...
    @overload
    def __getitem__(self, i: slice) -> list[AstRef]: ...
    def __iter__(self) -> Iterator[AstRef]: ...
    def __contains__(self, item: AstRef) -> bool: ...
    def push(self, v: AstRef) -> None: ...
    def resize(self, n: int) -> None: ...
    def __setitem__(self, i: int, v: AstRef) -> None: ...
    def translate(self, ctx: Context) -> AstVector: ...


# ══════════════════════════════════════════════════════════════════════
# Expression Hierarchy
# ══════════════════════════════════════════════════════════════════════


class ExprRef(AstRef):
    def sort(self) -> SortRef: ...
    def sort_kind(self) -> int: ...
    def decl(self) -> FuncDeclRef: ...
    def children(self) -> list[ExprRef]: ...
    def num_args(self) -> int: ...
    def arg(self, i: int) -> ExprRef: ...
    def __eq__(self, other: ExprRef | int | bool | float | str) -> BoolRef: ...  # type: ignore[override]
    def __ne__(self, other: ExprRef | int | bool | float | str) -> BoolRef: ...  # type: ignore[override]
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    # Arithmetic operators – valid when sort is Int/Real at runtime
    def __add__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __radd__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __sub__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __rsub__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __mul__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __rmul__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __truediv__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __rtruediv__(self, other: ExprRef | int | float) -> ExprRef: ...
    def __mod__(self, other: ExprRef | int) -> ExprRef: ...
    def __rmod__(self, other: ExprRef | int) -> ExprRef: ...
    def __pow__(self, other: ExprRef | int) -> ExprRef: ...
    def __neg__(self) -> ExprRef: ...
    # Comparison operators
    def __le__(self, other: ExprRef | int | float | str) -> BoolRef: ...
    def __lt__(self, other: ExprRef | int | float | str) -> BoolRef: ...
    def __ge__(self, other: ExprRef | int | float | str) -> BoolRef: ...
    def __gt__(self, other: ExprRef | int | float | str) -> BoolRef: ...
    # Value extraction
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_fraction(self) -> Fraction: ...
    def as_signed_long(self) -> int: ...
    # Sequence operators
    def __getitem__(self, idx: ExprRef | int | slice) -> ExprRef: ...
    def __contains__(self, other: ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def at(self, i: ExprRef | int) -> ExprRef: ...


class BoolRef(ExprRef):
    def __and__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __or__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __rand__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __ror__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __xor__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __rxor__(self, other: BoolRef | ExprRef | bool) -> BoolRef: ...
    def __invert__(self) -> BoolRef: ...


class ArithRef(ExprRef):
    def __add__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __radd__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __sub__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __rsub__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __mul__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __rmul__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __truediv__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __rtruediv__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...  # type: ignore[override]
    def __mod__(self, other: ArithRef | ExprRef | int) -> ArithRef: ...  # type: ignore[override]
    def __rmod__(self, other: ArithRef | ExprRef | int) -> ArithRef: ...  # type: ignore[override]
    def __pow__(self, other: ArithRef | ExprRef | int) -> ArithRef: ...  # type: ignore[override]
    def __neg__(self) -> ArithRef: ...  # type: ignore[override]
    def __le__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...  # type: ignore[override]
    def __lt__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...  # type: ignore[override]
    def __ge__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...  # type: ignore[override]
    def __gt__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...  # type: ignore[override]
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_fraction(self) -> Fraction: ...
    def is_int(self) -> bool: ...
    def is_real(self) -> bool: ...
    def numerator_as_long(self) -> int: ...
    def denominator_as_long(self) -> int: ...


class IntNumRef(ArithRef):
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...


class RatNumRef(ArithRef):
    def as_long(self) -> int: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_string(self) -> str: ...
    def as_fraction(self) -> Fraction: ...
    def numerator(self) -> IntNumRef: ...
    def denominator(self) -> IntNumRef: ...
    def numerator_as_long(self) -> int: ...
    def denominator_as_long(self) -> int: ...


class AlgebraicNumRef(ArithRef): ...
class IntRef(ArithRef): ...
class RealRef(ArithRef): ...


class SeqRef(ExprRef):
    def __add__(self, other: SeqRef | ExprRef | str) -> SeqRef: ...  # type: ignore[override]
    def __radd__(self, other: SeqRef | ExprRef | str) -> SeqRef: ...  # type: ignore[override]
    @overload
    def __getitem__(self, idx: int) -> SeqRef: ...  # type: ignore[override]
    @overload
    def __getitem__(self, idx: ArithRef | ExprRef) -> SeqRef: ...  # type: ignore[override]
    @overload
    def __getitem__(self, idx: slice) -> SeqRef: ...  # type: ignore[override]
    def __contains__(self, other: SeqRef | ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def __le__(self, other: SeqRef | ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def __lt__(self, other: SeqRef | ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def __ge__(self, other: SeqRef | ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def __gt__(self, other: SeqRef | ExprRef | str) -> BoolRef: ...  # type: ignore[override]
    def as_string(self) -> str: ...
    def at(self, i: ArithRef | ExprRef | int) -> SeqRef: ...


class CharRef(ExprRef): ...


class ReRef(ExprRef):
    def __add__(self, other: ReRef) -> ReRef: ...  # type: ignore[override]


class BitVecRef(ExprRef):
    def size(self) -> int: ...
    def __add__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __radd__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __sub__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __rsub__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __mul__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __rmul__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...  # type: ignore[override]
    def __and__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __rand__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __or__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __ror__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __xor__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __rxor__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __invert__(self) -> BitVecRef: ...
    def __lshift__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __rlshift__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __rshift__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __rrshift__(self, other: BitVecRef | ExprRef | int) -> BitVecRef: ...
    def __neg__(self) -> BitVecRef: ...  # type: ignore[override]
    def __le__(self, other: BitVecRef | ExprRef | int) -> BoolRef: ...  # type: ignore[override]
    def __lt__(self, other: BitVecRef | ExprRef | int) -> BoolRef: ...  # type: ignore[override]
    def __ge__(self, other: BitVecRef | ExprRef | int) -> BoolRef: ...  # type: ignore[override]
    def __gt__(self, other: BitVecRef | ExprRef | int) -> BoolRef: ...  # type: ignore[override]
    def as_long(self) -> int: ...
    def as_signed_long(self) -> int: ...


class BitVecNumRef(BitVecRef):
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_signed_long(self) -> int: ...


class ArrayRef(ExprRef):
    def __getitem__(self, idx: ExprRef | int | bool) -> ExprRef: ...  # type: ignore[override]
    def sort(self) -> ArraySortRef: ...
    def domain(self) -> SortRef: ...
    def domain_n(self, i: int) -> SortRef: ...
    def range(self) -> SortRef: ...
    def default(self) -> ExprRef: ...


class FPRef(ExprRef):
    def sort(self) -> FPSortRef: ...
    def ebits(self) -> int: ...
    def sbits(self) -> int: ...
    def __add__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __radd__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __sub__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __rsub__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __mul__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __rmul__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __truediv__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __rtruediv__(self, other: FPRef | ExprRef | float | int) -> FPRef: ...  # type: ignore[override]
    def __neg__(self) -> FPRef: ...  # type: ignore[override]
    def __le__(self, other: FPRef | ExprRef | float | int) -> BoolRef: ...  # type: ignore[override]
    def __lt__(self, other: FPRef | ExprRef | float | int) -> BoolRef: ...  # type: ignore[override]
    def __ge__(self, other: FPRef | ExprRef | float | int) -> BoolRef: ...  # type: ignore[override]
    def __gt__(self, other: FPRef | ExprRef | float | int) -> BoolRef: ...  # type: ignore[override]


class FPNumRef(FPRef):
    def as_string(self) -> str: ...
    def isNaN(self) -> bool: ...
    def isInf(self) -> bool: ...
    def isZero(self) -> bool: ...
    def isNegative(self) -> bool: ...
    def isPositive(self) -> bool: ...


class FPRMRef(ExprRef): ...
class DatatypeRef(ExprRef): ...
class FiniteDomainRef(ExprRef): ...
class FiniteDomainNumRef(FiniteDomainRef): ...
class PatternRef(AstRef): ...


class QuantifierRef(BoolRef):
    def is_forall(self) -> bool: ...
    def is_exists(self) -> bool: ...
    def is_lambda(self) -> bool: ...
    def num_vars(self) -> int: ...
    def var_name(self, i: int) -> str: ...
    def var_sort(self, i: int) -> SortRef: ...
    def body(self) -> ExprRef: ...
    def weight(self) -> int: ...
    def num_patterns(self) -> int: ...
    def pattern(self, i: int) -> PatternRef: ...


# ══════════════════════════════════════════════════════════════════════
# FuncDeclRef
# ══════════════════════════════════════════════════════════════════════


class FuncDeclRef(AstRef):
    def name(self) -> str: ...
    def arity(self) -> int: ...
    def kind(self) -> int: ...
    def domain(self, i: int) -> SortRef: ...
    def range(self) -> SortRef: ...
    def __call__(self, *args: ExprRef | int | bool | float | str) -> ExprRef: ...


# ══════════════════════════════════════════════════════════════════════
# ModelRef
# ══════════════════════════════════════════════════════════════════════


class FuncInterp:
    def else_value(self) -> ExprRef: ...
    def num_entries(self) -> int: ...
    def entry(self, i: int) -> FuncEntry: ...
    def arity(self) -> int: ...
    def __len__(self) -> int: ...


class FuncEntry:
    def num_args(self) -> int: ...
    def arg_value(self, i: int) -> ExprRef: ...
    def value(self) -> ExprRef: ...


class ModelRef:
    def decls(self) -> list[FuncDeclRef]: ...
    def eval(self, expr: ExprRef, model_completion: bool = False) -> ExprRef: ...
    def evaluate(self, expr: ExprRef, model_completion: bool = False) -> ExprRef: ...
    @overload
    def __getitem__(self, key: FuncDeclRef) -> ExprRef | FuncInterp | None: ...
    @overload
    def __getitem__(self, key: ExprRef) -> ExprRef | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[FuncDeclRef]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __contains__(self, key: ExprRef | FuncDeclRef) -> bool: ...
    def get_interp(self, decl: FuncDeclRef) -> ExprRef | FuncInterp | None: ...
    def num_sorts(self) -> int: ...
    def get_sort(self, i: int) -> SortRef: ...
    def get_universe(self, s: SortRef) -> AstVector: ...


# ══════════════════════════════════════════════════════════════════════
# CheckSatResult
# ══════════════════════════════════════════════════════════════════════


class CheckSatResult:
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...


sat: CheckSatResult
unsat: CheckSatResult
unknown: CheckSatResult


# ══════════════════════════════════════════════════════════════════════
# Statistics
# ══════════════════════════════════════════════════════════════════════


class Statistics:
    def __len__(self) -> int: ...
    def __getitem__(self, key: str | int) -> float | int: ...
    def keys(self) -> list[str]: ...
    def get_key_value(self, key: str) -> float | int: ...
    def __repr__(self) -> str: ...


# ══════════════════════════════════════════════════════════════════════
# Solver
# ══════════════════════════════════════════════════════════════════════

# Constraint input types: accept BoolRef, ExprRef, lists, or iterables of BoolRef/ExprRef
_BoolConstraint = BoolRef | ExprRef | Iterable[BoolRef | ExprRef]


class Solver:
    def __init__(
        self, solver: Solver | None = None, ctx: Context | None = None
    ) -> None: ...
    def add(self, *args: _BoolConstraint) -> None: ...
    def append(self, *args: _BoolConstraint) -> None: ...
    def insert(self, *args: _BoolConstraint) -> None: ...
    def assert_exprs(self, *args: _BoolConstraint) -> None: ...
    def check(self, *assumptions: BoolRef) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def push(self) -> None: ...
    def pop(self, n: int = 1) -> None: ...
    def reset(self) -> None: ...
    def set(self, *args: str | int | bool, **kwargs: str | int | bool) -> None: ...
    def assertions(self) -> AstVector: ...
    def units(self) -> AstVector: ...
    def unsat_core(self) -> AstVector: ...
    def from_string(self, s: str) -> None: ...
    def from_file(self, f: str) -> None: ...
    def to_smt2(self) -> str: ...
    def sexpr(self) -> str: ...
    def dimacs(self, include_names: bool = True) -> str: ...
    def statistics(self) -> Statistics: ...
    def reason_unknown(self) -> str: ...
    def num_scopes(self) -> int: ...
    def param_descrs(self) -> ParamDescrsRef: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def translate(self, ctx: Context) -> Solver: ...
    def __copy__(self) -> Solver: ...
    def __deepcopy__(self, memo: dict[int, object] | None = None) -> Solver: ...


class SimpleSolver(Solver): ...


class ParamDescrsRef:
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def get_name(self, i: int) -> str: ...
    def get_kind(self, name: str) -> int: ...
    def get_documentation(self, name: str) -> str: ...
    def __repr__(self) -> str: ...


# ══════════════════════════════════════════════════════════════════════
# Optimize
# ══════════════════════════════════════════════════════════════════════


class OptimizeObjective:
    def lower(self) -> ExprRef: ...
    def upper(self) -> ExprRef: ...
    def value(self) -> ExprRef: ...
    def lower_values(self) -> list[ExprRef]: ...
    def upper_values(self) -> list[ExprRef]: ...


class Optimize:
    def __init__(self, ctx: Context | None = None) -> None: ...
    def add(self, *args: _BoolConstraint) -> None: ...
    def add_soft(
        self, p: BoolRef, weight: str | int = ..., id: str | ExprRef = ...
    ) -> OptimizeObjective: ...
    def check(self, *assumptions: BoolRef) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def push(self) -> None: ...
    def pop(self, n: int = 1) -> None: ...
    def set(self, *args: str | int | bool, **kwargs: str | int | bool) -> None: ...
    def maximize(self, arg: ArithRef | ExprRef) -> OptimizeObjective: ...
    def minimize(self, arg: ArithRef | ExprRef) -> OptimizeObjective: ...
    def assertions(self) -> AstVector: ...
    def objectives(self) -> list[OptimizeObjective]: ...
    def statistics(self) -> Statistics: ...
    def from_string(self, s: str) -> None: ...
    def from_file(self, f: str) -> None: ...
    def reason_unknown(self) -> str: ...


# ══════════════════════════════════════════════════════════════════════
# Goal / Tactic
# ══════════════════════════════════════════════════════════════════════


class Goal:
    def __init__(
        self,
        models: bool = True,
        unsatCores: bool = False,
        proofs: bool = False,
        ctx: Context | None = None,
    ) -> None: ...
    def add(self, *args: _BoolConstraint) -> None: ...
    def insert(self, *args: _BoolConstraint) -> None: ...
    def append(self, *args: _BoolConstraint) -> None: ...
    def assert_exprs(self, *args: _BoolConstraint) -> None: ...
    def as_expr(self) -> BoolRef: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> BoolRef: ...
    def __iter__(self) -> Iterator[BoolRef]: ...
    def __repr__(self) -> str: ...
    def translate(self, ctx: Context) -> Goal: ...
    def simplify(self) -> Goal: ...
    def depth(self) -> int: ...
    def size(self) -> int: ...
    def prec(self) -> int: ...
    def inconsistent(self) -> bool: ...


class ApplyResult:
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Goal: ...
    def __iter__(self) -> Iterator[Goal]: ...
    def as_expr(self) -> BoolRef: ...
    def __repr__(self) -> str: ...


class Tactic:
    def __init__(self, name: str, ctx: Context | None = None) -> None: ...
    def __call__(
        self, goal: Goal, *args: str, **kwargs: str | int | bool
    ) -> ApplyResult: ...
    def solver(self, logFile: str | None = None) -> Solver: ...
    def apply(
        self, goal: Goal, *args: str, **kwargs: str | int | bool
    ) -> ApplyResult: ...
    def param_descrs(self) -> ParamDescrsRef: ...


class Probe:
    def __init__(self, name: str, ctx: Context | None = None) -> None: ...
    def __call__(self, goal: Goal) -> float: ...
    def __eq__(self, other: Probe | float | int) -> Probe: ...  # type: ignore[override]
    def __ne__(self, other: Probe | float | int) -> Probe: ...  # type: ignore[override]
    def __le__(self, other: Probe | float | int) -> Probe: ...
    def __lt__(self, other: Probe | float | int) -> Probe: ...
    def __ge__(self, other: Probe | float | int) -> Probe: ...
    def __gt__(self, other: Probe | float | int) -> Probe: ...


def Then(*tactics: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...
def OrElse(*tactics: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...
def With(tactic: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...
def Repeat(t: Tactic | str, max: int = ...) -> Tactic: ...
def TryFor(t: Tactic | str, ms: int) -> Tactic: ...
def ParOr(*tactics: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...
def ParThen(t1: Tactic | str, t2: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...
def AndThen(*tactics: Tactic | str, **kwargs: str | int | bool) -> Tactic: ...


# ══════════════════════════════════════════════════════════════════════
# Sort Constructors
# ══════════════════════════════════════════════════════════════════════


def IntSort(ctx: Context | None = None) -> ArithSortRef: ...
def BoolSort(ctx: Context | None = None) -> BoolSortRef: ...
def RealSort(ctx: Context | None = None) -> ArithSortRef: ...
def StringSort(ctx: Context | None = None) -> SeqSortRef: ...
def BitVecSort(sz: int, ctx: Context | None = None) -> BitVecSortRef: ...
def SeqSort(s: SortRef) -> SeqSortRef: ...
def ReSort(s: SortRef) -> ReSortRef: ...
def SetSort(s: SortRef) -> ArraySortRef: ...
def ArraySort(*sig: SortRef) -> ArraySortRef: ...
def FPSort(ebits: int, sbits: int, ctx: Context | None = None) -> FPSortRef: ...
def Float16(ctx: Context | None = None) -> FPSortRef: ...
def Float32(ctx: Context | None = None) -> FPSortRef: ...
def Float64(ctx: Context | None = None) -> FPSortRef: ...
def Float128(ctx: Context | None = None) -> FPSortRef: ...
def DeclareSort(name: str | int, ctx: Context | None = None) -> SortRef: ...
def CharSort(ctx: Context | None = None) -> CharSortRef: ...


# ══════════════════════════════════════════════════════════════════════
# Variable / Value Constructors
# ══════════════════════════════════════════════════════════════════════


def Int(name: str, ctx: Context | None = None) -> ArithRef: ...
def Ints(names: str, ctx: Context | None = None) -> list[ArithRef]: ...
def IntVal(val: int, ctx: Context | None = None) -> IntNumRef: ...
def Bool(name: str, ctx: Context | None = None) -> BoolRef: ...
def BoolVal(val: bool, ctx: Context | None = None) -> BoolRef: ...
def Bools(names: str, ctx: Context | None = None) -> list[BoolRef]: ...
def Real(name: str, ctx: Context | None = None) -> ArithRef: ...
def RealVal(val: int | float | str, ctx: Context | None = None) -> RatNumRef: ...
def Reals(names: str, ctx: Context | None = None) -> list[ArithRef]: ...
def String(name: str, ctx: Context | None = None) -> SeqRef: ...
def StringVal(val: str, ctx: Context | None = None) -> SeqRef: ...
def Strings(names: str, ctx: Context | None = None) -> list[SeqRef]: ...
def Const(name: str, sort: SortRef) -> ExprRef: ...
def Consts(names: str, sort: SortRef) -> list[ExprRef]: ...
def FreshConst(sort: SortRef, prefix: str = "c") -> ExprRef: ...
def FreshInt(prefix: str = "x", ctx: Context | None = None) -> ArithRef: ...
def FreshBool(prefix: str = "b", ctx: Context | None = None) -> BoolRef: ...
def FreshReal(prefix: str = "x", ctx: Context | None = None) -> ArithRef: ...
def FP(name: str, fpsort: FPSortRef, ctx: Context | None = None) -> FPRef: ...
def FPs(names: str, fpsort: FPSortRef, ctx: Context | None = None) -> list[FPRef]: ...
def FPVal(
    val: float | int | str, fpsort: FPSortRef | None = None, ctx: Context | None = None
) -> FPNumRef: ...
def BitVec(name: str, bv: int, ctx: Context | None = None) -> BitVecRef: ...
def BitVecs(names: str, bv: int, ctx: Context | None = None) -> list[BitVecRef]: ...
def BitVecVal(val: int, bv: int, ctx: Context | None = None) -> BitVecNumRef: ...
def K(sort: SortRef, val: ExprRef | int | bool | float | str) -> ArrayRef: ...
def Array(name: str, *sorts: SortRef) -> ArrayRef: ...


@overload
def Lambda(vs: ExprRef, body: ExprRef) -> QuantifierRef: ...
@overload
def Lambda(vs: Sequence[ExprRef], body: ExprRef) -> QuantifierRef: ...


def Var(idx: int, s: SortRef) -> ExprRef: ...


# ══════════════════════════════════════════════════════════════════════
# Logical / Boolean Operations
# ══════════════════════════════════════════════════════════════════════


def And(
    *args: BoolRef | ExprRef | bool | Iterable[BoolRef], ctx: Context | None = None
) -> BoolRef: ...
def Or(
    *args: BoolRef | ExprRef | bool | Iterable[BoolRef], ctx: Context | None = None
) -> BoolRef: ...
def Not(a: BoolRef | ExprRef | bool, ctx: Context | None = None) -> BoolRef: ...
def Implies(
    a: BoolRef | ExprRef | bool, b: BoolRef | ExprRef | bool, ctx: Context | None = None
) -> BoolRef: ...


# If() preserves the type of the then/else branches through TypeVar
@overload
def If(
    a: BoolRef | ExprRef | bool, b: ArithRef, c: ArithRef | int | float, ctx: Context | None = None
) -> ArithRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: ArithRef | int | float, c: ArithRef, ctx: Context | None = None
) -> ArithRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: BoolRef, c: BoolRef | bool, ctx: Context | None = None
) -> BoolRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: BoolRef | bool, c: BoolRef, ctx: Context | None = None
) -> BoolRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: SeqRef, c: SeqRef | str, ctx: Context | None = None
) -> SeqRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: SeqRef | str, c: SeqRef, ctx: Context | None = None
) -> SeqRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: BitVecRef, c: BitVecRef | int, ctx: Context | None = None
) -> BitVecRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: BitVecRef | int, c: BitVecRef, ctx: Context | None = None
) -> BitVecRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: FPRef, c: FPRef | float, ctx: Context | None = None
) -> FPRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: FPRef | float, c: FPRef, ctx: Context | None = None
) -> FPRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: ArrayRef, c: ArrayRef, ctx: Context | None = None
) -> ArrayRef: ...
@overload
def If(
    a: BoolRef | ExprRef | bool, b: _E, c: _E, ctx: Context | None = None
) -> _E: ...
@overload
def If(
    a: BoolRef | ExprRef | bool,
    b: ExprRef | int | bool | float | str,
    c: ExprRef | int | bool | float | str,
    ctx: Context | None = None,
) -> ExprRef: ...


def Xor(
    a: BoolRef | ExprRef | bool, b: BoolRef | ExprRef | bool, ctx: Context | None = None
) -> BoolRef: ...
def Distinct(*args: ExprRef | int | bool | float | str | Sequence[ExprRef]) -> BoolRef: ...


@overload
def ForAll(
    vs: ExprRef, body: BoolRef | ExprRef, weight: int = ..., qid: str = ..., skid: str = ...,
    patterns: Sequence[PatternRef] = ..., no_patterns: Sequence[ExprRef] = ...,
) -> QuantifierRef: ...
@overload
def ForAll(
    vs: Sequence[ExprRef | None], body: BoolRef | ExprRef, weight: int = ..., qid: str = ..., skid: str = ...,
    patterns: Sequence[PatternRef] = ..., no_patterns: Sequence[ExprRef] = ...,
) -> QuantifierRef: ...
@overload
def Exists(
    vs: ExprRef, body: BoolRef | ExprRef, weight: int = ..., qid: str = ..., skid: str = ...,
    patterns: Sequence[PatternRef] = ..., no_patterns: Sequence[ExprRef] = ...,
) -> QuantifierRef: ...
@overload
def Exists(
    vs: Sequence[ExprRef | None], body: BoolRef | ExprRef, weight: int = ..., qid: str = ..., skid: str = ...,
    patterns: Sequence[PatternRef] = ..., no_patterns: Sequence[ExprRef] = ...,
) -> QuantifierRef: ...


def MultiPattern(*args: ExprRef) -> PatternRef: ...


# ══════════════════════════════════════════════════════════════════════
# Arithmetic / Conversion
# ══════════════════════════════════════════════════════════════════════


def Sum(*args: ArithRef | ExprRef | int | float | Iterable[ArithRef | int | float]) -> ArithRef: ...
def Product(*args: ArithRef | ExprRef | int | float | Iterable[ArithRef | int | float]) -> ArithRef: ...
def ToReal(a: ArithRef | ExprRef | int) -> ArithRef: ...
def ToInt(a: ArithRef | ExprRef | int | float) -> ArithRef: ...
def IsInt(a: ArithRef | ExprRef) -> BoolRef: ...
def IntToStr(a: ArithRef | ExprRef | int) -> SeqRef: ...
def StrToInt(a: SeqRef | ExprRef | str) -> ArithRef: ...
def BV2Int(bv: BitVecRef | ExprRef, is_signed: bool = False) -> ArithRef: ...
def Int2BV(a: ArithRef | ExprRef | int, num_bits: int) -> BitVecRef: ...
def Abs(a: ArithRef | ExprRef | int | float) -> ArithRef: ...
def Sqrt(a: ArithRef | ExprRef | int | float, ctx: Context | None = None) -> ArithRef: ...


# ══════════════════════════════════════════════════════════════════════
# Bitvector Operations
# ══════════════════════════════════════════════════════════════════════


@overload
def Extract(high: int, low: int, a: BitVecRef | ExprRef) -> BitVecRef: ...
@overload
def Extract(s: SeqRef | ExprRef, offset: ArithRef | ExprRef | int, length: ArithRef | ExprRef | int) -> SeqRef: ...


@overload
def Concat(*args: BitVecRef) -> BitVecRef: ...
@overload
def Concat(*args: SeqRef) -> SeqRef: ...
@overload
def Concat(*args: ReRef) -> ReRef: ...
@overload
def Concat(*args: ExprRef | str) -> ExprRef: ...


def SignExt(n: int, a: BitVecRef | ExprRef) -> BitVecRef: ...
def ZeroExt(n: int, a: BitVecRef | ExprRef) -> BitVecRef: ...
def RepeatBitVec(n: int, a: BitVecRef | ExprRef) -> BitVecRef: ...
def LShR(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...
def RotateLeft(a: BitVecRef | ExprRef, b: int) -> BitVecRef: ...
def RotateRight(a: BitVecRef | ExprRef, b: int) -> BitVecRef: ...
def ULT(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def ULE(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def UGT(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def UGE(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def SLT(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def SLE(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def SGT(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def SGE(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BoolRef: ...
def UDiv(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...
def URem(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...
def SDiv(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...
def SRem(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...
def SMod(a: BitVecRef | ExprRef, b: BitVecRef | ExprRef | int) -> BitVecRef: ...


# ══════════════════════════════════════════════════════════════════════
# String Operations
# ══════════════════════════════════════════════════════════════════════


def Length(s: SeqRef | ExprRef | str) -> ArithRef: ...
def SubString(
    s: SeqRef | ExprRef | str,
    offset: ArithRef | ExprRef | int,
    length: ArithRef | ExprRef | int,
) -> SeqRef: ...
def SubSeq(
    s: SeqRef | ExprRef,
    offset: ArithRef | ExprRef | int,
    length: ArithRef | ExprRef | int,
) -> SeqRef: ...
def IndexOf(
    s: SeqRef | ExprRef | str,
    substr: SeqRef | ExprRef | str,
    offset: ArithRef | ExprRef | int = ...,
) -> ArithRef: ...
def LastIndexOf(s: SeqRef | ExprRef | str, substr: SeqRef | ExprRef | str) -> ArithRef: ...
def Contains(s: SeqRef | ExprRef | str, substr: SeqRef | ExprRef | str) -> BoolRef: ...
def Replace(
    s: SeqRef | ExprRef | str,
    src: SeqRef | ExprRef | str,
    dst: SeqRef | ExprRef | str,
) -> SeqRef: ...
def PrefixOf(pre: SeqRef | ExprRef | str, s: SeqRef | ExprRef | str) -> BoolRef: ...
def SuffixOf(suf: SeqRef | ExprRef | str, s: SeqRef | ExprRef | str) -> BoolRef: ...
def Unit(elem: ExprRef | int | str) -> SeqRef: ...
def StrToCode(s: SeqRef | ExprRef | str) -> ArithRef: ...
def StrFromCode(c: ArithRef | ExprRef | int) -> SeqRef: ...
def CharFromBV(bv: BitVecRef | ExprRef) -> SeqRef: ...


# ══════════════════════════════════════════════════════════════════════
# Regex Operations
# ══════════════════════════════════════════════════════════════════════


def Re(s: str | SeqRef | ExprRef) -> ReRef: ...
def InRe(s: SeqRef | ExprRef | str, re: ReRef | ExprRef) -> BoolRef: ...
def Union(*args: ReRef | ExprRef) -> ReRef: ...
def Intersect(*args: ReRef | ExprRef) -> ReRef: ...
def Star(re: ReRef | ExprRef) -> ReRef: ...
def Plus(re: ReRef | ExprRef) -> ReRef: ...
def Option(re: ReRef | ExprRef) -> ReRef: ...
def Loop(re: ReRef | ExprRef, lo: int, hi: int = 0) -> ReRef: ...
def Range(lo: str | SeqRef | ExprRef, hi: str | SeqRef | ExprRef) -> ReRef: ...
def AllChar(sort: SortRef | None = None, ctx: Context | None = None) -> ReRef: ...
def Complement(re: ReRef | ExprRef) -> ReRef: ...
def Diff(a: ReRef | ExprRef, b: ReRef | ExprRef) -> ReRef: ...
def Full(sort: SortRef | None = None, ctx: Context | None = None) -> ReRef: ...


# ══════════════════════════════════════════════════════════════════════
# Set Operations
# ══════════════════════════════════════════════════════════════════════


def EmptySet(s: SortRef) -> ArrayRef: ...
def FullSet(s: SortRef) -> ArrayRef: ...
def Empty(s: SortRef | SeqSortRef) -> SeqRef: ...
def SetAdd(s: ArrayRef | ExprRef, elem: ExprRef | int | bool | str) -> ArrayRef: ...
def SetDel(s: ArrayRef | ExprRef, elem: ExprRef | int | bool | str) -> ArrayRef: ...
def SetUnion(*args: ArrayRef | ExprRef) -> ArrayRef: ...
def SetIntersect(*args: ArrayRef | ExprRef) -> ArrayRef: ...
def SetDifference(a: ArrayRef | ExprRef, b: ArrayRef | ExprRef) -> ArrayRef: ...
def SetComplement(a: ArrayRef | ExprRef) -> ArrayRef: ...
def IsMember(elem: ExprRef | int | bool | str, s: ArrayRef | ExprRef) -> BoolRef: ...
def IsSubset(a: ArrayRef | ExprRef, b: ArrayRef | ExprRef) -> BoolRef: ...


# ══════════════════════════════════════════════════════════════════════
# Array Operations
# ══════════════════════════════════════════════════════════════════════


def Select(a: ArrayRef | ExprRef, *idx: ExprRef | int | bool) -> ExprRef: ...
def Store(
    a: ArrayRef | ExprRef,
    idx: ExprRef | int | bool,
    val: ExprRef | int | bool | float | str,
) -> ArrayRef: ...
def Update(
    a: ArrayRef | ExprRef,
    idx: ExprRef | int | bool,
    val: ExprRef | int | bool | float | str,
) -> ArrayRef: ...
def Map(f: FuncDeclRef, *args: ArrayRef | ExprRef) -> ArrayRef: ...
def Default(a: ArrayRef | ExprRef) -> ExprRef: ...
def Ext(a: ArrayRef | ExprRef, b: ArrayRef | ExprRef) -> ExprRef: ...


# ══════════════════════════════════════════════════════════════════════
# Floating-Point Operations
# ══════════════════════════════════════════════════════════════════════


def fpAdd(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpSub(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpMul(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpDiv(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpRem(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpNeg(a: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpAbs(a: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpSqrt(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpFMA(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, b: FPRef | ExprRef, c: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpMin(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpMax(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpRoundToIntegral(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, ctx: Context | None = None) -> FPRef: ...
def fpLT(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpLEQ(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpGT(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpGEQ(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpEQ(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpNEQ(a: FPRef | ExprRef, b: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsNaN(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsInf(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsZero(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsPositive(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsNegative(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsSubnormal(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpIsNormal(a: FPRef | ExprRef, ctx: Context | None = None) -> BoolRef: ...
def fpToSBV(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, s: BitVecSortRef, ctx: Context | None = None) -> BitVecRef: ...
def fpToUBV(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, s: BitVecSortRef, ctx: Context | None = None) -> BitVecRef: ...
def fpToReal(a: FPRef | ExprRef, ctx: Context | None = None) -> ArithRef: ...
def fpToFP(
    rm: FPRMRef | ExprRef,
    a: FPRef | BitVecRef | ArithRef | ExprRef | float | int,
    s: FPSortRef,
    ctx: Context | None = None,
) -> FPRef: ...
def fpFPToFP(rm: FPRMRef | ExprRef, a: FPRef | ExprRef, s: FPSortRef, ctx: Context | None = None) -> FPRef: ...
def fpBVToFP(a: BitVecRef | ExprRef, s: FPSortRef, ctx: Context | None = None) -> FPRef: ...
def fpSignedToFP(
    rm: FPRMRef | ExprRef, a: BitVecRef | ArithRef | ExprRef | int, s: FPSortRef, ctx: Context | None = None
) -> FPRef: ...
def fpUnsignedToFP(
    rm: FPRMRef | ExprRef, a: BitVecRef | ArithRef | ExprRef | int, s: FPSortRef, ctx: Context | None = None
) -> FPRef: ...
def fpRealToFP(rm: FPRMRef | ExprRef, a: ArithRef | ExprRef | float, s: FPSortRef, ctx: Context | None = None) -> FPRef: ...
def fpNaN(s: FPSortRef, ctx: Context | None = None) -> FPNumRef: ...
def fpPlusInfinity(s: FPSortRef, ctx: Context | None = None) -> FPNumRef: ...
def fpMinusInfinity(s: FPSortRef, ctx: Context | None = None) -> FPNumRef: ...
def fpPlusZero(s: FPSortRef, ctx: Context | None = None) -> FPNumRef: ...
def fpMinusZero(s: FPSortRef, ctx: Context | None = None) -> FPNumRef: ...


# ══════════════════════════════════════════════════════════════════════
# FP Rounding Modes
# ══════════════════════════════════════════════════════════════════════


def RNE(ctx: Context | None = None) -> FPRMRef: ...
def RNA(ctx: Context | None = None) -> FPRMRef: ...
def RTP(ctx: Context | None = None) -> FPRMRef: ...
def RTN(ctx: Context | None = None) -> FPRMRef: ...
def RTZ(ctx: Context | None = None) -> FPRMRef: ...
def RoundNearestTiesToEven(ctx: Context | None = None) -> FPRMRef: ...
def RoundNearestTiesToAway(ctx: Context | None = None) -> FPRMRef: ...
def RoundTowardPositive(ctx: Context | None = None) -> FPRMRef: ...
def RoundTowardNegative(ctx: Context | None = None) -> FPRMRef: ...
def RoundTowardZero(ctx: Context | None = None) -> FPRMRef: ...


# ══════════════════════════════════════════════════════════════════════
# Predicate / Test Functions
# ══════════════════════════════════════════════════════════════════════


def is_true(a: ExprRef | BoolRef | object) -> bool: ...
def is_false(a: ExprRef | BoolRef | object) -> bool: ...
def is_const(a: ExprRef | object) -> bool: ...
def is_app(a: ExprRef | object) -> bool: ...
def is_and(a: ExprRef | object) -> bool: ...
def is_or(a: ExprRef | object) -> bool: ...
def is_not(a: ExprRef | object) -> bool: ...
def is_implies(a: ExprRef | object) -> bool: ...
def is_le(a: ExprRef | object) -> bool: ...
def is_lt(a: ExprRef | object) -> bool: ...
def is_ge(a: ExprRef | object) -> bool: ...
def is_gt(a: ExprRef | object) -> bool: ...
def is_eq(a: ExprRef | object) -> bool: ...
def is_distinct(a: ExprRef | object) -> bool: ...
def is_bool(a: object) -> TypeGuard[BoolRef]: ...
def is_int(a: object) -> TypeGuard[ArithRef]: ...
def is_int_value(a: object) -> TypeGuard[IntNumRef]: ...
def is_real(a: object) -> TypeGuard[ArithRef]: ...
def is_rational_value(a: object) -> TypeGuard[RatNumRef]: ...
def is_algebraic_value(a: object) -> TypeGuard[AlgebraicNumRef]: ...
def is_string(a: object) -> TypeGuard[SeqRef]: ...
def is_string_value(a: object) -> TypeGuard[SeqRef]: ...
def is_bv(a: object) -> TypeGuard[BitVecRef]: ...
def is_bv_value(a: object) -> TypeGuard[BitVecNumRef]: ...
def is_fp(a: object) -> TypeGuard[FPRef]: ...
def is_fp_value(a: object) -> TypeGuard[FPNumRef]: ...
def is_fprm(a: object) -> TypeGuard[FPRMRef]: ...
def is_fprm_value(a: object) -> TypeGuard[FPRMRef]: ...
def is_array(a: object) -> TypeGuard[ArrayRef]: ...
def is_select(a: object) -> bool: ...
def is_store(a: object) -> bool: ...
def is_map(a: object) -> bool: ...
def is_const_array(a: object) -> bool: ...
def is_K(a: object) -> bool: ...
def is_default(a: object) -> bool: ...
def is_quantifier(a: object) -> TypeGuard[QuantifierRef]: ...
def is_var(a: object) -> bool: ...
def is_add(a: object) -> bool: ...
def is_sub(a: object) -> bool: ...
def is_mul(a: object) -> bool: ...
def is_div(a: object) -> bool: ...
def is_idiv(a: object) -> bool: ...
def is_mod(a: object) -> bool: ...
def is_to_real(a: object) -> bool: ...
def is_to_int(a: object) -> bool: ...
def is_is_int(a: object) -> bool: ...
def is_expr(a: object) -> TypeGuard[ExprRef]: ...
def is_sort(a: object) -> TypeGuard[SortRef]: ...
def is_func_decl(a: object) -> TypeGuard[FuncDeclRef]: ...
def is_app_of(a: ExprRef, k: int) -> bool: ...
def eq(a: ExprRef, b: ExprRef) -> bool: ...


# ══════════════════════════════════════════════════════════════════════
# Utility Functions
# ══════════════════════════════════════════════════════════════════════


# simplify() preserves type through overloads
@overload
def simplify(a: BoolRef, *args: str, **kwargs: str | int | bool) -> BoolRef: ...
@overload
def simplify(a: ArithRef, *args: str, **kwargs: str | int | bool) -> ArithRef: ...
@overload
def simplify(a: BitVecRef, *args: str, **kwargs: str | int | bool) -> BitVecRef: ...
@overload
def simplify(a: SeqRef, *args: str, **kwargs: str | int | bool) -> SeqRef: ...
@overload
def simplify(a: FPRef, *args: str, **kwargs: str | int | bool) -> FPRef: ...
@overload
def simplify(a: ArrayRef, *args: str, **kwargs: str | int | bool) -> ArrayRef: ...
@overload
def simplify(a: ReRef, *args: str, **kwargs: str | int | bool) -> ReRef: ...
@overload
def simplify(a: ExprRef, *args: str, **kwargs: str | int | bool) -> ExprRef: ...


@overload
def substitute(a: ExprRef, m: Sequence[tuple[ExprRef, ExprRef]]) -> ExprRef: ...
@overload
def substitute(a: ExprRef, m: Sequence[tuple[ExprRef | None, ExprRef]]) -> ExprRef: ...
@overload
def substitute(a: ExprRef, *m: tuple[ExprRef, ExprRef]) -> ExprRef: ...
def substitute_vars(a: ExprRef, *m: ExprRef) -> ExprRef: ...
def substitute_funs(
    a: ExprRef, *m: tuple[FuncDeclRef, Sequence[ExprRef], ExprRef]
) -> ExprRef: ...
def solve(*args: BoolRef | ExprRef, **kwargs: str | int | bool) -> None: ...
def prove(claim: BoolRef | ExprRef, **kwargs: str | int | bool) -> None: ...
def Function(name: str, *sig: SortRef) -> FuncDeclRef: ...
def RecFunction(name: str, *sig: SortRef) -> FuncDeclRef: ...
def RecAddDefinition(f: FuncDeclRef, args: Sequence[ExprRef], body: ExprRef) -> None: ...
def describe_tactics() -> str: ...
def describe_probes() -> str: ...
def tactic_description(name: str) -> str: ...
def probe_description(name: str) -> str: ...
def tactics() -> list[str]: ...
def probes() -> list[str]: ...
def get_version_string() -> str: ...
def get_version() -> tuple[int, int, int, int]: ...


# ══════════════════════════════════════════════════════════════════════
# Z3 Op-codes (int constants)
# ══════════════════════════════════════════════════════════════════════


Z3_OP_UNINTERPRETED: int
Z3_OP_TRUE: int
Z3_OP_FALSE: int
Z3_OP_AND: int
Z3_OP_OR: int
Z3_OP_NOT: int
Z3_OP_IFF: int
Z3_OP_XOR: int
Z3_OP_ITE: int
Z3_OP_EQ: int
Z3_OP_DISTINCT: int
Z3_OP_ADD: int
Z3_OP_SUB: int
Z3_OP_MUL: int
Z3_OP_DIV: int
Z3_OP_IDIV: int
Z3_OP_MOD: int
Z3_OP_REM: int
Z3_OP_POWER: int
Z3_OP_LE: int
Z3_OP_LT: int
Z3_OP_GE: int
Z3_OP_GT: int
Z3_OP_UMINUS: int
Z3_OP_TO_REAL: int
Z3_OP_TO_INT: int
Z3_OP_IS_INT: int
Z3_OP_IMPLIES: int
Z3_OP_SELECT: int
Z3_OP_STORE: int
Z3_OP_CONCAT: int
Z3_OP_EXTRACT: int
Z3_OP_SEQ_PREFIX: int
Z3_OP_SEQ_SUFFIX: int
Z3_OP_SEQ_CONTAINS: int
Z3_OP_SEQ_AT: int
Z3_OP_SEQ_LENGTH: int
Z3_OP_SEQ_INDEX: int
Z3_OP_SEQ_CONCAT: int
Z3_OP_SEQ_EXTRACT: int
Z3_OP_SEQ_REPLACE: int
Z3_OP_SEQ_UNIT: int
Z3_OP_SEQ_EMPTY: int
Z3_OP_STR_TO_INT: int
Z3_OP_INT_TO_STR: int
Z3_OP_RE_FULL_SET: int
Z3_OP_RE_EMPTY_SET: int
Z3_OP_RE_CONCAT: int
Z3_OP_RE_UNION: int
Z3_OP_RE_INTERSECT: int
Z3_OP_RE_STAR: int
Z3_OP_RE_PLUS: int
Z3_OP_RE_OPTION: int
Z3_OP_RE_LOOP: int
Z3_OP_RE_RANGE: int
Z3_OP_RE_COMPLEMENT: int
Z3_OP_FPA_NUM: int
Z3_OP_FPA_PLUS_INF: int
Z3_OP_FPA_MINUS_INF: int
Z3_OP_FPA_NAN: int
Z3_OP_FPA_PLUS_ZERO: int
Z3_OP_FPA_MINUS_ZERO: int

# Sort kinds
Z3_UNINTERPRETED_SORT: int
Z3_BOOL_SORT: int
Z3_INT_SORT: int
Z3_REAL_SORT: int
Z3_BV_SORT: int
Z3_ARRAY_SORT: int
Z3_DATATYPE_SORT: int
Z3_RELATION_SORT: int
Z3_FINITE_DOMAIN_SORT: int
Z3_FLOATING_POINT_SORT: int
Z3_ROUNDING_MODE_SORT: int
Z3_SEQ_SORT: int
Z3_RE_SORT: int
Z3_CHAR_SORT: int
Z3_TYPE_VAR: int
Z3_UNKNOWN_SORT: int


# ══════════════════════════════════════════════════════════════════════
# Additional commonly used functions
# ══════════════════════════════════════════════════════════════════════


def parse_smt2_string(
    s: str,
    sorts: dict[str, SortRef] = ...,
    decls: dict[str, FuncDeclRef | ExprRef] = ...,
    ctx: Context | None = None,
) -> AstVector: ...


def parse_smt2_file(
    f: str,
    sorts: dict[str, SortRef] = ...,
    decls: dict[str, FuncDeclRef | ExprRef] = ...,
    ctx: Context | None = None,
) -> AstVector: ...


def set_option(*args: str | int, **kwargs: str | int | bool) -> None: ...
