"""Type stubs for z3-solver — covers all z3 usage in pyspectre.

z3 is dynamically typed at runtime; these stubs are intentionally permissive
to match z3's actual behavior where ExprRef subtypes are interchangeable
depending on the underlying sort.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, overload

# ── Sort hierarchy ──────────────────────────────────────────────

class SortRef:
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def kind(self) -> int: ...

class BoolSortRef(SortRef): ...
class ArithSortRef(SortRef): ...

class BitVecSortRef(SortRef):
    def size(self) -> int: ...

class FPSortRef(SortRef):
    def ebits(self) -> int: ...
    def sbits(self) -> int: ...

class SeqSortRef(SortRef): ...
class ReSortRef(SortRef): ...
class ArraySortRef(SortRef): ...
class DatatypeSortRef(SortRef): ...
class FiniteDomainSortRef(SortRef): ...
class CharSortRef(SortRef): ...
class TypeVarRef(SortRef): ...

# ── AST base ────────────────────────────────────────────────────

class AstRef:
    def sexpr(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def hash(self) -> int: ...
    def ctx_ref(self) -> Any: ...

class AstVector:
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> AstRef: ...
    def __iter__(self) -> Iterator[AstRef]: ...
    def __contains__(self, item: AstRef) -> bool: ...
    def push(self, v: AstRef) -> None: ...

# ── Expression hierarchy ────────────────────────────────────────

# NOTE: ExprRef has all arithmetic/comparison operators because z3
# dispatches based on sort at runtime.  Functions like If(), simplify(),
# ModelRef.eval() return ExprRef, and callers routinely use arithmetic
# and comparison operators on those results.

class ExprRef(AstRef):
    def sort(self) -> SortRef: ...
    def sort_kind(self) -> int: ...
    def decl(self) -> FuncDeclRef: ...
    def children(self) -> list[ExprRef]: ...
    def num_args(self) -> int: ...
    def arg(self, i: int) -> ExprRef: ...
    def __eq__(self, other: Any) -> BoolRef: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> BoolRef: ...  # type: ignore[override]
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    # Arithmetic operators — valid when sort is Int/Real at runtime
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    # Comparison operators — valid for Int/Real/BV/Seq sorts
    def __le__(self, other: Any) -> BoolRef: ...
    def __lt__(self, other: Any) -> BoolRef: ...
    def __ge__(self, other: Any) -> BoolRef: ...
    def __gt__(self, other: Any) -> BoolRef: ...
    # Value extraction — valid for concrete/evaluated values
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_fraction(self) -> Any: ...
    def as_signed_long(self) -> int: ...
    # Sequence operators (valid when sort is Seq at runtime)
    def __getitem__(self, idx: Any) -> Any: ...
    def __contains__(self, other: Any) -> Any: ...
    def at(self, i: Any) -> Any: ...

class BoolRef(ExprRef):
    def __and__(self, other: BoolRef | ExprRef) -> BoolRef: ...
    def __or__(self, other: BoolRef | ExprRef) -> BoolRef: ...
    def __rand__(self, other: BoolRef | ExprRef) -> BoolRef: ...
    def __ror__(self, other: BoolRef | ExprRef) -> BoolRef: ...
    def __invert__(self) -> BoolRef: ...

class ArithRef(ExprRef):
    def __add__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __radd__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __sub__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __rsub__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __mul__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __rmul__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __truediv__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __rtruediv__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __mod__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __rmod__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __pow__(self, other: ArithRef | ExprRef | int | float) -> ArithRef: ...
    def __neg__(self) -> ArithRef: ...
    def __le__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...
    def __lt__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...
    def __ge__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...
    def __gt__(self, other: ArithRef | ExprRef | int | float) -> BoolRef: ...
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_fraction(self) -> Any: ...
    def is_int(self) -> bool: ...

class IntNumRef(ArithRef):
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...

class RatNumRef(ArithRef):
    def as_long(self) -> int: ...
    def as_decimal(self, prec: int) -> str: ...
    def as_string(self) -> str: ...
    def as_fraction(self) -> Any: ...
    def numerator(self) -> IntNumRef: ...
    def denominator(self) -> IntNumRef: ...
    def numerator_as_long(self) -> int: ...
    def denominator_as_long(self) -> int: ...

class AlgebraicNumRef(ArithRef): ...
class IntRef(ArithRef): ...
class RealRef(ArithRef): ...

class SeqRef(ExprRef):
    def __add__(self, other: SeqRef | str) -> SeqRef: ...
    def __radd__(self, other: SeqRef | str) -> SeqRef: ...
    def __getitem__(self, idx: Any) -> SeqRef: ...
    def __contains__(self, other: Any) -> BoolRef: ...
    def __le__(self, other: SeqRef | str | ExprRef) -> BoolRef: ...
    def __lt__(self, other: SeqRef | str | ExprRef) -> BoolRef: ...
    def __ge__(self, other: SeqRef | str | ExprRef) -> BoolRef: ...
    def __gt__(self, other: SeqRef | str | ExprRef) -> BoolRef: ...
    def as_string(self) -> str: ...
    def at(self, i: ArithRef | int) -> SeqRef: ...

class CharRef(ExprRef): ...
class ReRef(ExprRef): ...

class BitVecRef(ExprRef):
    def size(self) -> int: ...
    def __add__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __radd__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __sub__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __rsub__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __mul__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __rmul__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __and__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __rand__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __or__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __ror__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __xor__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __rxor__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __invert__(self) -> BitVecRef: ...
    def __lshift__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __rshift__(self, other: BitVecRef | int) -> BitVecRef: ...
    def __neg__(self) -> BitVecRef: ...
    def __le__(self, other: BitVecRef | int) -> BoolRef: ...
    def __lt__(self, other: BitVecRef | int) -> BoolRef: ...
    def __ge__(self, other: BitVecRef | int) -> BoolRef: ...
    def __gt__(self, other: BitVecRef | int) -> BoolRef: ...
    def as_long(self) -> int: ...
    def as_signed_long(self) -> int: ...

class BitVecNumRef(BitVecRef):
    def as_long(self) -> int: ...
    def as_string(self) -> str: ...
    def as_signed_long(self) -> int: ...

class ArrayRef(ExprRef):
    def __getitem__(self, idx: Any) -> ExprRef: ...
    def sort(self) -> ArraySortRef: ...
    def domain(self) -> SortRef: ...
    def range(self) -> SortRef: ...
    def default(self) -> ExprRef: ...

class FPRef(ExprRef):
    def sort(self) -> FPSortRef: ...
    def ebits(self) -> int: ...
    def sbits(self) -> int: ...
    def __add__(self, other: FPRef | float) -> FPRef: ...
    def __radd__(self, other: FPRef | float) -> FPRef: ...
    def __sub__(self, other: FPRef | float) -> FPRef: ...
    def __rsub__(self, other: FPRef | float) -> FPRef: ...
    def __mul__(self, other: FPRef | float) -> FPRef: ...
    def __rmul__(self, other: FPRef | float) -> FPRef: ...
    def __truediv__(self, other: FPRef | float) -> FPRef: ...
    def __neg__(self) -> FPRef: ...
    def __le__(self, other: FPRef | float) -> BoolRef: ...
    def __lt__(self, other: FPRef | float) -> BoolRef: ...
    def __ge__(self, other: FPRef | float) -> BoolRef: ...
    def __gt__(self, other: FPRef | float) -> BoolRef: ...

class FPNumRef(FPRef):
    def as_string(self) -> str: ...

class FPRMRef(ExprRef): ...
class DatatypeRef(ExprRef): ...
class FiniteDomainRef(ExprRef): ...
class FiniteDomainNumRef(FiniteDomainRef): ...
class PatternRef(AstRef): ...

class QuantifierRef(BoolRef):
    def is_forall(self) -> bool: ...
    def is_exists(self) -> bool: ...
    def num_vars(self) -> int: ...
    def var_name(self, i: int) -> str: ...
    def var_sort(self, i: int) -> SortRef: ...
    def body(self) -> ExprRef: ...
    def weight(self) -> int: ...

# ── FuncDeclRef ─────────────────────────────────────────────────

class FuncDeclRef(AstRef):
    def name(self) -> str: ...
    def arity(self) -> int: ...
    def kind(self) -> int: ...
    def domain(self, i: int) -> SortRef: ...
    def range(self) -> SortRef: ...
    def __call__(self, *args: Any) -> ExprRef: ...

# ── ModelRef ────────────────────────────────────────────────────

class ModelRef:
    def decls(self) -> list[FuncDeclRef]: ...
    # eval/evaluate return Any to allow assignment to ArithRef, BoolRef, etc.
    def eval(self, expr: ExprRef, model_completion: bool = False) -> Any: ...
    def evaluate(self, expr: ExprRef, model_completion: bool = False) -> Any: ...
    @overload
    def __getitem__(self, key: FuncDeclRef) -> ExprRef: ...
    @overload
    def __getitem__(self, key: ExprRef) -> ExprRef: ...
    def __getitem__(self, key: Any) -> ExprRef: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[FuncDeclRef]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def get_interp(self, decl: FuncDeclRef) -> ExprRef | FuncInterp | None: ...
    def num_sorts(self) -> int: ...

# ── FuncInterp ─────────────────────────────────────────────────

class FuncInterp:
    def else_value(self) -> ExprRef: ...
    def num_entries(self) -> int: ...
    def entry(self, i: int) -> FuncEntry: ...
    def arity(self) -> int: ...
    def __len__(self) -> int: ...

class FuncEntry:
    def num_args(self) -> int: ...
    def arg_value(self, i: int) -> ExprRef: ...
    def value(self) -> ExprRef: ...

# ── CheckSatResult ──────────────────────────────────────────────

class CheckSatResult:
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

sat: CheckSatResult
unsat: CheckSatResult
unknown: CheckSatResult

# ── Solver ──────────────────────────────────────────────────────

class Solver:
    def __init__(self, solver: Any = None, ctx: Any = None) -> None: ...
    def add(self, *args: Any) -> None: ...
    def append(self, *args: Any) -> None: ...
    def insert(self, *args: Any) -> None: ...
    def assert_exprs(self, *args: Any) -> None: ...
    def check(self, *assumptions: Any) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def push(self) -> None: ...
    def pop(self, n: int = 1) -> None: ...
    def reset(self) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def assertions(self) -> AstVector: ...
    def unsat_core(self) -> AstVector: ...
    def from_string(self, s: str) -> None: ...
    def from_file(self, f: str) -> None: ...
    def to_smt2(self) -> str: ...
    def sexpr(self) -> str: ...
    def statistics(self) -> Any: ...
    def reason_unknown(self) -> str: ...
    def num_scopes(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── Optimize ────────────────────────────────────────────────────

class OptimizeObjective:
    def lower(self) -> ExprRef: ...
    def upper(self) -> ExprRef: ...
    def value(self) -> ExprRef: ...

class Optimize:
    def __init__(self, ctx: Any = None) -> None: ...
    def add(self, *args: Any) -> None: ...
    def check(self, *assumptions: Any) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def push(self) -> None: ...
    def pop(self) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def maximize(self, arg: ArithRef) -> OptimizeObjective: ...
    def minimize(self, arg: ArithRef) -> OptimizeObjective: ...
    def assertions(self) -> AstVector: ...

# ── Goal / Tactic ───────────────────────────────────────────────

class Goal:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, *args: Any) -> None: ...
    def as_expr(self) -> BoolRef: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> ExprRef: ...
    def __iter__(self) -> Iterator[ExprRef]: ...
    def __repr__(self) -> str: ...

class ApplyResult:
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Goal: ...
    def as_expr(self) -> ExprRef: ...

class Tactic:
    def __init__(self, name: str, ctx: Any = None) -> None: ...
    def __call__(self, goal: Goal, *args: Any, **kwargs: Any) -> ApplyResult: ...

class Probe:
    def __init__(self, name: str, ctx: Any = None) -> None: ...
    def __call__(self, goal: Goal) -> float: ...
    def __eq__(self, other: Any) -> Probe: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> Probe: ...  # type: ignore[override]
    def __le__(self, other: Any) -> Probe: ...
    def __lt__(self, other: Any) -> Probe: ...
    def __ge__(self, other: Any) -> Probe: ...
    def __gt__(self, other: Any) -> Probe: ...

def Then(*tactics: Any, **kwargs: Any) -> Tactic: ...
def OrElse(*tactics: Any, **kwargs: Any) -> Tactic: ...
def With(tactic: Tactic, **kwargs: Any) -> Tactic: ...

# ── Sort constructors ──────────────────────────────────────────

def IntSort(ctx: Any = None) -> ArithSortRef: ...
def BoolSort(ctx: Any = None) -> BoolSortRef: ...
def RealSort(ctx: Any = None) -> ArithSortRef: ...
def StringSort(ctx: Any = None) -> SeqSortRef: ...
def BitVecSort(sz: int, ctx: Any = None) -> BitVecSortRef: ...
def SeqSort(s: SortRef) -> SeqSortRef: ...
def SetSort(s: SortRef) -> ArraySortRef: ...
def ArraySort(*sig: SortRef) -> ArraySortRef: ...
def FPSort(ebits: int, sbits: int, ctx: Any = None) -> FPSortRef: ...
def Float16(ctx: Any = None) -> FPSortRef: ...
def Float32(ctx: Any = None) -> FPSortRef: ...
def Float64(ctx: Any = None) -> FPSortRef: ...
def Float128(ctx: Any = None) -> FPSortRef: ...
def DeclareSort(name: str, ctx: Any = None) -> SortRef: ...
def CharSort(ctx: Any = None) -> CharSortRef: ...

# ── Variable / value constructors ──────────────────────────────

def Int(name: str, ctx: Any = None) -> ArithRef: ...
def Ints(names: str, ctx: Any = None) -> list[ArithRef]: ...
def IntVal(val: int, ctx: Any = None) -> IntNumRef: ...
def Bool(name: str, ctx: Any = None) -> BoolRef: ...
def BoolVal(val: bool, ctx: Any = None) -> BoolRef: ...
def Bools(names: str, ctx: Any = None) -> list[BoolRef]: ...
def Real(name: str, ctx: Any = None) -> ArithRef: ...
def RealVal(val: int | float | str, ctx: Any = None) -> RatNumRef: ...
def Reals(names: str, ctx: Any = None) -> list[ArithRef]: ...
def String(name: str, ctx: Any = None) -> SeqRef: ...
def StringVal(val: str, ctx: Any = None) -> SeqRef: ...
def Strings(names: str, ctx: Any = None) -> list[SeqRef]: ...
def Const(name: str, sort: SortRef) -> ExprRef: ...
def Consts(names: str, sort: SortRef) -> list[ExprRef]: ...
def FreshConst(sort: SortRef, prefix: str = "c") -> ExprRef: ...
def FP(name: str, fpsort: FPSortRef, ctx: Any = None) -> FPRef: ...
def FPs(names: str, fpsort: FPSortRef, ctx: Any = None) -> list[FPRef]: ...
def FPVal(val: float | int | str, fpsort: FPSortRef | None = None, ctx: Any = None) -> FPNumRef: ...
def BitVec(name: str, bv: int, ctx: Any = None) -> BitVecRef: ...
def BitVecs(names: str, bv: int, ctx: Any = None) -> list[BitVecRef]: ...
def BitVecVal(val: int, bv: int, ctx: Any = None) -> BitVecNumRef: ...
def K(sort: SortRef, val: Any) -> ArrayRef: ...
def Array(name: str, *sorts: SortRef) -> ArrayRef: ...
def Lambda(vs: Any, body: Any) -> ExprRef: ...
def Var(idx: int, s: SortRef) -> ExprRef: ...

# ── Logical / boolean operations ───────────────────────────────

def And(*args: Any) -> BoolRef: ...
def Or(*args: Any) -> BoolRef: ...
def Not(a: Any, ctx: Any = None) -> BoolRef: ...
def Implies(a: Any, b: Any, ctx: Any = None) -> BoolRef: ...

# If() returns Any because result type depends on arguments (ArithRef, BoolRef, SeqRef, etc.)
def If(a: Any, b: Any, c: Any, ctx: Any = None) -> Any: ...
def Xor(a: Any, b: Any, ctx: Any = None) -> BoolRef: ...
def Distinct(*args: Any) -> BoolRef: ...
def ForAll(vs: Any, body: Any, *args: Any, **kwargs: Any) -> QuantifierRef: ...
def Exists(vs: Any, body: Any, *args: Any, **kwargs: Any) -> QuantifierRef: ...
def MultiPattern(*args: ExprRef) -> PatternRef: ...

# ── Arithmetic / conversion ────────────────────────────────────

def Sum(*args: Any) -> ArithRef: ...
def Product(*args: Any) -> ArithRef: ...
def ToReal(a: Any) -> ArithRef: ...
def ToInt(a: Any) -> ArithRef: ...
def IntToStr(a: Any) -> SeqRef: ...
def StrToInt(a: Any) -> ArithRef: ...
def BV2Int(bv: BitVecRef, is_signed: bool = False) -> ArithRef: ...
def Int2BV(a: ArithRef, num_bits: int) -> BitVecRef: ...
def Abs(a: Any) -> ArithRef: ...

# ── Bitvector operations ───────────────────────────────────────

@overload
def Extract(high: int, low: int, a: BitVecRef) -> BitVecRef: ...
@overload
def Extract(s: SeqRef, offset: ArithRef | int, length: ArithRef | int) -> SeqRef: ...
@overload
def Extract(s: Any, offset: Any, length: Any) -> Any: ...
@overload
def Concat(*args: BitVecRef) -> BitVecRef: ...
@overload
def Concat(*args: SeqRef) -> SeqRef: ...
@overload
def Concat(*args: ReRef) -> ReRef: ...
@overload
def Concat(*args: Any) -> Any: ...
def SignExt(n: int, a: BitVecRef) -> BitVecRef: ...
def ZeroExt(n: int, a: BitVecRef) -> BitVecRef: ...
def LShR(a: BitVecRef, b: BitVecRef | int) -> BitVecRef: ...
def RotateLeft(a: BitVecRef, b: int) -> BitVecRef: ...
def RotateRight(a: BitVecRef, b: int) -> BitVecRef: ...
def ULT(a: BitVecRef, b: BitVecRef | int) -> BoolRef: ...
def ULE(a: BitVecRef, b: BitVecRef | int) -> BoolRef: ...
def UGT(a: BitVecRef, b: BitVecRef | int) -> BoolRef: ...
def UGE(a: BitVecRef, b: BitVecRef | int) -> BoolRef: ...
def UDiv(a: BitVecRef, b: BitVecRef | int) -> BitVecRef: ...
def URem(a: BitVecRef, b: BitVecRef | int) -> BitVecRef: ...
def SRem(a: BitVecRef, b: BitVecRef | int) -> BitVecRef: ...

# ── String operations ──────────────────────────────────────────

def Length(s: SeqRef | ExprRef) -> ArithRef: ...
def SubString(
    s: SeqRef | ExprRef, offset: ArithRef | ExprRef | int, length: ArithRef | ExprRef | int
) -> SeqRef: ...
def IndexOf(
    s: SeqRef | ExprRef, substr: SeqRef | ExprRef | str, offset: ArithRef | ExprRef | int = ...
) -> ArithRef: ...
def Contains(s: SeqRef | ExprRef, substr: SeqRef | ExprRef | str) -> BoolRef: ...
def Replace(
    s: SeqRef | ExprRef, src: SeqRef | ExprRef | str, dst: SeqRef | ExprRef | str
) -> SeqRef: ...
def PrefixOf(pre: SeqRef | ExprRef | str, s: SeqRef | ExprRef) -> BoolRef: ...
def SuffixOf(suf: SeqRef | ExprRef | str, s: SeqRef | ExprRef) -> BoolRef: ...
def Unit(elem: ExprRef) -> SeqRef: ...
def StrToCode(s: SeqRef | ExprRef) -> ArithRef: ...
def StrFromCode(c: ArithRef | ExprRef | int) -> SeqRef: ...

# ── Regex operations ───────────────────────────────────────────

def Re(s: str | SeqRef) -> ReRef: ...
def InRe(s: SeqRef | ExprRef, re: ReRef) -> BoolRef: ...
def Union(*args: ReRef) -> ReRef: ...
def Intersect(*args: ReRef) -> ReRef: ...
def Star(re: ReRef) -> ReRef: ...
def Plus(re: ReRef) -> ReRef: ...
def Option(re: ReRef) -> ReRef: ...
def Loop(re: ReRef, lo: int, hi: int = 0) -> ReRef: ...
def Range(lo: str | SeqRef, hi: str | SeqRef) -> ReRef: ...
def AllChar(sort: SortRef | None = None, ctx: Any = None) -> ReRef: ...
def Complement(re: ReRef) -> ReRef: ...

# ── Set operations ─────────────────────────────────────────────

def EmptySet(s: SortRef) -> ArrayRef: ...
def FullSet(s: SortRef) -> ArrayRef: ...
def Empty(s: SortRef) -> SeqRef: ...
def SetAdd(s: ArrayRef, elem: ExprRef | int) -> ArrayRef: ...
def SetDel(s: ArrayRef, elem: ExprRef | int) -> ArrayRef: ...
def SetUnion(*args: ArrayRef) -> ArrayRef: ...
def SetIntersect(*args: ArrayRef) -> ArrayRef: ...
def SetDifference(a: ArrayRef, b: ArrayRef) -> ArrayRef: ...
def SetComplement(a: ArrayRef) -> ArrayRef: ...
def IsMember(elem: ExprRef | int, s: ArrayRef | ExprRef) -> BoolRef: ...
def IsSubset(a: ArrayRef | ExprRef, b: ArrayRef | ExprRef) -> BoolRef: ...

# ── Array operations ───────────────────────────────────────────

def Select(a: ArrayRef | ExprRef, idx: ExprRef | int | bool) -> ExprRef: ...
def Store(
    a: ArrayRef | ExprRef, idx: ExprRef | int | bool, val: ExprRef | int | bool | str
) -> ArrayRef: ...
def Update(
    a: ArrayRef | ExprRef, idx: ExprRef | int | bool, val: ExprRef | int | bool | str
) -> ArrayRef: ...
def Map(f: FuncDeclRef, *args: ArrayRef) -> ArrayRef: ...
def Default(a: ArrayRef) -> ExprRef: ...

# ── Floating-point operations ──────────────────────────────────

def fpAdd(rm: FPRMRef, a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpSub(rm: FPRMRef, a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpMul(rm: FPRMRef, a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpDiv(rm: FPRMRef, a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpRem(a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpNeg(a: FPRef, ctx: Any = None) -> FPRef: ...
def fpAbs(a: FPRef, ctx: Any = None) -> FPRef: ...
def fpSqrt(rm: FPRMRef, a: FPRef, ctx: Any = None) -> FPRef: ...
def fpFMA(rm: FPRMRef, a: FPRef, b: FPRef, c: FPRef, ctx: Any = None) -> FPRef: ...
def fpMin(a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpMax(a: FPRef, b: FPRef, ctx: Any = None) -> FPRef: ...
def fpLT(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpLEQ(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpGT(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpGEQ(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpEQ(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpNEQ(a: FPRef, b: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsNaN(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsInf(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsZero(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsPositive(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsNegative(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsSubnormal(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpIsNormal(a: FPRef, ctx: Any = None) -> BoolRef: ...
def fpToSBV(rm: FPRMRef, a: FPRef, s: BitVecSortRef, ctx: Any = None) -> BitVecRef: ...
def fpToUBV(rm: FPRMRef, a: FPRef, s: BitVecSortRef, ctx: Any = None) -> BitVecRef: ...
def fpToReal(a: FPRef, ctx: Any = None) -> ArithRef: ...
def fpToFP(rm: FPRMRef, a: Any, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpSignedToFP(rm: FPRMRef, a: Any, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpUnsignedToFP(rm: FPRMRef, a: Any, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpRealToFP(rm: FPRMRef, a: ArithRef, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpBVToFP(a: BitVecRef, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpFPToFP(rm: FPRMRef, a: FPRef, s: FPSortRef, ctx: Any = None) -> FPRef: ...
def fpNaN(s: FPSortRef, ctx: Any = None) -> FPNumRef: ...
def fpPlusInfinity(s: FPSortRef, ctx: Any = None) -> FPNumRef: ...
def fpMinusInfinity(s: FPSortRef, ctx: Any = None) -> FPNumRef: ...
def fpPlusZero(s: FPSortRef, ctx: Any = None) -> FPNumRef: ...
def fpMinusZero(s: FPSortRef, ctx: Any = None) -> FPNumRef: ...

# ── FP Rounding Modes ──────────────────────────────────────────

def RNE(ctx: Any = None) -> FPRMRef: ...
def RNA(ctx: Any = None) -> FPRMRef: ...
def RTP(ctx: Any = None) -> FPRMRef: ...
def RTN(ctx: Any = None) -> FPRMRef: ...
def RTZ(ctx: Any = None) -> FPRMRef: ...

# ── Predicate / test functions ─────────────────────────────────

def is_true(a: Any) -> bool: ...
def is_false(a: Any) -> bool: ...
def is_const(a: Any) -> bool: ...
def is_app(a: Any) -> bool: ...
def is_and(a: Any) -> bool: ...
def is_or(a: Any) -> bool: ...
def is_not(a: Any) -> bool: ...
def is_le(a: Any) -> bool: ...
def is_lt(a: Any) -> bool: ...
def is_ge(a: Any) -> bool: ...
def is_gt(a: Any) -> bool: ...
def is_eq(a: Any) -> bool: ...
def is_bool(a: Any) -> bool: ...
def is_int(a: Any) -> bool: ...
def is_int_value(a: Any) -> bool: ...
def is_real(a: Any) -> bool: ...
def is_rational_value(a: Any) -> bool: ...
def is_string(a: Any) -> bool: ...
def is_string_value(a: Any) -> bool: ...
def is_bv(a: Any) -> bool: ...
def is_bv_value(a: Any) -> bool: ...
def is_fp(a: Any) -> bool: ...
def is_fp_value(a: Any) -> bool: ...
def is_array(a: Any) -> bool: ...
def is_select(a: Any) -> bool: ...
def is_store(a: Any) -> bool: ...
def is_quantifier(a: Any) -> bool: ...
def is_var(a: Any) -> bool: ...
def eq(a: ExprRef, b: ExprRef) -> bool: ...

# ── Utility functions ──────────────────────────────────────────

# simplify() returns Any because result sort matches input sort
def simplify(a: ExprRef, *args: Any, **kwargs: Any) -> Any: ...
def substitute(a: ExprRef, *m: Any) -> ExprRef: ...
def substitute_vars(a: ExprRef, *m: ExprRef) -> ExprRef: ...
def solve(*args: Any, **kwargs: Any) -> None: ...
def prove(claim: BoolRef, **kwargs: Any) -> None: ...
def Function(name: str, *sig: SortRef) -> FuncDeclRef: ...
def RecFunction(name: str, *sig: SortRef) -> FuncDeclRef: ...
def RecAddDefinition(f: FuncDeclRef, args: list[ExprRef], body: ExprRef) -> None: ...
def describe_tactics() -> str: ...
def describe_probes() -> str: ...
def is_expr(a: Any) -> bool: ...
def get_version_string() -> str: ...
def get_version() -> tuple[int, int, int, int]: ...

# ── Z3 op-codes (int constants) ────────────────────────────────

Z3_OP_UNINTERPRETED: int
Z3_OP_TRUE: int
Z3_OP_FALSE: int
Z3_OP_AND: int
Z3_OP_OR: int
Z3_OP_NOT: int
Z3_OP_IFF: int
Z3_OP_XOR: int
Z3_OP_ITE: int
Z3_OP_EQ: int
Z3_OP_DISTINCT: int
Z3_OP_ADD: int
Z3_OP_SUB: int
Z3_OP_MUL: int
Z3_OP_DIV: int
Z3_OP_IDIV: int
Z3_OP_MOD: int
Z3_OP_REM: int
Z3_OP_POWER: int
Z3_OP_LE: int
Z3_OP_LT: int
Z3_OP_GE: int
Z3_OP_GT: int
Z3_OP_UMINUS: int
Z3_OP_TO_REAL: int
Z3_OP_TO_INT: int
Z3_OP_IS_INT: int
Z3_OP_IMPLIES: int
Z3_OP_SELECT: int
Z3_OP_STORE: int
Z3_OP_CONCAT: int
Z3_OP_EXTRACT: int
Z3_OP_SEQ_PREFIX: int
Z3_OP_SEQ_SUFFIX: int
Z3_OP_SEQ_CONTAINS: int
Z3_OP_SEQ_AT: int
Z3_OP_SEQ_LENGTH: int
Z3_OP_SEQ_INDEX: int
Z3_OP_SEQ_REPLACE: int
Z3_OP_SEQ_UNIT: int
Z3_OP_SEQ_EMPTY: int
Z3_OP_STR_TO_INT: int
Z3_OP_INT_TO_STR: int
Z3_OP_RE_FULL_SET: int
Z3_OP_RE_EMPTY_SET: int
Z3_OP_RE_CONCAT: int
Z3_OP_RE_UNION: int
Z3_OP_RE_INTERSECT: int
Z3_OP_RE_STAR: int
Z3_OP_RE_PLUS: int
Z3_OP_RE_OPTION: int
Z3_OP_RE_LOOP: int
Z3_OP_RE_RANGE: int
Z3_OP_RE_COMPLEMENT: int
Z3_OP_FPA_NUM: int
Z3_OP_FPA_PLUS_INF: int
Z3_OP_FPA_MINUS_INF: int
Z3_OP_FPA_NAN: int
Z3_OP_FPA_PLUS_ZERO: int
Z3_OP_FPA_MINUS_ZERO: int
Z3_INT_SORT: int
Z3_BOOL_SORT: int
Z3_REAL_SORT: int
Z3_BV_SORT: int
Z3_ARRAY_SORT: int
Z3_DATATYPE_SORT: int
Z3_FLOATING_POINT_SORT: int
Z3_SEQ_SORT: int
Z3_RE_SORT: int
Z3_UNINTERPRETED_SORT: int

# ── Context ────────────────────────────────────────────────────

class Context:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def main_ctx() -> Context: ...
def set_param(*args: Any, **kwargs: Any) -> None: ...
def get_param(name: str) -> str: ...
def reset_params() -> None: ...

# ── Z3Exception ────────────────────────────────────────────────

class Z3Exception(Exception): ...
