# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from pysymex._internal.reporting.html.styles import HTML_STYLES

HTML_TEMPLATE = (
    """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - pysymex Report</title>
    <style>
"""
    + HTML_STYLES
    + """
    </style>
</head>
<body>
    <div class="page">
        <header class="report-header">
            <div class="report-header__top">
                <h1 class="report-title">{title}</h1>
                <span class="report-badge">pysymex report</span>
            </div>
            <dl class="meta-grid">
                <div>
                    <dt>Target</dt>
                    <dd>{file_path}</dd>
                </div>
                <div>
                    <dt>Function</dt>
                    <dd>{function_name}()</dd>
                </div>
                <div>
                    <dt>Generated</dt>
                    <dd>{timestamp}</dd>
                </div>
                <div>
                    <dt>Duration</dt>
                    <dd>{duration:.2f}s</dd>
                </div>
            </dl>
        </header>
        {error_html}
        <div class="summary" role="group" aria-label="Scan summary">
            <div class="summary__cell">
                <div class="summary__label">Issues</div>
                <div class="summary__value {issue_count_class}">{issue_count}</div>
            </div>
            <div class="summary__cell">
                <div class="summary__label">Paths explored</div>
                <div class="summary__value summary__value--neutral">{paths_explored}</div>
            </div>
            <div class="summary__cell">
                <div class="summary__label">Max depth</div>
                <div class="summary__value summary__value--neutral">{max_depth}</div>
            </div>
            <div class="summary__cell">
                <div class="summary__label">Status</div>
                <div class="summary__value {status_value_class}">{status}</div>
            </div>
        </div>
        <section class="section">
            <div class="section__head">Issues</div>
            <div class="section__body">
                {issues_html}
            </div>
        </section>
        <section class="section">
            <div class="section__head">Resource usage</div>
            <div class="section__body">
                {resources_html}
            </div>
        </section>
        <footer class="report-footer">
            Generated by pysymex v{version} &middot;
            <a href="https://github.com/darkoss1/pysymex">GitHub</a>
        </footer>
    </div>
</body>
</html>"""
)
