# pysymex: python symbolic execution & formal verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Canonical configuration defaults used across pysymex."""

from __future__ import annotations

from typing import Final

VERSION: Final = "0.1.1a1"

CONFIG_FILE_NAMES: Final = (
    ".pysymex.toml",
    "pysymex.toml",
    "pyproject.toml",
)

DEFAULT_SOLVER_STRATEGY: Final = "incremental"
DEFAULT_SOLVER_CACHE_SIZE: Final = 50000
DEFAULT_SOLVER_LAZY_EVAL_THRESHOLD: Final = 20
DEFAULT_SOLVER_COMPACTION_INTERVAL: Final = 50
DEFAULT_SOLVER_PORTFOLIO_TIMEOUT_MS: Final = 100
DEFAULT_SOLVER_WARM_START: Final = True
DEFAULT_SOLVER_SIMPLIFY_CONSTRAINTS: Final = True
DEFAULT_SOLVER_TIMEOUT_MS: Final = 10000

DEFAULT_CONCURRENCY_ENABLED: Final = False
DEFAULT_CONCURRENCY_DETECT_RACES: Final = True
DEFAULT_CONCURRENCY_DETECT_DEADLOCKS: Final = True
DEFAULT_CONCURRENCY_ASYNC_ANALYSIS: Final = True
DEFAULT_CONCURRENCY_MAX_INTERLEAVINGS: Final = 1000
DEFAULT_CONCURRENCY_DPOR_ENABLED: Final = True
DEFAULT_CONCURRENCY_LOCKSET_ANALYSIS: Final = True

DEFAULT_DETECT_DIVISION_BY_ZERO: Final = True
DEFAULT_DETECT_ASSERTION_ERRORS: Final = True
DEFAULT_DETECT_INDEX_ERRORS: Final = True
DEFAULT_DETECT_TYPE_ERRORS: Final = True
DEFAULT_DETECT_KEY_ERRORS: Final = True
DEFAULT_DETECT_ATTRIBUTE_ERRORS: Final = True
DEFAULT_DETECT_OVERFLOW: Final = False
DEFAULT_DETECT_NULL_POINTER: Final = True

DEFAULT_LIMIT_MAX_PATHS: Final = 1000
DEFAULT_LIMIT_MAX_DEPTH: Final = 100
DEFAULT_LIMIT_MAX_ITERATIONS: Final = 10000
DEFAULT_LIMIT_TIMEOUT_SECONDS: Final = 60.0
DEFAULT_LIMIT_MAX_MEMORY_MB: Final = 1024
DEFAULT_LIMIT_MAX_CONSTRAINT_SIZE: Final = 10000
DEFAULT_LIMIT_MAX_STRING_LENGTH: Final = 1000
DEFAULT_LIMIT_MAX_LIST_LENGTH: Final = 100

DEFAULT_OUTPUT_FORMAT: Final = "text"
DEFAULT_OUTPUT_COLOR: Final = True
DEFAULT_OUTPUT_VERBOSE: Final = False
DEFAULT_OUTPUT_QUIET: Final = False
DEFAULT_OUTPUT_SHOW_PATHS: Final = True
DEFAULT_OUTPUT_SHOW_CONSTRAINTS: Final = False
DEFAULT_OUTPUT_SHOW_TIMING: Final = True

DEFAULT_ANALYSIS_STRATEGY: Final = "adaptive"
DEFAULT_ANALYSIS_LOOP_UNROLL_LIMIT: Final = 10
DEFAULT_ANALYSIS_ARRAY_SIZE_LIMIT: Final = 50
DEFAULT_ANALYSIS_STRING_SOLVER: Final = "z3str3"
DEFAULT_ANALYSIS_INCREMENTAL_SOLVING: Final = True
DEFAULT_ANALYSIS_CONSTRAINT_CACHING: Final = True
DEFAULT_ANALYSIS_INCLUDE_PATTERNS: Final = ("**/*.py",)
DEFAULT_ANALYSIS_EXCLUDE_PATTERNS: Final = (
    "**/test_*.py",
    "**/*_test.py",
    "**/tests/**",
    "**/tests_backup/**",
    "**/.venv/**",
    "**/venv/**",
    "**/node_modules/**",
)

DEFAULT_SCAN_MODE: Final = "symbolic"
SCAN_MODE_CHOICES: Final = ("symbolic",)
SCAN_OUTPUT_FORMAT_CHOICES: Final = ("text", "json", "sarif", "rich", "html", "markdown")
DEFAULT_SCAN_OUTPUT_FORMAT: Final = "text"
DEFAULT_SCAN_MAX_PATHS: Final = 5000
DEFAULT_SCAN_TIMEOUT_SECONDS: Final = 10
DEFAULT_SCAN_WORKERS: Final = 0
DEFAULT_SCAN_MAX_ITERATIONS: Final = 0
DEFAULT_SCAN_SANDBOX: Final = True
DEFAULT_SCAN_DETERMINISTIC: Final = False
DEFAULT_SCAN_RANDOM_SEED: Final = 42

DEFAULT_SCANNER_FILE_MAX_PATHS: Final = 100
DEFAULT_SCANNER_DIRECTORY_MAX_PATHS: Final = 200
DEFAULT_SCANNER_TIMEOUT_SECONDS: Final = 30.0
DEFAULT_SCANNER_DIRECTORY_TIMEOUT_SECONDS: Final = 30
DEFAULT_SCANNER_CLI_DIRECTORY: Final = "."
DEFAULT_SCANNER_CLI_RECURSIVE: Final = True
DEFAULT_SCANNER_CLI_WORKERS: Final = 0
DEFAULT_SCANNER_CLI_MAX_ITERATIONS: Final = 0

DEFAULT_ASYNC_SCANNER_PROCESS_POOL: Final = True

DEFAULT_ANALYZE_MAX_PATHS: Final = 100000
DEFAULT_ANALYZE_TIMEOUT_SECONDS: Final = 60
DEFAULT_BENCHMARK_ITERATIONS: Final = 1
DEFAULT_CHECK_FAIL_ON: Final = "high"

DEFAULT_VERIFIED_SOLVER_TIMEOUT_MS: Final = 250
DEFAULT_VERIFIED_TERMINATION_TIMEOUT_MS: Final = 10000
DEFAULT_VERIFIED_INTEGER_BITS: Final = 64

DEFAULT_TRACE_OUTPUT_DIR: Final = ".pysymex/traces"
TRACE_VERBOSITY_CHOICES: Final = ("quiet", "delta_only", "full")
DEFAULT_TRACE_VERBOSITY: Final = "delta_only"
DEFAULT_TRACE_ENABLED: Final = False
DEFAULT_TRACE_DELTA_BATCH_SIZE: Final = 50
DEFAULT_TRACE_KEYFRAME_ON_FORK: Final = True
DEFAULT_TRACE_KEYFRAME_ON_PRUNE: Final = True
DEFAULT_TRACE_KEYFRAME_ON_ISSUE: Final = True
DEFAULT_TRACE_MAX_CONSTRAINT_DISPLAY: Final = 50
DEFAULT_TRACE_COMPRESSION_LEVEL: Final = 6

__all__ = [
    "CONFIG_FILE_NAMES",
    "DEFAULT_ANALYSIS_ARRAY_SIZE_LIMIT",
    "DEFAULT_ANALYSIS_CONSTRAINT_CACHING",
    "DEFAULT_ANALYSIS_EXCLUDE_PATTERNS",
    "DEFAULT_ANALYSIS_INCREMENTAL_SOLVING",
    "DEFAULT_ANALYSIS_INCLUDE_PATTERNS",
    "DEFAULT_ANALYSIS_LOOP_UNROLL_LIMIT",
    "DEFAULT_ANALYSIS_STRATEGY",
    "DEFAULT_ANALYSIS_STRING_SOLVER",
    "DEFAULT_ANALYZE_MAX_PATHS",
    "DEFAULT_ANALYZE_TIMEOUT_SECONDS",
    "DEFAULT_ASYNC_SCANNER_PROCESS_POOL",
    "DEFAULT_BENCHMARK_ITERATIONS",
    "DEFAULT_CHECK_FAIL_ON",
    "DEFAULT_CONCURRENCY_ASYNC_ANALYSIS",
    "DEFAULT_CONCURRENCY_DETECT_DEADLOCKS",
    "DEFAULT_CONCURRENCY_DETECT_RACES",
    "DEFAULT_CONCURRENCY_DPOR_ENABLED",
    "DEFAULT_CONCURRENCY_ENABLED",
    "DEFAULT_CONCURRENCY_LOCKSET_ANALYSIS",
    "DEFAULT_CONCURRENCY_MAX_INTERLEAVINGS",
    "DEFAULT_DETECT_ASSERTION_ERRORS",
    "DEFAULT_DETECT_ATTRIBUTE_ERRORS",
    "DEFAULT_DETECT_DIVISION_BY_ZERO",
    "DEFAULT_DETECT_INDEX_ERRORS",
    "DEFAULT_DETECT_KEY_ERRORS",
    "DEFAULT_DETECT_NULL_POINTER",
    "DEFAULT_DETECT_OVERFLOW",
    "DEFAULT_DETECT_TYPE_ERRORS",
    "DEFAULT_LIMIT_MAX_CONSTRAINT_SIZE",
    "DEFAULT_LIMIT_MAX_DEPTH",
    "DEFAULT_LIMIT_MAX_ITERATIONS",
    "DEFAULT_LIMIT_MAX_LIST_LENGTH",
    "DEFAULT_LIMIT_MAX_MEMORY_MB",
    "DEFAULT_LIMIT_MAX_PATHS",
    "DEFAULT_LIMIT_MAX_STRING_LENGTH",
    "DEFAULT_LIMIT_TIMEOUT_SECONDS",
    "DEFAULT_OUTPUT_COLOR",
    "DEFAULT_OUTPUT_FORMAT",
    "DEFAULT_OUTPUT_QUIET",
    "DEFAULT_OUTPUT_SHOW_CONSTRAINTS",
    "DEFAULT_OUTPUT_SHOW_PATHS",
    "DEFAULT_OUTPUT_SHOW_TIMING",
    "DEFAULT_OUTPUT_VERBOSE",
    "DEFAULT_SCAN_DETERMINISTIC",
    "DEFAULT_SCAN_MAX_ITERATIONS",
    "DEFAULT_SCAN_MAX_PATHS",
    "DEFAULT_SCAN_MODE",
    "DEFAULT_SCAN_OUTPUT_FORMAT",
    "DEFAULT_SCAN_RANDOM_SEED",
    "DEFAULT_SCAN_SANDBOX",
    "DEFAULT_SCAN_TIMEOUT_SECONDS",
    "DEFAULT_SCAN_WORKERS",
    "DEFAULT_SCANNER_CLI_DIRECTORY",
    "DEFAULT_SCANNER_CLI_MAX_ITERATIONS",
    "DEFAULT_SCANNER_CLI_RECURSIVE",
    "DEFAULT_SCANNER_CLI_WORKERS",
    "DEFAULT_SCANNER_DIRECTORY_MAX_PATHS",
    "DEFAULT_SCANNER_DIRECTORY_TIMEOUT_SECONDS",
    "DEFAULT_SCANNER_FILE_MAX_PATHS",
    "DEFAULT_SCANNER_TIMEOUT_SECONDS",
    "DEFAULT_SOLVER_CACHE_SIZE",
    "DEFAULT_SOLVER_COMPACTION_INTERVAL",
    "DEFAULT_SOLVER_LAZY_EVAL_THRESHOLD",
    "DEFAULT_SOLVER_PORTFOLIO_TIMEOUT_MS",
    "DEFAULT_SOLVER_SIMPLIFY_CONSTRAINTS",
    "DEFAULT_SOLVER_STRATEGY",
    "DEFAULT_SOLVER_TIMEOUT_MS",
    "DEFAULT_SOLVER_WARM_START",
    "DEFAULT_TRACE_COMPRESSION_LEVEL",
    "DEFAULT_TRACE_DELTA_BATCH_SIZE",
    "DEFAULT_TRACE_ENABLED",
    "DEFAULT_TRACE_KEYFRAME_ON_FORK",
    "DEFAULT_TRACE_KEYFRAME_ON_ISSUE",
    "DEFAULT_TRACE_KEYFRAME_ON_PRUNE",
    "DEFAULT_TRACE_MAX_CONSTRAINT_DISPLAY",
    "DEFAULT_TRACE_OUTPUT_DIR",
    "DEFAULT_TRACE_VERBOSITY",
    "DEFAULT_VERIFIED_INTEGER_BITS",
    "DEFAULT_VERIFIED_SOLVER_TIMEOUT_MS",
    "DEFAULT_VERIFIED_TERMINATION_TIMEOUT_MS",
    "SCAN_MODE_CHOICES",
    "SCAN_OUTPUT_FORMAT_CHOICES",
    "TRACE_VERBOSITY_CHOICES",
    "VERSION",
]
