# pysymex: Python Symbolic Execution & Formal Verification
# Upstream Repository: https://github.com/darkoss1/pysymex
#
# Copyright (C) 2026 pysymex Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Models module for Python builtins and standard library (lazy-loaded).

All public symbols are loaded on first access via ``__getattr__``.
"""

from __future__ import annotations

from importlib import import_module

_EXPORTS: dict[str, tuple[str, str]] = {
    "ASYNCIO_MODELS": ("pysymex.models.concurrency.asyncio", "ASYNCIO_MODELS"),
    "ConditionModel": ("pysymex.models.concurrency.asyncio", "ConditionModel"),
    "CoroutineModel": ("pysymex.models.concurrency.asyncio", "CoroutineModel"),
    "EventModel": ("pysymex.models.concurrency.asyncio", "EventModel"),
    "FutureModel": ("pysymex.models.concurrency.asyncio", "FutureModel"),
    "LockModel": ("pysymex.models.concurrency.asyncio", "LockModel"),
    "QueueModel": ("pysymex.models.concurrency.asyncio", "QueueModel"),
    "SemaphoreModel": ("pysymex.models.concurrency.asyncio", "SemaphoreModel"),
    "TaskModel": ("pysymex.models.concurrency.asyncio", "TaskModel"),
    "get_asyncio_model": ("pysymex.models.concurrency.asyncio", "get_asyncio_model"),
    "AbsModel": ("pysymex.models.builtins", "AbsModel"),
    "BoolModel": ("pysymex.models.builtins", "BoolModel"),
    "FunctionModel": ("pysymex.models.builtins", "FunctionModel"),
    "IntModel": ("pysymex.models.builtins", "IntModel"),
    "LenModel": ("pysymex.models.builtins", "LenModel"),
    "MaxModel": ("pysymex.models.builtins", "MaxModel"),
    "MinModel": ("pysymex.models.builtins", "MinModel"),
    "ModelRegistry": ("pysymex.models.builtins", "ModelRegistry"),
    "ModelResult": ("pysymex.models.builtins", "ModelResult"),
    "PrintModel": ("pysymex.models.builtins", "PrintModel"),
    "RangeModel": ("pysymex.models.builtins", "RangeModel"),
    "StrModel": ("pysymex.models.builtins", "StrModel"),
    "default_model_registry": ("pysymex.models.builtins", "default_model_registry"),
    "CONTEXTLIB_MODELS": ("pysymex.models.stdlib.contextlib", "CONTEXTLIB_MODELS"),
    "AsyncContextManagerModel": ("pysymex.models.stdlib.contextlib", "AsyncContextManagerModel"),
    "AsyncExitStackModel": ("pysymex.models.stdlib.contextlib", "AsyncExitStackModel"),
    "ContextDecoratorModel": ("pysymex.models.stdlib.contextlib", "ContextDecoratorModel"),
    "ContextManagerModel": ("pysymex.models.stdlib.contextlib", "ContextManagerModel"),
    "ExitStackModel": ("pysymex.models.stdlib.contextlib", "ExitStackModel"),
    "get_contextlib_model": ("pysymex.models.stdlib.contextlib", "get_contextlib_model"),
    "DATACLASSES_MODELS": ("pysymex.models.stdlib.dataclasses", "DATACLASSES_MODELS"),
    "FieldInfo": ("pysymex.models.stdlib.dataclasses", "FieldInfo"),
    "asdict_model": ("pysymex.models.stdlib.dataclasses", "asdict_model"),
    "astuple_model": ("pysymex.models.stdlib.dataclasses", "astuple_model"),
    "dataclass_model": ("pysymex.models.stdlib.dataclasses", "dataclass_model"),
    "field_model": ("pysymex.models.stdlib.dataclasses", "field_model"),
    "fields_model": ("pysymex.models.stdlib.dataclasses", "fields_model"),
    "get_dataclasses_model": ("pysymex.models.stdlib.dataclasses", "get_dataclasses_model"),
    "is_dataclass_model": ("pysymex.models.stdlib.dataclasses", "is_dataclass_model"),
    "make_dataclass_model": ("pysymex.models.stdlib.dataclasses", "make_dataclass_model"),
    "replace_model": ("pysymex.models.stdlib.dataclasses", "replace_model"),
    "DICT_MODELS": ("pysymex.models.containers.dicts", "DICT_MODELS"),
    "DictGetModel": ("pysymex.models.containers.dicts", "DictGetModel"),
    "DictItemsModel": ("pysymex.models.containers.dicts", "DictItemsModel"),
    "DictKeysModel": ("pysymex.models.containers.dicts", "DictKeysModel"),
    "DictValuesModel": ("pysymex.models.containers.dicts", "DictValuesModel"),
    "LIST_MODELS": ("pysymex.models.containers.lists", "LIST_MODELS"),
    "ListAppendModel": ("pysymex.models.containers.lists", "ListAppendModel"),
    "ListExtendModel": ("pysymex.models.containers.lists", "ListExtendModel"),
    "ListInsertModel": ("pysymex.models.containers.lists", "ListInsertModel"),
    "ListPopModel": ("pysymex.models.containers.lists", "ListPopModel"),
    "BoundMethod": ("pysymex.models.objects", "BoundMethod"),
    "ClassRegistry": ("pysymex.models.objects", "ClassRegistry"),
    "MethodType": ("pysymex.models.objects", "MethodType"),
    "SymbolicAttribute": ("pysymex.models.objects", "SymbolicAttribute"),
    "SymbolicClass": ("pysymex.models.objects", "SymbolicClass"),
    "SymbolicDescriptor": ("pysymex.models.objects", "SymbolicDescriptor"),
    "SymbolicInstance": ("pysymex.models.objects", "SymbolicInstance"),
    "SymbolicMethod": ("pysymex.models.objects", "SymbolicMethod"),
    "SymbolicProperty": ("pysymex.models.objects", "SymbolicProperty"),
    "TypeChecker": ("pysymex.models.objects", "TypeChecker"),
    "REGEX_MODELS": ("pysymex.models.stdlib.regex", "REGEX_MODELS"),
    "PatternCompiler": ("pysymex.models.stdlib.regex", "PatternCompiler"),
    "ReCompileModel": ("pysymex.models.stdlib.regex", "ReCompileModel"),
    "ReEscapeModel": ("pysymex.models.stdlib.regex", "ReEscapeModel"),
    "ReFullmatchModel": ("pysymex.models.stdlib.regex", "ReFullmatchModel"),
    "ReSplitModel": ("pysymex.models.stdlib.regex", "ReSplitModel"),
    "ReSubModel": ("pysymex.models.stdlib.regex", "ReSubModel"),
    "compile_pattern": ("pysymex.models.stdlib.regex", "compile_pattern"),
    "EnhancedReFindallModel": ("pysymex.models.stdlib.regex", "ReFindallModel"),
    "EnhancedReMatchModel": ("pysymex.models.stdlib.regex", "ReMatchModel"),
    "EnhancedReSearchModel": ("pysymex.models.stdlib.regex", "ReSearchModel"),
    "SET_MODELS": ("pysymex.models.containers.sets", "SET_MODELS"),
    "SetAddModel": ("pysymex.models.containers.sets", "SetAddModel"),
    "SetClearModel": ("pysymex.models.containers.sets", "SetClearModel"),
    "SetContainsModel": ("pysymex.models.containers.sets", "SetContainsModel"),
    "SetCopyModel": ("pysymex.models.containers.sets", "SetCopyModel"),
    "SetDiscardModel": ("pysymex.models.containers.sets", "SetDiscardModel"),
    "SetIntersectionModel": ("pysymex.models.containers.sets", "SetIntersectionModel"),
    "SetLenModel": ("pysymex.models.containers.sets", "SetLenModel"),
    "SetPopModel": ("pysymex.models.containers.sets", "SetPopModel"),
    "SetRemoveModel": ("pysymex.models.containers.sets", "SetRemoveModel"),
    "SetUnionModel": ("pysymex.models.containers.sets", "SetUnionModel"),
    "SetDifferenceModel": ("pysymex.models.containers.sets", "SetDifferenceModel"),
    "SetSymmetricDifferenceModel": (
        "pysymex.models.containers.sets",
        "SetSymmetricDifferenceModel",
    ),
    "SetIssubsetModel": ("pysymex.models.containers.sets", "SetIssubsetModel"),
    "SetIssupersetModel": ("pysymex.models.containers.sets", "SetIssupersetModel"),
    "SetIsdisjointModel": ("pysymex.models.containers.sets", "SetIsdisjointModel"),
    "SetUpdateModel": ("pysymex.models.containers.sets", "SetUpdateModel"),
    "SetIntersectionUpdateModel": ("pysymex.models.containers.sets", "SetIntersectionUpdateModel"),
    "SetDifferenceUpdateModel": ("pysymex.models.containers.sets", "SetDifferenceUpdateModel"),
    "SetSymmetricDifferenceUpdateModel": (
        "pysymex.models.containers.sets",
        "SetSymmetricDifferenceUpdateModel",
    ),
    "TUPLE_MODELS": ("pysymex.models.containers.tuples", "TUPLE_MODELS"),
    "TupleModel": ("pysymex.models.containers.tuples", "TupleModel"),
    "TupleGetitemModel": ("pysymex.models.containers.tuples", "TupleGetitemModel"),
    "TupleContainsModel": ("pysymex.models.containers.tuples", "TupleContainsModel"),
    "TupleLenModel": ("pysymex.models.containers.tuples", "TupleLenModel"),
    "TupleCountModel": ("pysymex.models.containers.tuples", "TupleCountModel"),
    "TupleIndexModel": ("pysymex.models.containers.tuples", "TupleIndexModel"),
    "TupleAddModel": ("pysymex.models.containers.tuples", "TupleAddModel"),
    "TupleMulModel": ("pysymex.models.containers.tuples", "TupleMulModel"),
    "TupleSliceModel": ("pysymex.models.containers.tuples", "TupleSliceModel"),
    "TupleEqModel": ("pysymex.models.containers.tuples", "TupleEqModel"),
    "TupleHashModel": ("pysymex.models.containers.tuples", "TupleHashModel"),
    "ListSetitemModel": ("pysymex.models.containers.lists", "ListSetitemModel"),
    "ListDelitemModel": ("pysymex.models.containers.lists", "ListDelitemModel"),
    "ListAddModel": ("pysymex.models.containers.lists", "ListAddModel"),
    "ListMulModel": ("pysymex.models.containers.lists", "ListMulModel"),
    "ListEqModel": ("pysymex.models.containers.lists", "ListEqModel"),
    "ListIaddModel": ("pysymex.models.containers.lists", "ListIaddModel"),
    "ListImulModel": ("pysymex.models.containers.lists", "ListImulModel"),
    "ExecModel": ("pysymex.models.builtins", "ExecModel"),
    "EvalModel": ("pysymex.models.builtins", "EvalModel"),
    "CompileModel": ("pysymex.models.builtins", "CompileModel"),
    "BinModel": ("pysymex.models.builtins", "BinModel"),
    "OctModel": ("pysymex.models.builtins", "OctModel"),
    "HexModel": ("pysymex.models.builtins", "HexModel"),
    "BytesModel": ("pysymex.models.builtins", "BytesModel"),
    "BytearrayModel": ("pysymex.models.builtins", "BytearrayModel"),
    "FrozensetModel": ("pysymex.models.builtins", "FrozensetModel"),
    "MemoryviewModel": ("pysymex.models.builtins", "MemoryviewModel"),
    "ObjectModel": ("pysymex.models.builtins", "ObjectModel"),
    "PropertyModel": ("pysymex.models.builtins", "PropertyModel"),
    "ClassmethodModel": ("pysymex.models.builtins", "ClassmethodModel"),
    "StaticmethodModel": ("pysymex.models.builtins", "StaticmethodModel"),
    "VarsModel": ("pysymex.models.builtins", "VarsModel"),
    "DirModel": ("pysymex.models.builtins", "DirModel"),
    "AsciiModel": ("pysymex.models.builtins", "AsciiModel"),
    "BreakpointModel": ("pysymex.models.builtins", "BreakpointModel"),
    "BYTES_MODELS": ("pysymex.models.containers.bytes", "BYTES_MODELS"),
    "FROZENSET_MODELS": ("pysymex.models.containers.frozensets", "FROZENSET_MODELS"),
    "INT_FLOAT_MODELS": ("pysymex.models.numeric", "INT_FLOAT_MODELS"),
    "CounterModel": ("pysymex.models.stdlib", "CounterModel"),
    "DefaultdictModel": ("pysymex.models.stdlib", "DefaultdictModel"),
    "DequeModel": ("pysymex.models.stdlib", "DequeModel"),
    "ExtendedStdlibRegistry": ("pysymex.models.stdlib", "ExtendedStdlibRegistry"),
    "ItertoolsChainModel": ("pysymex.models.stdlib", "ItertoolsChainModel"),
    "ItertoolsIsliceModel": ("pysymex.models.stdlib", "ItertoolsIsliceModel"),
    "ItertoolsProductModel": ("pysymex.models.stdlib", "ItertoolsProductModel"),
    "JsonDumpsModel": ("pysymex.models.stdlib", "JsonDumpsModel"),
    "JsonLoadsModel": ("pysymex.models.stdlib", "JsonLoadsModel"),
    "MathCeilModel": ("pysymex.models.stdlib", "MathCeilModel"),
    "MathCosModel": ("pysymex.models.stdlib", "MathCosModel"),
    "MathExpModel": ("pysymex.models.stdlib", "MathExpModel"),
    "MathFloorModel": ("pysymex.models.stdlib", "MathFloorModel"),
    "MathLogModel": ("pysymex.models.stdlib", "MathLogModel"),
    "MathSinModel": ("pysymex.models.stdlib", "MathSinModel"),
    "MathSqrtModel": ("pysymex.models.stdlib", "MathSqrtModel"),
    "OrderedDictModel": ("pysymex.models.stdlib", "OrderedDictModel"),
    "RandomChoiceModel": ("pysymex.models.stdlib", "RandomChoiceModel"),
    "RandomRandintModel": ("pysymex.models.stdlib", "RandomRandintModel"),
    "ReFindallModel": ("pysymex.models.stdlib", "ReFindallModel"),
    "ReMatchModel": ("pysymex.models.stdlib", "ReMatchModel"),
    "ReSearchModel": ("pysymex.models.stdlib", "ReSearchModel"),
    "extended_stdlib_registry": ("pysymex.models.stdlib", "extended_stdlib_registry"),
    "get_stdlib_model": ("pysymex.models.stdlib", "get_stdlib_model"),
    "list_stdlib_models": ("pysymex.models.stdlib", "list_stdlib_models"),
    "list_stdlib_modules": ("pysymex.models.stdlib", "list_stdlib_modules"),
    "STRING_MODELS": ("pysymex.models.containers.strings", "STRING_MODELS"),
    "StrJoinModel": ("pysymex.models.containers.strings", "StrJoinModel"),
    "StrLowerModel": ("pysymex.models.containers.strings", "StrLowerModel"),
    "StrReplaceModel": ("pysymex.models.containers.strings", "StrReplaceModel"),
    "StrSplitModel": ("pysymex.models.containers.strings", "StrSplitModel"),
    "StrStripModel": ("pysymex.models.containers.strings", "StrStripModel"),
    "StrUpperModel": ("pysymex.models.containers.strings", "StrUpperModel"),
    "THREADING_MODELS": ("pysymex.models.concurrency.threading", "THREADING_MODELS"),
    "BarrierModel": ("pysymex.models.concurrency.threading", "BarrierModel"),
    "ThreadingConditionModel": ("pysymex.models.concurrency.threading", "ConditionModel"),
    "ThreadingEventModel": ("pysymex.models.concurrency.threading", "EventModel"),
    "ThreadingLockModel": ("pysymex.models.concurrency.threading", "LockModel"),
    "RLockModel": ("pysymex.models.concurrency.threading", "RLockModel"),
    "ThreadingSemaphoreModel": ("pysymex.models.concurrency.threading", "SemaphoreModel"),
    "ThreadModel": ("pysymex.models.concurrency.threading", "ThreadModel"),
    "get_threading_model": ("pysymex.models.concurrency.threading", "get_threading_model"),
    "COLLECTIONS_MODELS": ("pysymex.models.stdlib.collections", "COLLECTIONS_MODELS"),
    "ChainMapModel": ("pysymex.models.stdlib.collections", "ChainMapModel"),
    "EnhancedCounterModel": ("pysymex.models.stdlib.collections", "CounterModel"),
    "DefaultDictModel": ("pysymex.models.stdlib.collections", "DefaultDictModel"),
    "EnhancedDequeModel": ("pysymex.models.stdlib.collections", "DequeModel"),
    "EnhancedOrderedDictModel": ("pysymex.models.stdlib.collections", "OrderedDictModel"),
    "get_collections_model": ("pysymex.models.stdlib.collections", "get_collections_model"),
    "register_collections_models": (
        "pysymex.models.stdlib.collections",
        "register_collections_models",
    ),
    "ITERTOOLS_MODELS": ("pysymex.models.stdlib.itertools", "ITERTOOLS_MODELS"),
    "get_itertools_model": ("pysymex.models.stdlib.itertools", "get_itertools_model"),
    "register_itertools_models": ("pysymex.models.stdlib.itertools", "register_itertools_models"),
    "FUNCTOOLS_MODELS": ("pysymex.models.stdlib.functools", "FUNCTOOLS_MODELS"),
    "PartialModel": ("pysymex.models.stdlib.functools", "PartialModel"),
    "get_functools_model": ("pysymex.models.stdlib.functools", "get_functools_model"),
    "register_functools_models": ("pysymex.models.stdlib.functools", "register_functools_models"),
    "PATHLIB_MODELS": ("pysymex.models.stdlib.pathlib", "PATHLIB_MODELS"),
}


def __getattr__(name: str) -> object:
    """Lazy-load model exports to prevent eager side-effect imports."""
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
    module_name, attr_name = target
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Dir."""
    return sorted(set(_EXPORTS.keys()) | set(globals()))
